<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Campus;
use App\Models\ServicePoint;

class CampusSeeder extends Seeder
{
    public function run(): void
    {
        $main = Campus::firstOrCreate(['slug' => 'main-campus'], [
            'name'            => 'Main Campus — Kaimosi',
            'summary'         => 'The flagship campus of Kaimosi Friends University, nestled in the scenic highlands of Vihiga County, Western Kenya.',
            'description'     => "Kaimosi Friends University's Main Campus sits on over 350 acres of land in Kaimosi, Vihiga County. Founded in the Quaker tradition, the campus is home to the majority of KAFU's schools, faculties, research centres, student accommodation, and administrative offices. The serene forest environment provides an ideal setting for academic excellence and community life.",
            'address'         => 'P.O. Box 27 — 50309, Kaimosi, Vihiga County, Kenya',
            'county'          => 'Vihiga',
            'region'          => 'Western Kenya',
            'latitude'        => 0.1295,
            'longitude'       => 34.9085,
            'hero_image'      => '/images/uploads/IMG_8696.jpg',
            'gallery_images'  => ['/img6424.jpg', '/pic1.jpg'],
            'contact_email'   => 'info@kafu.ac.ke',
            'contact_phone'   => '+254 700 000 000',
            'visitor_notes'   => 'The main gate is open 24 hours. Visitor registration is required at the security desk. Campus tours can be arranged through the Public Relations office.',
            'transport_notes' => 'From Kisumu: Take a matatu (Route 31) to Kaimosi Market, then a bodaboda to the university gate (~35 min). From Kakamega: Direct matatus run to Kaimosi (~45 min). The campus is 2 km from the main Kisumu–Kapsabet highway.',
            'sort_order'      => 1,
            'status'          => 'active',
        ]);

        $kisumu = Campus::firstOrCreate(['slug' => 'kisumu-campus'], [
            'name'            => 'Kisumu Campus',
            'summary'         => 'KAFU\'s urban satellite campus in Kisumu City, offering selected programmes and professional development courses.',
            'description'     => "The Kisumu Campus provides accessible higher education opportunities within Kisumu City. It offers selected undergraduate and postgraduate programmes, short courses, and professional development training. The campus serves students from the Lake Basin region and beyond.",
            'address'         => 'Kisumu City Centre, Kisumu County, Kenya',
            'county'          => 'Kisumu',
            'region'          => 'Nyanza',
            'latitude'        => -0.0917,
            'longitude'       => 34.7680,
            'hero_image'      => null,
            'gallery_images'  => [],
            'contact_email'   => 'kisumu@kafu.ac.ke',
            'contact_phone'   => '+254 700 000 001',
            'visitor_notes'   => 'Please contact the campus office in advance to arrange visits.',
            'transport_notes' => 'Located in Kisumu City Centre, accessible by public transport from Kisumu Bus Station. Taxi and boda boda services readily available.',
            'sort_order'      => 2,
            'status'          => 'active',
        ]);

        Campus::firstOrCreate(['slug' => 'kobujoi'], [
            'name'            => 'Kobujoi Campus',
            'summary'         => 'KAFU\'s newest campus, officially opened on 8th September 2025 in Aldai Constituency, Nandi County — focused on STEM, teacher education, and agricultural innovation.',
            'description'     => "Kaimosi Friends University continues to expand its footprint in higher education through the establishment of Kobujoi Campus in Aldai Constituency, Nandi County. The Campus reflects the University's commitment to expanding access to quality higher education, promoting inclusivity, and supporting socio-economic transformation through teaching, research, innovation, and community engagement.\n\nThe establishment of Kobujoi Campus was inspired by a development tour by His Excellency the President of the Republic of Kenya, William Samoei Ruto, on 24th August 2024, during which local leaders and residents appealed for a university presence in the region. In response, KAFU embraced the vision in alignment with the Government's Bottom-Up Economic Transformation Agenda (BETA).\n\nKobujoi Campus officially opened its doors on 8th September 2025 with the admission of its pioneer Bachelor of Education (Arts) students. The Campus is strategically positioning itself as a regional hub for STEM, teacher education, agricultural innovation, and industrial crop development. The Campus is directed by Prof. Remmy Shiundu.",
            'address'         => 'Aldai Constituency, Nandi County, Kenya',
            'county'          => 'Nandi',
            'region'          => 'Rift Valley',
            'latitude'        => 0.1742,
            'longitude'       => 35.2935,
            'hero_image'      => '/images/uploads/Members-of-the-University-Council-tour-Kaimosi-Friends-Universitys-Kobujoi-Campus-during-the-three-day-familiarization-and-induction-programme.jpeg',
            'gallery_images'  => [
                '/images/uploads/image-110.jpeg',
                '/images/uploads/image-93.jpeg',
                '/images/uploads/image-80.jpeg',
                '/images/uploads/image-94.jpeg',
            ],
            'contact_email'   => 'kobujoi@kafu.ac.ke',
            'contact_phone'   => '+254 700 000 002',
            'visitor_notes'   => 'Please contact the campus office in advance to arrange visits. The campus is located on the former Aldai High School and Ressio Comprehensive Primary School grounds in Aldai Constituency.',
            'transport_notes' => 'From Eldoret: Take a matatu towards Kapsabet or Nandi Hills and alight at Aldai Junction (approx. 1 hour). From Kapsabet Town: Direct matatus run to Aldai (approx. 30 minutes). From Kisumu: Travel via Chemelil towards Kapsabet, then proceed to Aldai.',
            'sort_order'      => 3,
            'status'          => 'active',
        ]);

        $offices = [
            [
                'name'              => 'Admissions Office',
                'slug'              => 'admissions-office',
                'category'          => 'admissions',
                'campus_id'         => $main->id,
                'building'          => 'Administration Block, Ground Floor',
                'contact_person'    => 'Head of Admissions',
                'public_phone'      => '+254 700 000 100',
                'public_email'      => 'admissions@kafu.ac.ke',
                'whatsapp'          => '+254 700 000 100',
                'physical_location' => 'Administration Block, Ground Floor, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => '8:00 AM – 1:00 PM', 'sun' => 'Closed'],
                'summary'           => 'The Admissions Office handles all undergraduate and postgraduate application inquiries, admission letters, and enrolment processes.',
                'support_scope'     => 'Application inquiries, admission status, joining instructions, deferrals, transfers, and re-admission requests.',
                'sort_order'        => 1,
            ],
            [
                'name'              => 'Registrar\'s Office',
                'slug'              => 'registrars-office',
                'category'          => 'registrar',
                'campus_id'         => $main->id,
                'building'          => 'Administration Block, First Floor',
                'contact_person'    => 'University Registrar',
                'public_phone'      => '+254 700 000 200',
                'public_email'      => 'registrar@kafu.ac.ke',
                'physical_location' => 'Administration Block, First Floor, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => 'Closed', 'sun' => 'Closed'],
                'summary'           => 'The Registrar\'s Office manages student records, academic transcripts, letters of verification, graduation, and course registration.',
                'support_scope'     => 'Academic transcripts, student status letters, graduation clearance, course registration, semester records.',
                'sort_order'        => 2,
            ],
            [
                'name'              => 'Finance Office',
                'slug'              => 'finance-office',
                'category'          => 'finance',
                'campus_id'         => $main->id,
                'building'          => 'Administration Block, Ground Floor',
                'contact_person'    => 'Finance Officer',
                'public_phone'      => '+254 700 000 300',
                'public_email'      => 'finance@kafu.ac.ke',
                'physical_location' => 'Administration Block, Ground Floor, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => '8:00 AM – 12:00 PM', 'sun' => 'Closed'],
                'summary'           => 'The Finance Office manages fee payments, receipts, student financial statements, and HELB disbursements.',
                'support_scope'     => 'Fee payment, financial clearance, HELB queries, receipts, fee structure inquiries.',
                'sort_order'        => 3,
            ],
            [
                'name'              => 'Student Affairs Office',
                'slug'              => 'student-affairs-office',
                'category'          => 'student_affairs',
                'campus_id'         => $main->id,
                'building'          => 'Student Centre',
                'contact_person'    => 'Dean of Students',
                'public_phone'      => '+254 700 000 400',
                'public_email'      => 'students@kafu.ac.ke',
                'physical_location' => 'Student Centre, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 6:00 PM', 'sat' => '9:00 AM – 1:00 PM', 'sun' => 'Closed'],
                'summary'           => 'Student Affairs coordinates student welfare, clubs, hall management, counselling referrals, and discipline.',
                'support_scope'     => 'Student welfare, accommodation allocation, clubs and societies, student ID, disciplinary matters.',
                'sort_order'        => 4,
            ],
            [
                'name'              => 'ICT Support Centre',
                'slug'              => 'ict-support',
                'category'          => 'ict',
                'campus_id'         => $main->id,
                'building'          => 'ICT Building',
                'contact_person'    => 'ICT Director',
                'public_phone'      => '+254 700 000 500',
                'public_email'      => 'ict@kafu.ac.ke',
                'physical_location' => 'ICT Building, Main Campus',
                'operating_hours'   => ['mon_fri' => '7:30 AM – 7:00 PM', 'sat' => '8:00 AM – 2:00 PM', 'sun' => 'Closed'],
                'summary'           => 'The ICT Support Centre provides technical assistance for university systems, student portals, email, Wi-Fi, and computing resources.',
                'support_scope'     => 'Student portal access, email setup, Wi-Fi support, computer labs, software licensing, system issues.',
                'sort_order'        => 5,
            ],
            [
                'name'              => 'University Library',
                'slug'              => 'library',
                'category'          => 'library',
                'campus_id'         => $main->id,
                'building'          => 'Library Block',
                'contact_person'    => 'University Librarian',
                'public_phone'      => '+254 700 000 600',
                'public_email'      => 'library@kafu.ac.ke',
                'physical_location' => 'Library Block, Main Campus',
                'operating_hours'   => ['mon_fri' => '7:00 AM – 9:00 PM', 'sat' => '8:00 AM – 4:00 PM', 'sun' => '10:00 AM – 4:00 PM'],
                'summary'           => 'The KAFU Library provides physical and digital resources to support learning and research across all disciplines.',
                'support_scope'     => 'Book borrowing, digital databases, research support, e-resources, interlibrary loans, reading rooms.',
                'sort_order'        => 6,
            ],
            [
                'name'              => 'Health Services Centre',
                'slug'              => 'health-services',
                'category'          => 'health',
                'campus_id'         => $main->id,
                'building'          => 'Health Centre',
                'contact_person'    => 'Medical Officer',
                'public_phone'      => '+254 700 000 700',
                'public_email'      => 'health@kafu.ac.ke',
                'physical_location' => 'Health Centre, Near Student Hostels, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => '8:00 AM – 1:00 PM', 'sun' => 'Emergency Only'],
                'summary'           => 'The Health Services Centre provides primary healthcare to students and staff, including outpatient consultations, basic diagnostics, and referrals.',
                'support_scope'     => 'Outpatient consultations, first aid, health insurance guidance, mental health referrals, pharmacy.',
                'sort_order'        => 7,
            ],
            [
                'name'              => 'International & Partnerships Office',
                'slug'              => 'international-office',
                'category'          => 'international',
                'campus_id'         => $main->id,
                'building'          => 'Administration Block, Second Floor',
                'contact_person'    => 'Director of International Linkages',
                'public_phone'      => '+254 700 000 800',
                'public_email'      => 'international@kafu.ac.ke',
                'physical_location' => 'Administration Block, Second Floor, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => 'Closed', 'sun' => 'Closed'],
                'summary'           => 'The International Office coordinates international student admissions, exchange programmes, and institutional partnerships.',
                'support_scope'     => 'International student support, visa guidance, exchange programme applications, partnership inquiries.',
                'sort_order'        => 8,
            ],
            [
                'name'              => 'Research & Innovation Office',
                'slug'              => 'research-office',
                'category'          => 'research',
                'campus_id'         => $main->id,
                'building'          => 'Research Block',
                'contact_person'    => 'Director of Research & Innovation',
                'public_phone'      => '+254 700 000 900',
                'public_email'      => 'research@kafu.ac.ke',
                'physical_location' => 'Research Block, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => 'Closed', 'sun' => 'Closed'],
                'summary'           => 'Coordinates research ethics, grants management, innovation support, and industry collaboration at KAFU.',
                'support_scope'     => 'Research ethics clearance, grant applications, research collaborations, publication support.',
                'sort_order'        => 9,
            ],
            [
                'name'              => 'Procurement Office',
                'slug'              => 'procurement-office',
                'category'          => 'procurement',
                'campus_id'         => $main->id,
                'building'          => 'Administration Block, Ground Floor',
                'contact_person'    => 'Procurement Officer',
                'public_phone'      => '+254 700 001 000',
                'public_email'      => 'procurement@kafu.ac.ke',
                'physical_location' => 'Administration Block, Ground Floor, Main Campus',
                'operating_hours'   => ['mon_fri' => '8:00 AM – 5:00 PM', 'sat' => 'Closed', 'sun' => 'Closed'],
                'summary'           => 'Handles all procurement, tendering, supplier registration, and purchasing processes for the university.',
                'support_scope'     => 'Supplier registration, tender notices, purchase orders, procurement inquiries.',
                'sort_order'        => 10,
            ],
        ];

        Campus::firstOrCreate(['slug' => 'vokoli'], [
            'name'            => 'Vokoli Campus',
            'summary'         => 'KAFU\'s Vokoli Campus brings higher education to Vihiga County, extending the university\'s reach and providing accessible academic opportunities to communities in the region.',
            'description'     => "Kaimosi Friends University's Vokoli Campus is part of the university's strategic expansion plan to improve access to quality higher education across Western Kenya. Located in Vihiga County, the campus serves students from the surrounding communities and is committed to the university's mission of transformative education, research, and community service.\n\nThe campus offers programmes aligned with local development priorities and is developing into a centre for community engagement and skills development for the region.",
            'address'         => 'Vokoli, Vihiga County, Kenya',
            'county'          => 'Vihiga',
            'region'          => 'Western',
            'latitude'        => 0.0847,
            'longitude'       => 34.7218,
            'hero_image'      => null,
            'gallery_images'  => [],
            'contact_email'   => 'vokoli@kafu.ac.ke',
            'contact_phone'   => '+254 700 000 003',
            'visitor_notes'   => 'Please contact the campus office in advance to arrange visits.',
            'transport_notes' => 'From Kisumu: Take a matatu towards Vihiga and alight at Vokoli. From Kakamega: Direct matatus run towards Vihiga County. The campus is accessible from the main Kisumu–Kakamega road.',
            'sort_order'      => 4,
            'status'          => 'active',
        ]);

        foreach ($offices as $office) {
            ServicePoint::firstOrCreate(['slug' => $office['slug']], $office);
        }
    }
}
