<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CmsContent;
use Carbon\Carbon;

class ContentMigrationSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Helper: upsert — skip if slug+type already exists as published
        $upsert = function (array $data) use ($now) {
            $existing = CmsContent::where('type', $data['type'])
                ->where('slug', $data['slug'])
                ->where('is_deleted', false)
                ->first();
            if ($existing) {
                return; // already seeded
            }
            CmsContent::create(array_merge([
                'status'       => 'published',
                'published_at' => $now,
                'is_deleted'   => false,
                'author_id'    => 1,
            ], $data));
        };

        // ─────────────────────────────────────────────────────────────
        // SCHOOLS
        // ─────────────────────────────────────────────────────────────
        $schools = [
            [
                'code'  => 'SESS',
                'name'  => 'School of Education and Social Sciences',
                'dean'  => 'Dr. Nabeta K.N. Sangili',
                'colour' => '#1B3A6B',
                'description' => 'SESS offers programmes in teacher education, social work, criminology, disaster management, and social sciences.',
                'vision'  => 'To be a centre of excellence in Education and Social Sciences in Africa.',
                'mission' => 'To provide quality education through teaching, research, and community engagement.',
                'undergrad_count' => 7,
                'postgrad_count'  => 7,
                'doctoral_count'  => 2,
            ],
            [
                'code'  => 'SBE',
                'name'  => 'School of Business and Economics',
                'dean'  => 'Dr. Atieno Margaret Omondi',
                'colour' => '#D4A017',
                'description' => 'SBE empowers students to become transformative leaders and responsible professionals.',
                'vision'  => 'To be a centre of excellence in teaching professional and market driven courses.',
                'mission' => 'To provide professional and market driven courses that enable graduates fit in the labour market.',
                'undergrad_count' => 3,
                'postgrad_count'  => 2,
                'doctoral_count'  => 1,
            ],
            [
                'code'  => 'SCIT',
                'name'  => 'School of Computing and Information Technology',
                'dean'  => 'Prof. Kelvin K. Omieno',
                'colour' => '#0D6EFD',
                'description' => 'SCIT trains solution-oriented ICT experts capable of transforming the digital economy locally and globally.',
                'vision'  => 'To be a center of excellence in teaching, research, and innovation in computing and information technology for sustainable development.',
                'mission' => 'To provide quality education in computing and IT through innovative teaching, research, and industry engagement.',
                'undergrad_count' => 2,
                'postgrad_count'  => 1,
                'doctoral_count'  => 0,
            ],
            [
                'code'  => 'SOS',
                'name'  => 'School of Science',
                'dean'  => 'Dr. Annette O. Busula',
                'colour' => '#198754',
                'description' => 'SOS offers rigorous science programmes spanning physics, chemistry, biology, mathematics, statistics, and agricultural economics.',
                'vision'  => 'To be a centre of excellence in scientific research and education.',
                'mission' => 'To provide quality science education through teaching, research, and innovation.',
                'undergrad_count' => 7,
                'postgrad_count'  => 4,
                'doctoral_count'  => 0,
            ],
            [
                'code'  => 'SHS',
                'name'  => 'School of Health Sciences',
                'dean'  => 'Prof. Winnie Awino',
                'colour' => '#8B1A1A',
                'description' => 'Established in 2022, SHS is one of only two institutions in Kenya offering Optometry up to PhD level.',
                'vision'  => 'To be a centre of excellence in health sciences education and research in East and Central Africa.',
                'mission' => 'To train competent health professionals through quality education, research, and clinical practice.',
                'undergrad_count' => 3,
                'postgrad_count'  => 0,
                'doctoral_count'  => 0,
            ],
        ];

        foreach ($schools as $s) {
            $upsert([
                'type'        => 'school',
                'slug'        => strtolower($s['code']),
                'school_code' => $s['code'],
                'title'       => $s['name'],
                'summary'     => $s['description'],
                'body'        => $s['description'],
                'structured_data' => [
                    'dean'           => $s['dean'],
                    'colour'         => $s['colour'],
                    'vision'         => $s['vision'],
                    'mission'        => $s['mission'],
                    'programmes_count' => [
                        'undergraduate' => $s['undergrad_count'],
                        'postgraduate'  => $s['postgrad_count'],
                        'doctoral'      => $s['doctoral_count'],
                    ],
                ],
            ]);
        }

        // ─────────────────────────────────────────────────────────────
        // PROGRAMMES
        // ─────────────────────────────────────────────────────────────
        $programmes = [
            // SESS
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Education (Arts)','code'=>'BEd (Arts)','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Education (French)','code'=>'BEd (French)','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Education (Science)','code'=>'BEd (Science)','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Social Work','code'=>'BSW','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Education (ECD)','code'=>'BEd ECD','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Disaster Management and International Diplomacy','code'=>'BDMID','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'undergraduate','name'=>'Bachelor of Arts in Criminology and Criminal Justice','code'=>'BA Criminology','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Arts in Religion','code'=>'MA Religion','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Arts in Comparative Literature','code'=>'MA Comp. Lit.','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Education in Educational Psychology','code'=>'MEd Ed. Psych.','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Arts in English Language','code'=>'MA English','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Arts in Kiswahili','code'=>'MA Kiswahili','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Arts in Geography','code'=>'MA Geography','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'postgraduate','name'=>'Master of Arts in History','code'=>'MA History','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'doctoral','name'=>'Doctor of Philosophy in Comparative Literature','code'=>'PhD Comp. Lit.','duration'=>'3-5 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SESS','level'=>'doctoral','name'=>'Doctor of Philosophy in Religion','code'=>'PhD Religion','duration'=>'3-5 years','mode'=>'Full-time / Part-time'],
            // SBE
            ['school'=>'SBE','level'=>'undergraduate','name'=>'Bachelor of Commerce','code'=>'BCom','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SBE','level'=>'undergraduate','name'=>'Bachelor of Science in Economics','code'=>'BSc Economics','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SBE','level'=>'undergraduate','name'=>'Bachelor of Science in Economics and Statistics','code'=>'BSc Econ & Stats','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SBE','level'=>'postgraduate','name'=>'Master of Business Administration','code'=>'MBA','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SBE','level'=>'postgraduate','name'=>'Master of Science in Economics','code'=>'MSc Economics','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SBE','level'=>'doctoral','name'=>'Doctor of Philosophy in Business Administration','code'=>'PhD Bus. Admin.','duration'=>'3-5 years','mode'=>'Full-time / Part-time'],
            // SCIT
            ['school'=>'SCIT','level'=>'undergraduate','name'=>'Bachelor of Science in Computer Science','code'=>'BSc CS','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SCIT','level'=>'undergraduate','name'=>'Bachelor of Science in Information Technology','code'=>'BSc IT','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SCIT','level'=>'postgraduate','name'=>'Master of Science in Information Technology','code'=>'MSc IT','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            // SOS
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Physics with Appropriate Technology','code'=>'BSc Physics','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Chemistry','code'=>'BSc Chemistry','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Mathematics with IT','code'=>'BSc Maths+IT','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Applied Statistics with IT','code'=>'BSc Stat+IT','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Biology','code'=>'BSc Biology','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Agricultural Economics and Resource Management','code'=>'BSc Agric. Econ.','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'undergraduate','name'=>'Bachelor of Science in Economics and Statistics','code'=>'BSc Econ+Stats','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SOS','level'=>'postgraduate','name'=>'Master of Science in Physics','code'=>'MSc Physics','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SOS','level'=>'postgraduate','name'=>'Master of Science in Applied Mathematics','code'=>'MSc Appl. Maths','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SOS','level'=>'postgraduate','name'=>'Master of Science in Pure Mathematics','code'=>'MSc Pure Maths','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            ['school'=>'SOS','level'=>'postgraduate','name'=>'Master of Science in Microbiology','code'=>'MSc Microbiology','duration'=>'2 years','mode'=>'Full-time / Part-time'],
            // SHS
            ['school'=>'SHS','level'=>'undergraduate','name'=>'Bachelor of Optometry and Vision Sciences','code'=>'BOptom','duration'=>'5 years','mode'=>'Full-time'],
            ['school'=>'SHS','level'=>'undergraduate','name'=>'Bachelor of Science in Nursing','code'=>'BSN','duration'=>'4 years','mode'=>'Full-time'],
            ['school'=>'SHS','level'=>'undergraduate','name'=>'Bachelor of Science in Clinical Medicine and Community Health','code'=>'BSc Clinical Med.','duration'=>'4 years','mode'=>'Full-time'],
        ];

        foreach ($programmes as $p) {
            $slug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $p['school'] . '-' . $p['code']));
            $slug = trim($slug, '-');
            $upsert([
                'type'        => 'programme',
                'slug'        => $slug,
                'school_code' => $p['school'],
                'title'       => $p['name'],
                'body'        => '',
                'structured_data' => [
                    'level'            => $p['level'],
                    'programme_code'   => $p['code'],
                    'duration'         => $p['duration'],
                    'mode'             => $p['mode'],
                    'requirements'     => [],
                    'career_opportunities' => [],
                ],
            ]);
        }

        // ─────────────────────────────────────────────────────────────
        // STAFF PROFILES
        // ─────────────────────────────────────────────────────────────
        $staff = [
            // ── University Leadership ──────────────────────────────
            [
                'slug'        => 'prof-peter-n-mwita',
                'school_code' => null,
                'title'       => 'Prof. Peter Nyamuhanga Mwita',
                'structured_data' => [
                    'prefix'      => 'Prof.',
                    'first_name'  => 'Peter',
                    'middle_name' => 'Nyamuhanga',
                    'last_name'   => 'Mwita',
                    'designation' => 'Vice-Chancellor',
                    'department'  => 'Office of the Vice-Chancellor',
                    'unit'        => 'University Leadership',
                    'email'       => 'vc@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Prof. Peter Nyamuhanga Mwita is the Vice-Chancellor of Kaimosi Friends University (KAFU), officially appointed on 14 May 2025 having served as Acting Vice-Chancellor since 19 February 2024. As the university\'s Chief Executive and Chief Academic Officer, he holds comprehensive responsibility for KAFU\'s administrative, academic, financial, and external relations. Prof. Mwita has anchored his tenure in a bold transformational agenda: he spearheaded the launch of KAFU\'s 2023–2027 Strategic Plan aimed at positioning the institution as a world-class university of excellence in teaching, research, and community engagement in alignment with Kenya\'s Vision 2030. He led the university\'s inaugural Innovation Week, bringing together researchers, innovators, and industry to solve real-world challenges. Under his leadership, KAFU became a key partner in a $95 million zero-emission biofuel project projected to create over 1,200 jobs and generate long-term income for the university.',
                    'specializations' => ['Higher Education Leadership', 'Institutional Governance', 'Innovation and Entrepreneurship', 'Strategic Planning'],
                    'qualifications'  => [
                        ['year'=>'2005','qualification'=>'Doctor of Philosophy (Statistics)','institution'=>'University of Nairobi'],
                        ['year'=>'1999','qualification'=>'Master of Science (Statistics)','institution'=>'University of Nairobi'],
                        ['year'=>'1996','qualification'=>'Bachelor of Science (Mathematics and Statistics)','institution'=>'University of Nairobi'],
                    ],
                    'experience' => [
                        ['start'=>'2025','end'=>'Present','position'=>'Vice-Chancellor','institution'=>'Kaimosi Friends University'],
                        ['start'=>'2024','end'=>'2025','position'=>'Acting Vice-Chancellor','institution'=>'Kaimosi Friends University'],
                    ],
                    'research_interests' => ['Higher education governance and policy','Innovation ecosystems in African universities','Strategic planning in public universities','Sustainable development and university-industry partnerships'],
                    'teaching_areas'     => ['Statistical Methods','Research Design','Higher Education Leadership'],
                    'memberships'        => ['Inter-University Council for East Africa','Association of African Universities','Kenya Universities and Colleges Central Placement Service (KUCCPS) Board'],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'prof-james-a-shikuku',
                'school_code' => null,
                'title'       => 'Prof. James A. Shikuku',
                'structured_data' => [
                    'prefix'      => 'Prof.',
                    'first_name'  => 'James',
                    'middle_name' => 'A.',
                    'last_name'   => 'Shikuku',
                    'designation' => 'Deputy Vice-Chancellor (Academic Affairs)',
                    'department'  => 'Academic Affairs',
                    'unit'        => 'University Leadership',
                    'email'       => 'dvc.academics@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Prof. Shikuku oversees academic programmes, quality assurance, and curriculum development across all five schools of the university.',
                    'specializations' => ['Curriculum Development', 'Quality Assurance', 'Academic Policy'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'mr-thomas-m-mwangi',
                'school_code' => null,
                'title'       => 'Mr. Thomas M. Mwangi',
                'structured_data' => [
                    'prefix'      => 'Mr.',
                    'first_name'  => 'Thomas',
                    'middle_name' => 'M.',
                    'last_name'   => 'Mwangi',
                    'designation' => 'University Registrar',
                    'department'  => 'Registry',
                    'unit'        => 'University Administration',
                    'email'       => 'registrar@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Mr. Mwangi serves as University Registrar, overseeing academic records, student admissions, and institutional governance documentation.',
                    'specializations' => ['Academic Administration', 'Records Management', 'Student Affairs'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            // ── SESS ───────────────────────────────────────────────
            [
                'slug'        => 'dr-nabeta-kn-sangili',
                'school_code' => 'SESS',
                'title'       => 'Dr. Nabeta K.N. Sangili',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Nabeta',
                    'middle_name' => 'K.N.',
                    'last_name'   => 'Sangili',
                    'designation' => 'Dean, School of Education and Social Sciences',
                    'department'  => 'Education',
                    'unit'        => null,
                    'email'       => 'dean.sess@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Nabeta K.N. Sangili is the Dean of the School of Education and Social Sciences at Kaimosi Friends University. With over fifteen years of experience in teacher education and educational research, Dr. Sangili has led the school in expanding its programme offering and deepening its community engagement. His doctoral research examined the effectiveness of professional development models for secondary school teachers in Kenya\'s rural counties. He is a committed advocate for inclusive education and the integration of indigenous knowledge in teacher preparation curricula.',
                    'specializations' => ['Teacher Education', 'Educational Psychology', 'Curriculum Studies'],
                    'qualifications'  => [
                        ['year'=>'2013','qualification'=>'Doctor of Philosophy (Education)','institution'=>'Maseno University'],
                        ['year'=>'2006','qualification'=>'Master of Education (Educational Psychology)','institution'=>'Maseno University'],
                        ['year'=>'2002','qualification'=>'Bachelor of Education (Arts)','institution'=>'Kaimosi Friends University College'],
                    ],
                    'experience' => [
                        ['start'=>'2018','end'=>'Present','position'=>'Dean','institution'=>'SESS, Kaimosi Friends University'],
                        ['start'=>'2013','end'=>'2018','position'=>'Senior Lecturer','institution'=>'SESS, Kaimosi Friends University'],
                        ['start'=>'2007','end'=>'2013','position'=>'Lecturer','institution'=>'SESS, Kaimosi Friends University'],
                    ],
                    'research_interests' => ['Teacher professional development','Inclusive education','Educational psychology','Indigenous knowledge in education'],
                    'teaching_areas'     => ['Educational Psychology','Curriculum Studies','Teaching Methods'],
                    'memberships'        => ['Kenya National Examinations Council','East Africa Educational Research Association'],
                    'publications' => [
                        ['citation'=>'Sangili, K.N. (2019). "Peer Mentoring and Teacher Effectiveness in Rural Kenya." African Journal of Teacher Education, 8(2), 44–61.','url'=>null],
                        ['citation'=>'Sangili, K.N. & Omondi, M.A. (2021). "Indigenous Knowledge Integration in Kenyan Teacher Education Programmes." Journal of Curriculum Studies in Africa, 3(1), 12–29.','url'=>null],
                    ],
                    'awards' => ['Best Dean Award, KAFU Academic Staff Recognition 2022'],
                ],
            ],
            [
                'slug'        => 'dr-jane-wesonga',
                'school_code' => 'SESS',
                'title'       => 'Dr. Jane Wesonga',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Jane',
                    'middle_name' => null,
                    'last_name'   => 'Wesonga',
                    'designation' => 'Senior Lecturer',
                    'department'  => 'Social Work',
                    'unit'        => null,
                    'email'       => 'j.wesonga@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Jane Wesonga is a Senior Lecturer in Social Work at KAFU. She brings extensive field experience in community development, child protection programming, and social welfare policy across Western Kenya. Her research examines intersections between social inequality, child welfare, and rural livelihoods.',
                    'specializations' => ['Community Development', 'Child Protection', 'Social Policy'],
                    'qualifications'  => [
                        ['year'=>'2018','qualification'=>'Doctor of Philosophy (Social Work)','institution'=>'Maseno University'],
                        ['year'=>'2012','qualification'=>'Master of Arts (Social Work)','institution'=>'Makerere University'],
                        ['year'=>'2007','qualification'=>'Bachelor of Social Work','institution'=>'Kaimosi Friends University College'],
                    ],
                    'experience' => [
                        ['start'=>'2018','end'=>'Present','position'=>'Senior Lecturer','institution'=>'SESS, KAFU'],
                        ['start'=>'2013','end'=>'2018','position'=>'Lecturer','institution'=>'SESS, KAFU'],
                        ['start'=>'2008','end'=>'2013','position'=>'Field Social Worker','institution'=>'World Vision Kenya'],
                    ],
                    'research_interests' => ['Child welfare','Community development','Social protection policy','Gender and social exclusion'],
                    'teaching_areas'     => ['Social Work Theory and Practice','Community Development','Child Protection'],
                    'memberships'        => ['Kenya Association of Social Workers'],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'mr-peter-mutuku',
                'school_code' => 'SESS',
                'title'       => 'Mr. Peter Mutuku',
                'structured_data' => [
                    'prefix'      => 'Mr.',
                    'first_name'  => 'Peter',
                    'middle_name' => null,
                    'last_name'   => 'Mutuku',
                    'designation' => 'Lecturer',
                    'department'  => 'Criminology',
                    'unit'        => null,
                    'email'       => 'p.mutuku@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Mr. Peter Mutuku is a Lecturer in Criminology and Criminal Justice. His academic interest centres on restorative justice models, prison reform, and alternatives to incarceration in the Kenyan context. He has worked with the Kenya Prisons Service and non-governmental organisations on community-based rehabilitation programmes.',
                    'specializations' => ['Criminology', 'Criminal Justice', 'Restorative Justice'],
                    'qualifications'  => [
                        ['year'=>'2017','qualification'=>'Master of Arts (Criminology)','institution'=>'University of Nairobi'],
                        ['year'=>'2013','qualification'=>'Bachelor of Arts (Criminology)','institution'=>'Moi University'],
                    ],
                    'experience' => [
                        ['start'=>'2018','end'=>'Present','position'=>'Lecturer','institution'=>'SESS, KAFU'],
                        ['start'=>'2015','end'=>'2018','position'=>'Programme Officer','institution'=>'Prison Fellowship Kenya'],
                    ],
                    'research_interests' => ['Restorative justice','Prison reform','Crime prevention','Juvenile justice'],
                    'teaching_areas'     => ['Criminology','Criminal Justice Administration','Penology'],
                    'memberships'        => ['Kenya Society of Criminology'],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'dr-mary-auma-omondi',
                'school_code' => 'SESS',
                'title'       => 'Dr. Mary Auma Omondi',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Mary',
                    'middle_name' => 'Auma',
                    'last_name'   => 'Omondi',
                    'designation' => 'Lecturer',
                    'department'  => 'Early Childhood Education',
                    'unit'        => null,
                    'email'       => 'm.auma@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Omondi specialises in early childhood education and child development. She coordinates the BEd ECD programme and conducts research on learning outcomes in rural early childhood settings.',
                    'specializations' => ['Early Childhood Development', 'Pedagogy', 'Child Psychology'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'rev-prof-david-simiyu',
                'school_code' => 'SESS',
                'title'       => 'Rev. Prof. David Simiyu',
                'structured_data' => [
                    'prefix'      => 'Rev. Prof.',
                    'first_name'  => 'David',
                    'middle_name' => null,
                    'last_name'   => 'Simiyu',
                    'designation' => 'Professor of Religious Studies',
                    'department'  => 'Religious Studies',
                    'unit'        => null,
                    'email'       => 'd.simiyu@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Rev. Prof. Simiyu is a theologian and Quaker minister with over two decades of scholarship in African traditional religion and Quaker ethics. He has authored several books on religion and society in East Africa.',
                    'specializations' => ['African Traditional Religion', 'Quaker Theology', 'Ethics and Moral Philosophy'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            // ── SBE ────────────────────────────────────────────────
            [
                'slug'        => 'dr-atieno-margaret-omondi',
                'school_code' => 'SBE',
                'title'       => 'Dr. Atieno Margaret Omondi',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Atieno',
                    'middle_name' => 'Margaret',
                    'last_name'   => 'Omondi',
                    'designation' => 'Dean, School of Business and Economics',
                    'department'  => 'Business Administration',
                    'unit'        => null,
                    'email'       => 'dean.sbe@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Atieno Margaret Omondi is the Dean of the School of Business and Economics. A strategic management scholar with a deep commitment to entrepreneurship education, Dr. Omondi has been instrumental in building SBE into one of the fastest-growing business schools in Western Kenya. Her research examines SME growth constraints, women\'s economic empowerment, and business incubation in emerging economies.',
                    'specializations' => ['Strategic Management', 'Entrepreneurship', 'SME Development'],
                    'qualifications'  => [
                        ['year'=>'2015','qualification'=>'Doctor of Philosophy (Business Administration)','institution'=>'University of Nairobi'],
                        ['year'=>'2009','qualification'=>'Master of Business Administration','institution'=>'Strathmore University'],
                        ['year'=>'2004','qualification'=>'Bachelor of Commerce (Marketing)','institution'=>'Moi University'],
                    ],
                    'experience' => [
                        ['start'=>'2020','end'=>'Present','position'=>'Dean','institution'=>'SBE, Kaimosi Friends University'],
                        ['start'=>'2015','end'=>'2020','position'=>'Senior Lecturer','institution'=>'SBE, Kaimosi Friends University'],
                        ['start'=>'2010','end'=>'2015','position'=>'Lecturer','institution'=>'SBE, Kaimosi Friends University'],
                    ],
                    'research_interests' => ['Entrepreneurship education','SME growth and financing','Women in business','Strategic leadership in Africa'],
                    'teaching_areas'     => ['Strategic Management','Entrepreneurship and Innovation','Business Research Methods'],
                    'memberships'        => ['Kenya Institute of Management','African Academy of Business','Women in Business Kenya'],
                    'publications' => [
                        ['citation'=>'Omondi, A.M. (2022). "Gender and Growth Constraints in Kenyan SMEs: Evidence from Western Kenya." Journal of African Business, 23(1), 115–133.','url'=>null],
                        ['citation'=>'Omondi, A.M. & Wanjala, J. (2020). "University Business Incubators and Start-up Performance in Kenya." East African Journal of Business and Economics, 5(2), 45–62.','url'=>null],
                    ],
                    'awards' => ['Business Education Leadership Award, Kenya Institute of Management 2021'],
                ],
            ],
            [
                'slug'        => 'dr-francis-ochieng',
                'school_code' => 'SBE',
                'title'       => 'Dr. Francis Ochieng',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Francis',
                    'middle_name' => null,
                    'last_name'   => 'Ochieng',
                    'designation' => 'Senior Lecturer',
                    'department'  => 'Accounting and Finance',
                    'unit'        => null,
                    'email'       => 'f.ochieng@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Francis Ochieng is a Senior Lecturer in Accounting and Finance at KAFU. A CPA(K) and CGMA holder, he specialises in IFRS adoption, public sector financial management, and audit quality. His research examines how accounting reforms impact accountability in Kenyan county governments.',
                    'specializations' => ['Financial Reporting', 'Auditing', 'Public Sector Accounting', 'IFRS'],
                    'qualifications'  => [
                        ['year'=>'2019','qualification'=>'Doctor of Philosophy (Accounting)','institution'=>'University of Nairobi'],
                        ['year'=>'2012','qualification'=>'Master of Commerce (Finance)','institution'=>'Strathmore University'],
                        ['year'=>'2007','qualification'=>'Bachelor of Commerce (Accounting)','institution'=>'Maseno University'],
                    ],
                    'experience' => [
                        ['start'=>'2019','end'=>'Present','position'=>'Senior Lecturer','institution'=>'SBE, KAFU'],
                        ['start'=>'2012','end'=>'2019','position'=>'Lecturer','institution'=>'SBE, KAFU'],
                        ['start'=>'2007','end'=>'2012','position'=>'Auditor','institution'=>'Kenya National Audit Office'],
                    ],
                    'research_interests' => ['Public sector accounting','Audit quality','IFRS adoption in Africa','Financial governance'],
                    'teaching_areas'     => ['Financial Accounting','Auditing','Public Finance Management'],
                    'memberships'        => ['ICPAK','CGMA (Chartered Institute of Management Accountants)'],
                    'publications' => [
                        ['citation'=>'Ochieng, F. (2021). "IFRS Adoption and Reporting Quality in Kenyan County Governments." International Journal of Accounting and Information Management, 29(4), 567–584.','url'=>null],
                    ],
                    'awards' => [],
                ],
            ],
            [
                'slug'        => 'ms-grace-akinyi',
                'school_code' => 'SBE',
                'title'       => 'Ms. Grace Akinyi',
                'structured_data' => [
                    'prefix'      => 'Ms.',
                    'first_name'  => 'Grace',
                    'middle_name' => null,
                    'last_name'   => 'Akinyi',
                    'designation' => 'Lecturer',
                    'department'  => 'Marketing',
                    'unit'        => null,
                    'email'       => 'g.akinyi@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Ms. Akinyi lectures in Marketing and specialises in digital marketing strategy and consumer behaviour. She has consulted widely for SMEs and social enterprises in the Lake Victoria Basin region.',
                    'specializations' => ['Digital Marketing', 'Consumer Behaviour', 'Brand Strategy'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'dr-james-wanjala',
                'school_code' => 'SBE',
                'title'       => 'Dr. James Wanjala',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'James',
                    'middle_name' => null,
                    'last_name'   => 'Wanjala',
                    'designation' => 'Lecturer',
                    'department'  => 'Economics',
                    'unit'        => null,
                    'email'       => 'j.wanjala@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Wanjala is a development economist whose work focuses on food security, rural income diversification, and agricultural value chains in Western Kenya.',
                    'specializations' => ['Development Economics', 'Agricultural Economics', 'Econometrics'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            // ── SCIT ───────────────────────────────────────────────
            [
                'slug'        => 'prof-kelvin-k-omieno',
                'school_code' => 'SCIT',
                'title'       => 'Prof. Kelvin K. Omieno',
                'structured_data' => [
                    'prefix'      => 'Prof.',
                    'first_name'  => 'Kelvin',
                    'middle_name' => 'K.',
                    'last_name'   => 'Omieno',
                    'designation' => 'Dean, School of Computing and Information Technology',
                    'department'  => 'Computer Science',
                    'unit'        => null,
                    'email'       => 'dean.scit@kafu.ac.ke',
                    'photo'       => 'https://kafu.ac.ke/wp-content/uploads/Prof.-Omieno-1.jpg',
                    'biography'   => 'Prof. Kelvin K. Omieno is a Professor of Computer Science and the Dean of the School of Computing and Information Technology. A recognised authority in artificial intelligence and machine learning, Prof. Omieno has published extensively in the application of intelligent systems to healthcare, agriculture, and education in Africa. He leads the KAFU AI and Data Science Research Group.',
                    'specializations' => ['Artificial Intelligence', 'Machine Learning', 'Data Science', 'Software Engineering'],
                    'qualifications'  => [
                        ['year'=>'2009','qualification'=>'Doctor of Philosophy (Computer Science)','institution'=>'University of Nairobi'],
                        ['year'=>'2004','qualification'=>'Master of Science (Computer Science)','institution'=>'University of Nairobi'],
                        ['year'=>'2000','qualification'=>'Bachelor of Science (Computer Science)','institution'=>'Maseno University'],
                    ],
                    'experience' => [
                        ['start'=>'2019','end'=>'Present','position'=>'Dean and Professor of Computer Science','institution'=>'SCIT, Kaimosi Friends University'],
                        ['start'=>'2012','end'=>'2019','position'=>'Associate Professor of Computer Science','institution'=>'SCIT, Kaimosi Friends University'],
                        ['start'=>'2009','end'=>'2012','position'=>'Senior Lecturer','institution'=>'SCIT, Kaimosi Friends University'],
                    ],
                    'research_interests' => ['Artificial intelligence','Machine learning','Intelligent systems for healthcare','Data science in agriculture','Computer science education'],
                    'teaching_areas'     => ['Artificial Intelligence','Machine Learning','Algorithm Design','Software Engineering'],
                    'memberships'        => ['Kenya ICT Board Technical Committee','IEEE Computer Society','Association for Computing Machinery (ACM)','African Advanced Institute for Science and Technology'],
                    'publications' => [
                        ['citation'=>'Omieno, K.K. et al. (2022). "Machine Learning Models for Malaria Prediction Using Environmental Data from Western Kenya." Journal of Healthcare Informatics, 14(3), 201–218.','url'=>null],
                        ['citation'=>'Omieno, K.K. & Muthoni, R. (2020). "Intelligent Crop Disease Detection Using Convolutional Neural Networks." African Journal of Computing and ICT, 13(1), 77–95.','url'=>null],
                    ],
                    'awards' => ['Kenya ICT Authority Research Excellence Award 2021','KAFU Distinguished Researcher Award 2019'],
                ],
            ],
            [
                'slug'        => 'dr-ruth-muthoni',
                'school_code' => 'SCIT',
                'title'       => 'Dr. Ruth Muthoni',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Ruth',
                    'middle_name' => null,
                    'last_name'   => 'Muthoni',
                    'designation' => 'Senior Lecturer',
                    'department'  => 'Computer Science',
                    'unit'        => null,
                    'email'       => 'r.muthoni@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Ruth Muthoni is a Senior Lecturer in Computer Science whose research focuses on natural language processing (NLP) for low-resource African languages. Her work addresses the scarcity of computational resources and annotated corpora for Swahili, Luhya, and other Kenyan languages.',
                    'specializations' => ['Natural Language Processing', 'Text Mining', 'African Language Computing'],
                    'qualifications'  => [
                        ['year'=>'2020','qualification'=>'Doctor of Philosophy (Computer Science — NLP)','institution'=>'University of Groningen, Netherlands'],
                        ['year'=>'2013','qualification'=>'Master of Science (Computer Science)','institution'=>'University of Nairobi'],
                        ['year'=>'2010','qualification'=>'Bachelor of Science (Computer Science)','institution'=>'Maseno University'],
                    ],
                    'experience' => [
                        ['start'=>'2020','end'=>'Present','position'=>'Senior Lecturer','institution'=>'SCIT, KAFU'],
                        ['start'=>'2020','end'=>'2020','position'=>'Postdoctoral Fellow','institution'=>'MasakhaNE Project, Leiden University'],
                    ],
                    'research_interests' => ['NLP for African languages','Text mining','Machine translation','Computational linguistics'],
                    'teaching_areas'     => ['Artificial Intelligence','Natural Language Processing','Data Structures'],
                    'memberships'        => ['Association for Computational Linguistics (ACL)','ACM'],
                    'publications' => [
                        ['citation'=>'Muthoni, R. et al. (2022). "Named Entity Recognition for Swahili Using Transformer Models." Proceedings of AfricaNLP Workshop, EMNLP 2022.','url'=>null],
                    ],
                    'awards' => ['Google AI for Social Good Fellowship 2021'],
                ],
            ],
            [
                'slug'        => 'mr-brian-omondi',
                'school_code' => 'SCIT',
                'title'       => 'Mr. Brian Omondi',
                'structured_data' => [
                    'prefix'      => 'Mr.',
                    'first_name'  => 'Brian',
                    'middle_name' => null,
                    'last_name'   => 'Omondi',
                    'designation' => 'Lecturer',
                    'department'  => 'Information Technology',
                    'unit'        => null,
                    'email'       => 'b.omondi@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Mr. Omondi lectures in Information Technology with a focus on cloud infrastructure, network design, and systems architecture. He holds CCNA and AWS certifications.',
                    'specializations' => ['Network Administration', 'Cloud Computing', 'Systems Architecture'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'dr-lilian-kemunto',
                'school_code' => 'SCIT',
                'title'       => 'Dr. Lilian Kemunto',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Lilian',
                    'middle_name' => null,
                    'last_name'   => 'Kemunto',
                    'designation' => 'Lecturer',
                    'department'  => 'Information Security',
                    'unit'        => null,
                    'email'       => 'l.kemunto@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Kemunto specialises in cybersecurity and digital forensics. Her work addresses cyber threat intelligence, incident response, and digital safety frameworks for academic and public sector institutions.',
                    'specializations' => ['Cybersecurity', 'Digital Forensics', 'Information Assurance'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            // ── SOS ────────────────────────────────────────────────
            [
                'slug'        => 'dr-annette-o-busula',
                'school_code' => 'SOS',
                'title'       => 'Dr. Annette O. Busula',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Annette',
                    'middle_name' => 'O.',
                    'last_name'   => 'Busula',
                    'designation' => 'Dean, School of Science',
                    'department'  => 'Biological Sciences',
                    'unit'        => null,
                    'email'       => 'dean.sos@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Annette O. Busula is the Dean of the School of Science and a leading researcher in malaria parasitology and molecular diagnostics. Her doctoral and postdoctoral work focused on the molecular epidemiology of Plasmodium falciparum drug resistance in Africa, and her publications appear in major peer-reviewed journals including Malaria Journal, PLOS ONE, and Antimicrobial Agents and Chemotherapy.',
                    'specializations' => ['Molecular Biology', 'Parasitology', 'Infectious Disease Research'],
                    'qualifications'  => [
                        ['year'=>'2016','qualification'=>'Doctor of Philosophy (Molecular Biology)','institution'=>'University of Antwerp / Institute of Tropical Medicine'],
                        ['year'=>'2010','qualification'=>'Master of Science (Biochemistry)','institution'=>'University of Nairobi'],
                        ['year'=>'2007','qualification'=>'Bachelor of Science (Biological Sciences)','institution'=>'Maseno University'],
                    ],
                    'experience' => [
                        ['start'=>'2019','end'=>'Present','position'=>'Dean, School of Science','institution'=>'Kaimosi Friends University'],
                        ['start'=>'2016','end'=>'2019','position'=>'Senior Lecturer, Molecular Biology','institution'=>'Kaimosi Friends University'],
                        ['start'=>'2016','end'=>'2016','position'=>'Postdoctoral Research Fellow','institution'=>'Institute of Tropical Medicine, Antwerp'],
                    ],
                    'research_interests' => ['Malaria parasitology','Drug resistance in P. falciparum','Molecular diagnostics','Tropical infectious diseases','One Health approaches'],
                    'teaching_areas'     => ['Molecular Biology','Parasitology','Biochemistry','Research Methods in Life Sciences'],
                    'memberships'        => ['Kenya Medical Research Institute (Affiliate)','African Society for Laboratory Medicine','American Society of Tropical Medicine and Hygiene'],
                    'publications' => [
                        ['citation'=>'Busula, A.O. et al. (2017). "Mechanisms of Plasmodium falciparum resistance to artemisinin-based combination therapies." Malaria Journal, 16, 215.','url'=>'https://doi.org/10.1186/s12936-017-1872-y'],
                        ['citation'=>'Busula, A.O. et al. (2015). "Genetic diversity of Plasmodium falciparum isolates from Western Kenya." PLOS ONE, 10(11), e0141659.','url'=>null],
                    ],
                    'awards' => ['KAFU Distinguished Research Award 2020','KEMRI Young Scientist Award 2018'],
                ],
            ],
            [
                'slug'        => 'dr-charles-simiyu',
                'school_code' => 'SOS',
                'title'       => 'Dr. Charles Simiyu',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Charles',
                    'middle_name' => null,
                    'last_name'   => 'Simiyu',
                    'designation' => 'Senior Lecturer',
                    'department'  => 'Chemistry',
                    'unit'        => null,
                    'email'       => 'c.simiyu@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Charles Simiyu is a Senior Lecturer in Chemistry whose research focuses on environmental and analytical chemistry, particularly water quality monitoring in the Lake Victoria Basin. He has led several community-funded studies on heavy metal contamination and agrochemical runoff into rivers and wetlands in the region.',
                    'specializations' => ['Analytical Chemistry', 'Environmental Chemistry', 'Water Quality Analysis'],
                    'qualifications'  => [
                        ['year'=>'2016','qualification'=>'Doctor of Philosophy (Chemistry)','institution'=>'University of Nairobi'],
                        ['year'=>'2010','qualification'=>'Master of Science (Analytical Chemistry)','institution'=>'Kenyatta University'],
                        ['year'=>'2007','qualification'=>'Bachelor of Science (Chemistry)','institution'=>'Maseno University'],
                    ],
                    'experience' => [
                        ['start'=>'2016','end'=>'Present','position'=>'Senior Lecturer','institution'=>'SOS, KAFU'],
                        ['start'=>'2010','end'=>'2016','position'=>'Lecturer','institution'=>'SOS, KAFU'],
                    ],
                    'research_interests' => ['Water quality monitoring','Heavy metal contamination','Environmental pollution','Analytical methods development'],
                    'teaching_areas'     => ['Analytical Chemistry','Environmental Chemistry','Instrumental Analysis'],
                    'memberships'        => ['Kenya Chemical Society','Royal Society of Chemistry (Associate)'],
                    'publications' => [
                        ['citation'=>'Simiyu, C. et al. (2020). "Heavy Metal Contamination of Wetlands in the Lake Victoria Basin." Environmental Monitoring and Assessment, 192(6), 384.','url'=>null],
                    ],
                    'awards' => [],
                ],
            ],
            [
                'slug'        => 'dr-sarah-chebet',
                'school_code' => 'SOS',
                'title'       => 'Dr. Sarah Chebet',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Sarah',
                    'middle_name' => null,
                    'last_name'   => 'Chebet',
                    'designation' => 'Lecturer',
                    'department'  => 'Biological Sciences',
                    'unit'        => null,
                    'email'       => 's.chebet@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Chebet is a plant ecologist and botanist. Her fieldwork documents indigenous plant species in the Kakamega Forest Ecosystem and informs community-based conservation strategies.',
                    'specializations' => ['Ecology', 'Botany', 'Biodiversity Conservation'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'mr-gilbert-otieno',
                'school_code' => 'SOS',
                'title'       => 'Mr. Gilbert Otieno',
                'structured_data' => [
                    'prefix'      => 'Mr.',
                    'first_name'  => 'Gilbert',
                    'middle_name' => null,
                    'last_name'   => 'Otieno',
                    'designation' => 'Lecturer',
                    'department'  => 'Physics',
                    'unit'        => null,
                    'email'       => 'g.otieno@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Mr. Otieno lectures in Applied Physics and leads the university\'s Renewable Energy lab. His work explores solar photovoltaic systems and low-cost instrumentation for rural electrification.',
                    'specializations' => ['Applied Physics', 'Renewable Energy', 'Instrumentation'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            // ── SHS ────────────────────────────────────────────────
            [
                'slug'        => 'prof-winnie-awino',
                'school_code' => 'SHS',
                'title'       => 'Prof. Winnie Awino',
                'structured_data' => [
                    'prefix'      => 'Prof.',
                    'first_name'  => 'Winnie',
                    'middle_name' => null,
                    'last_name'   => 'Awino',
                    'designation' => 'Dean, School of Health Sciences',
                    'department'  => 'Optometry',
                    'unit'        => null,
                    'email'       => 'dean.shs@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Prof. Winnie Awino is a Professor of Optometry and the founding Dean of the School of Health Sciences. She has been central to the development of the Bachelor of Optometry programme — one of only two such programmes available up to PhD level in Kenya. Her clinical and academic work spans low vision rehabilitation, community eye health outreach, and the epidemiology of visual impairment in Western Kenya.',
                    'specializations' => ['Optometry', 'Low Vision Rehabilitation', 'Community Eye Health'],
                    'qualifications'  => [
                        ['year'=>'2011','qualification'=>'Doctor of Philosophy (Vision Science)','institution'=>'University of KwaZulu-Natal, South Africa'],
                        ['year'=>'2005','qualification'=>'Master of Science (Optometry)','institution'=>'University of Nairobi'],
                        ['year'=>'2001','qualification'=>'Bachelor of Science (Optometry)','institution'=>'University of Nairobi'],
                    ],
                    'experience' => [
                        ['start'=>'2017','end'=>'Present','position'=>'Dean and Professor of Optometry','institution'=>'SHS, Kaimosi Friends University'],
                        ['start'=>'2012','end'=>'2017','position'=>'Senior Lecturer in Optometry','institution'=>'SHS, Kaimosi Friends University'],
                        ['start'=>'2011','end'=>'2012','position'=>'Postdoctoral Research Associate','institution'=>'Brien Holden Vision Institute, Sydney'],
                    ],
                    'research_interests' => ['Low vision rehabilitation','Visual impairment epidemiology','Community eye health','Paediatric optometry','Refractive error in East Africa'],
                    'teaching_areas'     => ['Clinical Optometry','Low Vision','Ocular Disease','Community Eye Health'],
                    'memberships'        => ['Optometrists Association Kenya (OAK)','African Vision Research Institute','International Society for Low Vision Research and Rehabilitation'],
                    'publications' => [
                        ['citation'=>'Awino, W. & Otieno, M. (2023). "Prevalence of Refractive Error among School-Age Children in Western Kenya." Clinical and Experimental Optometry, 106(2), 198–207.','url'=>null],
                        ['citation'=>'Awino, W. (2019). "Low Vision Rehabilitation Services in Rural Kenya: Challenges and Opportunities." African Vision and Eye Health, 78(1), a459.','url'=>null],
                    ],
                    'awards' => ['Vision 2020 East Africa Eye Health Champion Award 2022','KAFU Community Service Award 2020'],
                ],
            ],
            [
                'slug'        => 'dr-michael-otieno',
                'school_code' => 'SHS',
                'title'       => 'Dr. Michael Otieno',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Michael',
                    'middle_name' => null,
                    'last_name'   => 'Otieno',
                    'designation' => 'Senior Lecturer',
                    'department'  => 'Optometry',
                    'unit'        => null,
                    'email'       => 'm.otieno@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Michael Otieno is a Senior Lecturer in Optometry at the School of Health Sciences. His clinical research focuses on refractive error epidemiology in rural Western Kenya, anterior segment eye disease, and the pharmacological management of glaucoma and uveitis.',
                    'specializations' => ['Ocular Pharmacology', 'Contact Lenses', 'Refractive Error Management'],
                    'qualifications'  => [
                        ['year'=>'2018','qualification'=>'Doctor of Philosophy (Vision Science)','institution'=>'University of New South Wales, Australia'],
                        ['year'=>'2012','qualification'=>'Master of Optometry (Clinical)','institution'=>'University of Nairobi'],
                        ['year'=>'2008','qualification'=>'Bachelor of Science (Optometry)','institution'=>'University of Nairobi'],
                    ],
                    'experience' => [
                        ['start'=>'2018','end'=>'Present','position'=>'Senior Lecturer','institution'=>'SHS, KAFU'],
                        ['start'=>'2018','end'=>'2018','position'=>'Postdoctoral Clinical Fellow','institution'=>'Centre for Eye Health, Sydney'],
                        ['start'=>'2012','end'=>'2015','position'=>'Lecturer','institution'=>'SHS, KAFU'],
                    ],
                    'research_interests' => ['Refractive error epidemiology','Glaucoma pharmacotherapy','Anterior segment diseases','Contact lens applications'],
                    'teaching_areas'     => ['Clinical Optometry','Ocular Pharmacology','Contact Lens Fitting','Binocular Vision'],
                    'memberships'        => ['Optometrists Association Kenya (OAK)'],
                    'publications' => [
                        ['citation'=>'Otieno, M. & Awino, W. (2020). "Prevalence and Causes of Visual Impairment in School Children in Vihiga County." African Vision and Eye Health, 79(1), a555.','url'=>null],
                    ],
                    'awards' => [],
                ],
            ],
            [
                'slug'        => 'ms-agnes-kerubo',
                'school_code' => 'SHS',
                'title'       => 'Ms. Agnes Kerubo',
                'structured_data' => [
                    'prefix'      => 'Ms.',
                    'first_name'  => 'Agnes',
                    'middle_name' => null,
                    'last_name'   => 'Kerubo',
                    'designation' => 'Lecturer',
                    'department'  => 'Nursing',
                    'unit'        => null,
                    'email'       => 'a.kerubo@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Ms. Kerubo is a Registered Nurse and Midwife who coordinates the Bachelor of Science in Nursing programme. Her work focuses on maternal health outcomes and skilled birth attendance in rural health facilities.',
                    'specializations' => ['Midwifery', 'Community Health Nursing', 'Maternal and Child Health'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
            [
                'slug'        => 'dr-patrick-wabwire',
                'school_code' => 'SHS',
                'title'       => 'Dr. Patrick Wabwire',
                'structured_data' => [
                    'prefix'      => 'Dr.',
                    'first_name'  => 'Patrick',
                    'middle_name' => null,
                    'last_name'   => 'Wabwire',
                    'designation' => 'Lecturer',
                    'department'  => 'Clinical Medicine',
                    'unit'        => null,
                    'email'       => 'p.wabwire@kafu.ac.ke',
                    'photo'       => null,
                    'biography'   => 'Dr. Wabwire is a Clinical Officer and academic lecturer in Clinical Medicine. He supervises student clinical rotations and conducts research on tropical disease burden and primary health care delivery in Western Kenya.',
                    'specializations' => ['Internal Medicine', 'Tropical Diseases', 'Primary Health Care'],
                    'qualifications'  => [],
                    'experience'      => [],
                    'research_interests' => [],
                    'teaching_areas'     => [],
                    'memberships'        => [],
                    'publications' => [],
                    'awards'       => [],
                ],
            ],
        ];

        foreach ($staff as $s) {
            $upsert([
                'type'        => 'staff_profile',
                'slug'        => $s['slug'],
                'school_code' => $s['school_code'],
                'title'       => $s['title'],
                'body'        => $s['structured_data']['biography'] ?? '',
                'structured_data' => $s['structured_data'],
            ]);
        }

        // ─────────────────────────────────────────────────────────────
        // SITE SETTINGS — Contact
        // ─────────────────────────────────────────────────────────────
        $upsert([
            'type'  => 'page',
            'slug'  => 'contact',
            'title' => 'Contact Information',
            'body'    => '',
            'structured_data' => [
                'institution'  => 'Kaimosi Friends University',
                'abbreviation' => 'KAFU',
                'address'      => 'P.O BOX 385 – 50309, Kaimosi, Kenya',
                'phone'        => '+254 777 373 633',
                'emails' => [
                    ['label' => 'Vice Chancellor', 'address' => 'vc@kafu.ac.ke'],
                    ['label' => 'General Enquiries', 'address' => 'info@kafu.ac.ke'],
                ],
                'website' => 'https://kafu.ac.ke',
                'portals' => [
                    ['name' => 'Student Portal', 'url' => 'https://portal.kafu.ac.ke'],
                    ['name' => 'E-Learning (ODL)', 'url' => 'https://elearning.kafu.ac.ke'],
                ],
                'social_media' => [
                    ['platform' => 'Facebook', 'url' => 'https://www.facebook.com/KaimosiUniversity'],
                    ['platform' => 'Twitter', 'url' => 'https://twitter.com/KaimosiUni'],
                    ['platform' => 'YouTube', 'url' => 'https://www.youtube.com/@kaimosifrienduniversity'],
                ],
            ],
        ]);

        // ─────────────────────────────────────────────────────────────
        // SITE SETTINGS — Stats
        // ─────────────────────────────────────────────────────────────
        $upsert([
            'type'  => 'page',
            'slug'  => 'stats',
            'title' => 'University Stats',
            'body'    => '',
            'structured_data' => [
                ['label' => 'Schools',             'value' => 5],
                ['label' => 'Academic Programmes', 'value' => 38],
                ['label' => 'Years of Excellence', 'value' => 11],
                ['label' => 'Counties Reached',    'value' => 47],
            ],
        ]);

        // ─────────────────────────────────────────────────────────────
        // SITE SETTINGS — Admissions
        // ─────────────────────────────────────────────────────────────
        $upsert([
            'type'  => 'page',
            'slug'  => 'admissions',
            'title' => 'Admissions',
            'body'    => '',
            'structured_data' => [
                'pathways' => [
                    [
                        'id'          => 'undergraduate',
                        'title'       => 'Undergraduate',
                        'subtitle'    => 'Government Sponsored (KUCCPS) & Direct Entry',
                        'description' => 'Join one of KAFU\'s 22 undergraduate degree programmes via KUCCPS government placement or direct entry. Applications open each academic year.',
                        'requirements' => [
                            'Minimum KCSE mean grade of C+ (Plus) or its equivalent',
                            'Specific subject cluster requirements depending on the programme',
                            'Valid Kenya National Examinations Council (KNEC) certificate',
                            'National Identity Card or Birth Certificate',
                            'Two passport-size photographs',
                        ],
                        'steps' => [
                            ['step'=>1,'title'=>'Check Requirements','description'=>'Review the minimum entry requirements for your chosen programme.'],
                            ['step'=>2,'title'=>'Apply via KUCCPS','description'=>'Select Kaimosi Friends University on the KUCCPS portal during the application window.'],
                            ['step'=>3,'title'=>'Await Placement','description'=>'KUCCPS will notify you of your placement via SMS and the KUCCPS portal.'],
                            ['step'=>4,'title'=>'Accept Placement','description'=>'Log in to the KUCCPS portal and accept your placement to KAFU.'],
                            ['step'=>5,'title'=>'Report to KAFU','description'=>'Bring original documents, pay fees, and report on the stipulated joining date.'],
                        ],
                        'cta_label'    => 'Apply via KUCCPS',
                        'cta_url'      => 'https://students.kuccps.net/',
                        'cta_external' => true,
                    ],
                    [
                        'id'          => 'postgraduate',
                        'title'       => 'Postgraduate',
                        'subtitle'    => 'Masters & Doctoral Programmes',
                        'description' => 'Advance your professional or academic career through KAFU\'s research-based and coursework Masters and PhD programmes across all five schools.',
                        'requirements' => [
                            'For Masters: A relevant Bachelor\'s degree (Second Class Honours or above) from a recognized university',
                            'For PhD: A relevant Master\'s degree from a recognized university',
                            'Official transcripts and certificates from all previous institutions',
                            'Two academic referees\' letters of recommendation',
                            'A research proposal (for research-based programmes)',
                            'Curriculum Vitae (CV)',
                        ],
                        'steps' => [
                            ['step'=>1,'title'=>'Choose Your Programme','description'=>'Browse the postgraduate catalogue and identify a programme aligned to your goals.'],
                            ['step'=>2,'title'=>'Prepare Documents','description'=>'Gather official transcripts, certificates, CV, and reference letters.'],
                            ['step'=>3,'title'=>'Submit Application','description'=>'Apply directly through the KAFU Student Portal with all required documents.'],
                            ['step'=>4,'title'=>'Shortlisting & Interview','description'=>'Shortlisted candidates may be called for an interview or additional review.'],
                            ['step'=>5,'title'=>'Offer & Enrolment','description'=>'Upon acceptance, receive your admission letter and complete registration.'],
                        ],
                        'cta_label'    => 'Apply via Student Portal',
                        'cta_url'      => 'https://portal.kafu.ac.ke',
                        'cta_external' => true,
                    ],
                    [
                        'id'          => 'international',
                        'title'       => 'International Students',
                        'subtitle'    => 'Open to Students from All Nations',
                        'description' => 'KAFU warmly welcomes students from across Africa and the world. We provide guidance on recognition of foreign qualifications, student visas, and accommodation.',
                        'requirements' => [
                            'Recognized secondary school leaving certificate equivalent to KCSE C+',
                            'Certified copies of all academic certificates and transcripts',
                            'Valid passport (copy of bio-data page)',
                            'Student visa / study permit (upon admission)',
                            'Evidence of English language proficiency (where applicable)',
                            'Recognition of foreign qualifications from the Kenya National Qualifications Authority (KNQA)',
                        ],
                        'steps' => [
                            ['step'=>1,'title'=>'Equivalency Assessment','description'=>'Have your foreign qualifications recognized by KNQA or a recognized authority.'],
                            ['step'=>2,'title'=>'Submit Application','description'=>'Apply via the KAFU Student Portal with all certified documents.'],
                            ['step'=>3,'title'=>'Receive Offer Letter','description'=>'KAFU will issue a conditional or unconditional offer letter.'],
                            ['step'=>4,'title'=>'Apply for Student Visa','description'=>'Use your offer letter to apply for a Kenya student visa / study permit.'],
                            ['step'=>5,'title'=>'Arrive & Register','description'=>'Report to KAFU, present original documents, pay fees, and complete registration.'],
                        ],
                        'cta_label'    => 'Apply via Student Portal',
                        'cta_url'      => 'https://portal.kafu.ac.ke',
                        'cta_external' => true,
                    ],
                    [
                        'id'          => 'self-sponsored',
                        'title'       => 'Self-Sponsored',
                        'subtitle'    => 'Module II Programmes',
                        'description' => 'KAFU\'s Module II (self-sponsored) pathway is designed for working professionals, school leavers who missed government placement, and those seeking flexible learning arrangements.',
                        'requirements' => [
                            'Minimum KCSE mean grade of C+ for degree programmes',
                            'Minimum KCSE mean grade of C- for diploma programmes',
                            'KAFU application form (available on the portal)',
                            'Certified copies of academic certificates',
                            'National ID or passport copy',
                            'Two passport-size photos',
                        ],
                        'steps' => [
                            ['step'=>1,'title'=>'Download Application Form','description'=>'Download the Module II application form from the KAFU portal or admissions office.'],
                            ['step'=>2,'title'=>'Complete the Form','description'=>'Fill in all sections and attach certified copies of required documents.'],
                            ['step'=>3,'title'=>'Submit & Pay Application Fee','description'=>'Submit your form and pay the non-refundable application fee at the Finance Office or via M-Pesa.'],
                            ['step'=>4,'title'=>'Interview / Review','description'=>'Some programmes require a review panel or interview before admission.'],
                            ['step'=>5,'title'=>'Receive Admission Letter','description'=>'Collect or download your admission letter and report on the joining date.'],
                        ],
                        'cta_label'    => 'Apply via Student Portal',
                        'cta_url'      => 'https://portal.kafu.ac.ke',
                        'cta_external' => true,
                    ],
                ],
                'deadlines' => [
                    ['event'=>'KUCCPS Application Window','date'=>'2026-05-30','description'=>'Deadline for selecting KAFU on the KUCCPS portal'],
                    ['event'=>'Module II Applications Close','date'=>'2026-06-15','description'=>'Self-sponsored undergraduate and diploma applications'],
                    ['event'=>'Postgraduate Intake','date'=>'2026-06-30','description'=>'Masters and PhD applications for September 2026 intake'],
                    ['event'=>'International Applications Close','date'=>'2026-07-31','description'=>'All international student applications for September intake'],
                    ['event'=>'Reporting / Orientation','date'=>'2026-09-08','description'=>'First-year student reporting and orientation week begins'],
                ],
                'documents' => [
                    ['id'=>1,'title'=>'Undergraduate Application Form','category'=>'Application Forms','description'=>'Official direct-entry undergraduate application form','file_url'=>'#','version'=>'2026'],
                    ['id'=>2,'title'=>'Postgraduate Application Form','category'=>'Application Forms','description'=>'Application form for Masters and PhD programmes','file_url'=>'#','version'=>'2026'],
                    ['id'=>3,'title'=>'Module II Application Form','category'=>'Application Forms','description'=>'Self-sponsored programme application form','file_url'=>'#','version'=>'2026'],
                    ['id'=>4,'title'=>'Government-Sponsored Fee Structure 2025/2026','category'=>'Fee Structures','description'=>'Fee schedules for KUCCPS-placed students per school','file_url'=>'#','version'=>'2025/2026'],
                    ['id'=>5,'title'=>'Self-Sponsored Fee Structure 2025/2026','category'=>'Fee Structures','description'=>'Fee schedules for Module II and private students','file_url'=>'#','version'=>'2025/2026'],
                    ['id'=>6,'title'=>'Postgraduate Fee Structure 2025/2026','category'=>'Fee Structures','description'=>'Fee schedules for all Masters and PhD programmes','file_url'=>'#','version'=>'2025/2026'],
                    ['id'=>7,'title'=>'Joining Instructions 2025/2026','category'=>'Joining Instructions','description'=>'Official joining instructions and what to bring on reporting day','file_url'=>'#','version'=>'2025/2026'],
                    ['id'=>8,'title'=>'KAFU Prospectus 2025/2026','category'=>'Brochures','description'=>'Full university prospectus including all programmes and fees','file_url'=>'#','version'=>'2025/2026'],
                ],
                'contact' => [
                    'office'   => 'Admissions & Student Recruitment Office',
                    'email'    => 'admissions@kafu.ac.ke',
                    'phone'    => '+254 777 373 633',
                    'location' => 'Administration Block, Ground Floor, Main Campus, Kaimosi',
                    'hours'    => 'Monday – Friday, 8:00 AM – 5:00 PM',
                ],
            ],
        ]);

        // ─────────────────────────────────────────────────────────────
        // SITE SETTINGS — Homepage
        // ─────────────────────────────────────────────────────────────
        $upsert([
            'type'  => 'page',
            'slug'  => 'homepage',
            'title' => 'Homepage Content',
            'body'    => '',
            'structured_data' => [
                'hero' => [
                    'headline'    => 'Transforming Lives Through Knowledge',
                    'subheadline' => 'A Quaker-founded public university in the heart of Western Kenya, KAFU inspires innovation, integrity, and service to humanity.',
                    'cta_primary_label'   => 'Explore Programmes',
                    'cta_primary_url'     => '/programmes',
                    'cta_secondary_label' => 'Apply Now',
                    'cta_secondary_url'   => '/admissions',
                ],
                'about' => [
                    'heading'     => 'About Kaimosi Friends University',
                    'body'        => 'Kaimosi Friends University (KAFU) is a public university established by the Friends Church in Kenya, rooted in Quaker values of integrity, community, and service. Located in Kaimosi, Vihiga County, KAFU has grown into a centre of academic excellence offering programmes across five schools — education, business, computing, science, and health sciences. Our mission is to produce graduates who are not just job seekers but job creators, equipped to transform communities and contribute to Kenya\'s development agenda.',
                    'cta_label'   => 'Learn More About KAFU',
                    'cta_url'     => '/about',
                ],
                'why_kafu' => [
                    'heading' => 'Why Choose KAFU?',
                    'cards'   => [
                        ['title'=>'Quaker Heritage','description'=>'Rooted in over a century of Friends values — integrity, simplicity, community, and service — KAFU nurtures principled graduates.'],
                        ['title'=>'Research Excellence','description'=>'Our faculty pursue cutting-edge research from molecular biology to AI, with partnerships across Africa and beyond.'],
                        ['title'=>'Career-Ready Graduates','description'=>'Our curricula are designed in consultation with industry to produce graduates ready to lead, innovate, and create jobs.'],
                        ['title'=>'Inclusive Community','description'=>'KAFU welcomes students from all backgrounds, with bursary support, disability services, and a vibrant student life.'],
                    ],
                ],
            ],
        ]);

        $this->command->info('Content migration complete: schools, programmes, staff, and site settings seeded.');
    }
}
