<?php

namespace Database\Seeders;

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $departments = [
            // ── SESS ─────────────────────────────────────────────────────────
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Arts & Social Sciences Education',
                'slug'            => 'arts-social-sciences-education',
                'description'     => 'The Department of Arts & Social Sciences Education prepares highly competent teachers in humanities and social science subjects for secondary schools and tertiary institutions across Kenya. It offers both undergraduate and postgraduate programmes in education, equipping graduates with pedagogy, curriculum design, and assessment skills.',
                'vision'          => 'To be the leading department in teacher education and social sciences in East Africa.',
                'hod_name'        => 'Dr. Simiyu Wafula',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 's.wafula@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 201',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/IMG_8696.jpg',
                'hod_bio'         => 'Dr. Simiyu Wafula holds a PhD in Curriculum Studies from the University of Nairobi. With over 18 years of teaching and research experience, his scholarship focuses on teacher professional development, curriculum reform, and educational policy in Sub-Saharan Africa.',
                'office_location' => 'Humanities Block, Room 104, KAFU Main Campus',
                'email'           => 'dept.asse@kafu.ac.ke',
                'phone'           => '+254 700 100 200',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Science & Technical Education',
                'slug'            => 'science-technical-education',
                'description'     => 'The Department of Science & Technical Education trains teachers in science, mathematics, and technical subjects. It bridges the gap between theoretical knowledge and practical classroom delivery, producing graduates who are equipped to inspire the next generation of scientists and engineers in Kenyan secondary schools.',
                'vision'          => 'To produce excellent science and technical educators who drive innovation in Kenya.',
                'hod_name'        => 'Dr. Grace Nafula Barasa',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'g.barasa@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 211',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/PIC1.jpg',
                'hod_bio'         => 'Dr. Grace Nafula Barasa earned her PhD in Science Education from Moi University. She is a specialist in inquiry-based learning, STEM integration, and teacher effectiveness research. Dr. Barasa has published widely in peer-reviewed journals and has been involved in national curriculum review panels.',
                'office_location' => 'Science Education Building, Room 207, KAFU Main Campus',
                'email'           => 'dept.ste@kafu.ac.ke',
                'phone'           => '+254 700 100 210',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Social Work & Community Development',
                'slug'            => 'social-work-community-development',
                'description'     => 'The Department of Social Work & Community Development equips students with skills to address the complex social, economic, and psychological needs of individuals, families, and communities. Graduates serve in NGOs, government agencies, healthcare institutions, and community-based organisations across Kenya and the region.',
                'hod_name'        => 'Dr. Peter Onyango Ochieng',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'p.ochieng@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 221',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2026/03/IMG_6424-scaled.jpg',
                'hod_bio'         => 'Dr. Peter Onyango Ochieng holds a PhD in Social Work from the University of Pretoria. His research interests span community resilience, child welfare policy, and social protection systems in East Africa. He has consulted for UNICEF, the World Bank, and the Kenyan Government on social welfare programmes.',
                'office_location' => 'Humanities Block, Room 115, KAFU Main Campus',
                'email'           => 'dept.swcd@kafu.ac.ke',
                'phone'           => '+254 700 100 220',
                'sort_order'      => 3,
            ],
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Criminology, Security & Peace Studies',
                'slug'            => 'criminology-security-peace-studies',
                'description'     => 'The Department of Criminology, Security & Peace Studies offers interdisciplinary education in crime prevention, security management, conflict resolution, and peacebuilding. It prepares graduates for careers in law enforcement, correctional services, security consultancy, and humanitarian organisations.',
                'hod_name'        => 'Dr. Alice Kemunto Nyamweya',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'a.nyamweya@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 231',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Vice-Chancellor-Prof.-Peter-Mwita-addresses-fourth-year-teacher-trainees-during-the-opening-of-the-Competency-Based-Education-CBE-training-at-Kaimosi-Friends-University.jpg',
                'hod_bio'         => 'Dr. Alice Kemunto Nyamweya is a distinguished scholar in criminology and peace studies. She holds a PhD from the University of Edinburgh and has researched terrorism, gender-based violence, and transitional justice in conflict-affected communities. She serves on the advisory board of several national security think-tanks.',
                'office_location' => 'Social Sciences Block, Room 118, KAFU Main Campus',
                'email'           => 'dept.csps@kafu.ac.ke',
                'phone'           => '+254 700 100 230',
                'sort_order'      => 4,
            ],

            // ── SBE ──────────────────────────────────────────────────────────
            [
                'school_code'     => 'SBE',
                'name'            => 'Department of Business Administration & Management',
                'slug'            => 'business-administration-management',
                'description'     => 'The Department of Business Administration & Management offers comprehensive programmes that develop analytical, strategic, and leadership capabilities in business students. The department engages industry partners extensively to ensure graduates are job-ready, ethically grounded, and equipped to lead organisations of all sizes.',
                'vision'          => 'To produce globally competitive business leaders rooted in ethical practice.',
                'hod_name'        => 'Dr. James Mburu Kamau',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'j.kamau@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 301',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/PIC1.jpg',
                'hod_bio'         => 'Dr. James Mburu Kamau holds a PhD in Strategic Management from Strathmore University. His research focuses on corporate governance, SME sustainability, and digital transformation in Kenyan businesses. He is a member of the Kenya Institute of Management and has served on several corporate boards.',
                'office_location' => 'Business Block, Room 201, KAFU Main Campus',
                'email'           => 'dept.bam@kafu.ac.ke',
                'phone'           => '+254 700 100 300',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SBE',
                'name'            => 'Department of Accounting & Finance',
                'slug'            => 'accounting-finance',
                'description'     => 'The Department of Accounting & Finance prepares students for professional careers in financial management, auditing, taxation, and investment. The department is aligned with CPA(K) and ACCA professional standards, and its graduates are sought after in banking, public finance, and corporate accounting.',
                'hod_name'        => 'Dr. Esther Chebet Rotich',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'e.rotich@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 311',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/IMG_8696.jpg',
                'hod_bio'         => 'Dr. Esther Chebet Rotich is a CPA(K) and holds a PhD in Financial Economics from the University of Cape Town. Her research centres on public sector financial management, financial inclusion, and microfinance in rural Kenya. She has been a consultant for the National Treasury and several county governments.',
                'office_location' => 'Business Block, Room 215, KAFU Main Campus',
                'email'           => 'dept.af@kafu.ac.ke',
                'phone'           => '+254 700 100 310',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SBE',
                'name'            => 'Department of Economics',
                'slug'            => 'economics',
                'description'     => 'The Department of Economics provides rigorous training in micro and macroeconomic theory, econometrics, development economics, and policy analysis. Graduates are employed in government ministries, international financial institutions, research organisations, and the private sector.',
                'hod_name'        => 'Dr. Samuel Kipkemoi Bett',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 's.bett@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 321',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2026/03/IMG_6424-scaled.jpg',
                'hod_bio'         => 'Dr. Samuel Kipkemoi Bett holds a PhD in Development Economics from the University of Dar es Salaam. His research focuses on agricultural value chains, trade policy, and economic growth in East Africa. He has advised the Kenya Revenue Authority and COMESA Secretariat on economic policy matters.',
                'office_location' => 'Business Block, Room 225, KAFU Main Campus',
                'email'           => 'dept.econ@kafu.ac.ke',
                'phone'           => '+254 700 100 320',
                'sort_order'      => 3,
            ],

            // ── SCIT ─────────────────────────────────────────────────────────
            [
                'school_code'     => 'SCIT',
                'name'            => 'Department of Computer Science',
                'slug'            => 'computer-science',
                'description'     => 'The Department of Computer Science offers theoretically rigorous and practically grounded programmes in algorithms, software systems, artificial intelligence, data science, and computer networks. It is equipped with modern computing labs and is home to KAFU\'s Cyber Security Research Centre.',
                'vision'          => 'To be a centre of excellence in computing education and research in East Africa.',
                'hod_name'        => 'Dr. Lilian Ronoh',
                'hod_title'       => 'Chair, Computer Science Department',
                'hod_email'       => 'l.ronoh@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 401',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Dr.-Lilian-Ronoh-1-300x300.jpg',
                'hod_bio'         => 'Dr. Lilian Ronoh serves as Chair of the Department of Computer Science at Kaimosi Friends University\'s School of Computing and Information Technology. She is committed to academic excellence and equipping students with cutting-edge computing skills.',
                'office_location' => 'ICT Block, Room 101, KAFU Main Campus',
                'email'           => 'dept.cs@kafu.ac.ke',
                'phone'           => '+254 700 100 400',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SCIT',
                'name'            => 'Department of Information Technology',
                'slug'            => 'information-technology',
                'description'     => 'The Department of Information Technology trains students in systems administration, database management, networking, web technologies, and IT project management. Its graduates are in high demand across the banking, healthcare, telecommunications, and public sectors.',
                'hod_name'        => 'Mr. Shirandula',
                'hod_title'       => 'Chair of Department',
                'hod_email'       => 'shirandula@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 411',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2026/02/Mr._Shirandula_-COD-ITI-300x300.jpg',
                'hod_bio'         => 'Mr. Shirandula serves as the Chair of the Department of Information Technology and Informatics at Kaimosi Friends University. He is passionate about preparing students to meet the evolving demands of the global ICT industry.',
                'office_location' => 'ICT Block, Room 115, KAFU Main Campus',
                'email'           => 'dept.it@kafu.ac.ke',
                'phone'           => '+254 700 100 410',
                'sort_order'      => 2,
            ],

            // ── SOS ──────────────────────────────────────────────────────────
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Biological Sciences',
                'slug'            => 'biological-sciences',
                'description'     => 'The Department of Biological Sciences offers programmes in biology, botany, zoology, microbiology, and biochemistry. It is home to well-equipped molecular biology and ecology laboratories, supporting research in biodiversity, food security, and infectious diseases in Western Kenya.',
                'hod_name'        => 'Dr. Cleophas Wekesa Mulemi',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'c.mulemi@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 501',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/health.jpg',
                'hod_bio'         => 'Dr. Cleophas Wekesa Mulemi holds a PhD in Molecular Biology from Makerere University. His research spans malaria parasite genomics, plant-microbe interactions, and conservation biology in the Lake Victoria basin. He leads KAFU\'s Biodiversity Research Unit and has supervised over 20 postgraduate students.',
                'office_location' => 'Science Block A, Room 102, KAFU Main Campus',
                'email'           => 'dept.biosciences@kafu.ac.ke',
                'phone'           => '+254 700 100 500',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Physical & Chemical Sciences',
                'slug'            => 'physical-chemical-sciences',
                'description'     => 'The Department of Physical & Chemical Sciences offers programmes combining rigorous theoretical foundations with hands-on laboratory experience in physics, chemistry, and related disciplines. Graduates pursue careers in industry, research, teaching, and environmental management.',
                'hod_name'        => 'Dr. Joyce Moraa Nyamache',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'j.nyamache@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 511',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/PIC1.jpg',
                'hod_bio'         => 'Dr. Joyce Moraa Nyamache holds a PhD in Physical Chemistry from the University of Cape Town. Her research focuses on electrochemistry, green chemistry, and water purification technologies applicable to rural Kenya. She is a Fellow of the Chemical Society of Kenya and a recipient of the African Union Kwame Nkrumah Scientific Award.',
                'office_location' => 'Science Block B, Room 204, KAFU Main Campus',
                'email'           => 'dept.pcs@kafu.ac.ke',
                'phone'           => '+254 700 100 510',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Mathematics & Statistics',
                'slug'            => 'mathematics-statistics',
                'description'     => 'The Department of Mathematics & Statistics is committed to excellence in pure and applied mathematics, probability, statistics, and actuarial science. Its graduates are employed in banking, insurance, data analytics, and academia, and are highly regarded for their analytical rigour.',
                'hod_name'        => 'Dr. Emmanuel Kiptoo Chirchir',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'e.chirchir@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 521',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2026/03/IMG_6424-scaled.jpg',
                'hod_bio'         => 'Dr. Emmanuel Kiptoo Chirchir holds a PhD in Applied Mathematics from the University of Pretoria. His research interests include numerical methods, stochastic processes, and mathematical modelling of epidemic systems. He has served as a statistical consultant for county health departments and regional development agencies.',
                'office_location' => 'Science Block A, Room 215, KAFU Main Campus',
                'email'           => 'dept.mathstat@kafu.ac.ke',
                'phone'           => '+254 700 100 520',
                'sort_order'      => 3,
            ],
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Agricultural Economics & Rural Development',
                'slug'            => 'agricultural-economics-rural-development',
                'description'     => 'The Department of Agricultural Economics & Rural Development trains students in farm management, agricultural policy, rural finance, value chain analysis, and food systems. The department runs an active research farm and partners with county governments and NGOs on food security initiatives in Western Kenya.',
                'hod_name'        => 'Dr. Faith Mumbua Mutuku',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'f.mutuku@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 531',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/IMG_8696.jpg',
                'hod_bio'         => 'Dr. Faith Mumbua Mutuku holds a PhD in Agricultural Economics from the University of Ghana. Her research centres on smallholder farmer livelihoods, climate-smart agriculture, and food market integration in East Africa. She has collaborated with the FAO, IFAD, and the Kenyan Ministry of Agriculture on food security projects.',
                'office_location' => 'Agricultural Sciences Block, Room 110, KAFU Main Campus',
                'email'           => 'dept.aerd@kafu.ac.ke',
                'phone'           => '+254 700 100 530',
                'sort_order'      => 4,
            ],

            // ── SHS ──────────────────────────────────────────────────────────
            [
                'school_code'     => 'SHS',
                'name'            => 'Department of Optometry & Vision Sciences',
                'slug'            => 'optometry-vision-sciences',
                'description'     => 'The Department of Optometry & Vision Sciences is one of only two departments in Kenya offering Optometry training to the PhD level. It provides clinical, research, and community outreach training, producing graduates equipped to address the significant burden of preventable blindness and visual impairment in Kenya and East Africa.',
                'vision'          => 'To be the premier centre for optometry education and eye care research in East Africa.',
                'hod_name'        => 'Dr. Dickson Otieno Owino',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'd.owino@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 601',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/health.jpg',
                'hod_bio'         => 'Dr. Dickson Otieno Owino holds a PhD in Ophthalmic Sciences from Cardiff University and is a registered Optometrist in Kenya. His research focuses on myopia prevalence, diabetic retinopathy, and low vision rehabilitation in Sub-Saharan Africa. He has published in leading vision science journals and has led community eye screening campaigns across Western Kenya.',
                'office_location' => 'Health Sciences Block, Room 101, KAFU Main Campus',
                'email'           => 'dept.optometry@kafu.ac.ke',
                'phone'           => '+254 700 100 600',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SHS',
                'name'            => 'Department of Public & Community Health',
                'slug'            => 'public-community-health',
                'description'     => 'The Department of Public & Community Health equips students with knowledge and skills to promote, protect, and improve population health. The department runs community health programmes in Vihiga and surrounding counties, and its graduates work in public health agencies, NGOs, and research institutions.',
                'hod_name'        => 'Dr. Caroline Atieno Akumu',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'c.akumu@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 611',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2025/10/posgraduate.jpg',
                'hod_bio'         => 'Dr. Caroline Atieno Akumu holds a PhD in Epidemiology from the London School of Hygiene and Tropical Medicine. She specialises in infectious disease epidemiology, maternal and child health, and health systems strengthening. Her research has informed national policy on immunisation, HIV prevention, and nutrition programmes in Kenya.',
                'office_location' => 'Health Sciences Block, Room 115, KAFU Main Campus',
                'email'           => 'dept.pubhealth@kafu.ac.ke',
                'phone'           => '+254 700 100 610',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SHS',
                'name'            => 'Department of Medical Laboratory Sciences',
                'slug'            => 'medical-laboratory-sciences',
                'description'     => 'The Department of Medical Laboratory Sciences trains students in clinical chemistry, haematology, microbiology, histopathology, and blood transfusion. The department operates a functional teaching laboratory and partners with Kaimosi Friends University College Hospital for clinical placements.',
                'hod_name'        => 'Dr. Vincent Wabwoba Khisa',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'v.khisa@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 621',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/PIC1.jpg',
                'hod_bio'         => 'Dr. Vincent Wabwoba Khisa holds a PhD in Clinical Microbiology from Jomo Kenyatta University of Agriculture and Technology (JKUAT). He is a registered Medical Laboratory Scientist and a Fellow of the Kenya Medical Laboratory Technicians and Technologists Board. His research focuses on antimicrobial resistance, tropical infectious diseases, and point-of-care diagnostics in resource-limited settings.',
                'office_location' => 'Health Sciences Block, Room 205, KAFU Main Campus',
                'email'           => 'dept.mls@kafu.ac.ke',
                'phone'           => '+254 700 100 620',
                'sort_order'      => 3,
            ],
        ];

        foreach ($departments as $dept) {
            Department::create($dept);
        }
    }
}
