<?php

namespace Database\Seeders;

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $departments = [
            // ── SESS ─────────────────────────────────────────────────────────
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Arts & Social Sciences Education',
                'slug'            => 'arts-social-sciences-education',
                'description'     => 'The Department of Arts & Social Sciences Education prepares highly competent teachers in humanities and social science subjects for secondary schools and tertiary institutions across Kenya. It offers both undergraduate and postgraduate programmes in education, equipping graduates with pedagogy, curriculum design, and assessment skills.',
                'vision'          => 'To be the leading department in teacher education and social sciences in East Africa.',
                'hod_name'        => 'Dr. Simiyu Wafula',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 's.wafula@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 201',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/IMG_8696.jpg',
                'hod_bio'         => 'Dr. Simiyu Wafula holds a PhD in Curriculum Studies from the University of Nairobi. With over 18 years of teaching and research experience, his scholarship focuses on teacher professional development, curriculum reform, and educational policy in Sub-Saharan Africa.',
                'office_location' => 'Humanities Block, Room 104, KAFU Main Campus',
                'email'           => 'dept.asse@kafu.ac.ke',
                'phone'           => '+254 700 100 200',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Science & Technical Education',
                'slug'            => 'science-technical-education',
                'description'     => 'The Department of Science & Technical Education trains teachers in science, mathematics, and technical subjects. It bridges the gap between theoretical knowledge and practical classroom delivery, producing graduates who are equipped to inspire the next generation of scientists and engineers in Kenyan secondary schools.',
                'vision'          => 'To produce excellent science and technical educators who drive innovation in Kenya.',
                'hod_name'        => 'Dr. Grace Nafula Barasa',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'g.barasa@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 211',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/PIC1.jpg',
                'hod_bio'         => 'Dr. Grace Nafula Barasa earned her PhD in Science Education from Moi University. She is a specialist in inquiry-based learning, STEM integration, and teacher effectiveness research. Dr. Barasa has published widely in peer-reviewed journals and has been involved in national curriculum review panels.',
                'office_location' => 'Science Education Building, Room 207, KAFU Main Campus',
                'email'           => 'dept.ste@kafu.ac.ke',
                'phone'           => '+254 700 100 210',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Social Work & Community Development',
                'slug'            => 'social-work-community-development',
                'description'     => 'The Department of Social Work & Community Development equips students with skills to address the complex social, economic, and psychological needs of individuals, families, and communities. Graduates serve in NGOs, government agencies, healthcare institutions, and community-based organisations across Kenya and the region.',
                'hod_name'        => 'Dr. Peter Onyango Ochieng',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'p.ochieng@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 221',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2026/03/IMG_6424-scaled.jpg',
                'hod_bio'         => 'Dr. Peter Onyango Ochieng holds a PhD in Social Work from the University of Pretoria. His research interests span community resilience, child welfare policy, and social protection systems in East Africa. He has consulted for UNICEF, the World Bank, and the Kenyan Government on social welfare programmes.',
                'office_location' => 'Humanities Block, Room 115, KAFU Main Campus',
                'email'           => 'dept.swcd@kafu.ac.ke',
                'phone'           => '+254 700 100 220',
                'sort_order'      => 3,
            ],
            [
                'school_code'     => 'SESS',
                'name'            => 'Department of Criminology, Security & Peace Studies',
                'slug'            => 'criminology-security-peace-studies',
                'description'     => 'The Department of Criminology, Security & Peace Studies offers interdisciplinary education in crime prevention, security management, conflict resolution, and peacebuilding. It prepares graduates for careers in law enforcement, correctional services, security consultancy, and humanitarian organisations.',
                'hod_name'        => 'Dr. Alice Kemunto Nyamweya',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'a.nyamweya@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 231',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Vice-Chancellor-Prof.-Peter-Mwita-addresses-fourth-year-teacher-trainees-during-the-opening-of-the-Competency-Based-Education-CBE-training-at-Kaimosi-Friends-University.jpg',
                'hod_bio'         => 'Dr. Alice Kemunto Nyamweya is a distinguished scholar in criminology and peace studies. She holds a PhD from the University of Edinburgh and has researched terrorism, gender-based violence, and transitional justice in conflict-affected communities. She serves on the advisory board of several national security think-tanks.',
                'office_location' => 'Social Sciences Block, Room 118, KAFU Main Campus',
                'email'           => 'dept.csps@kafu.ac.ke',
                'phone'           => '+254 700 100 230',
                'sort_order'      => 4,
            ],

            // ── SBE ──────────────────────────────────────────────────────────
            [
                'school_code'     => 'SBE',
                'name'            => 'Department of Business Administration & Management',
                'slug'            => 'business-administration-management',
                'description'     => 'The Department of Business Administration & Management offers comprehensive programmes that develop analytical, strategic, and leadership capabilities in business students. The department engages industry partners extensively to ensure graduates are job-ready, ethically grounded, and equipped to lead organisations of all sizes.',
                'vision'          => 'To produce globally competitive business leaders rooted in ethical practice.',
                'hod_name'        => 'Mr. Obed Tanda Monayo',
                'hod_title'       => 'Chair, Business Administration & Management Sciences',
                'hod_email'       => 'o.monayo@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 301',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2025/10/Obed-Tanda-COD-BAMs-300x300.jpg',
                'hod_bio'         => 'Mr. Obed Tanda Monayo chairs the Department of Business Administration and Management Sciences at Kaimosi Friends University. He is committed to equipping students with leadership, entrepreneurship, and management skills for a competitive global environment.',
                'office_location' => 'Business Block, Room 201, KAFU Main Campus',
                'email'           => 'dept.bam@kafu.ac.ke',
                'phone'           => '+254 700 100 300',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SBE',
                'name'            => 'Department of Accounting & Finance',
                'slug'            => 'accounting-finance',
                'description'     => 'The Department of Accounting & Finance prepares students for professional careers in financial management, auditing, taxation, and investment. The department is aligned with CPA(K) and ACCA professional standards, and its graduates are sought after in banking, public finance, and corporate accounting.',
                'hod_name'        => 'Dr. Robert Opanyi',
                'hod_title'       => 'Chair, Department of Accounting, Finance & Economics',
                'hod_email'       => 'r.opanyi@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 311',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2025/10/Opanyi-COD-Accounting-300x300.jpg',
                'hod_bio'         => 'Dr. Robert Opanyi chairs the Department of Accounting, Finance and Economics at Kaimosi Friends University. He leads a team dedicated to producing transformative leaders and ethically grounded professionals capable of navigating the global financial landscape.',
                'office_location' => 'Business Block, Room 215, KAFU Main Campus',
                'email'           => 'dept.af@kafu.ac.ke',
                'phone'           => '+254 700 100 310',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SBE',
                'name'            => 'Department of Economics',
                'slug'            => 'economics',
                'description'     => 'The Department of Economics provides rigorous training in micro and macroeconomic theory, econometrics, development economics, and policy analysis. Graduates are employed in government ministries, international financial institutions, research organisations, and the private sector.',
                'hod_name'        => 'Dr. Mackton',
                'hod_title'       => 'Chair, Department of Economics',
                'hod_email'       => 'hod.economics@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 321',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2025/10/Dr.-Mackton-COD-Economics-300x300.jpg',
                'hod_bio'         => 'Dr. Mackton chairs the Department of Economics at the School of Business and Economics, Kaimosi Friends University.',
                'office_location' => 'Business Block, Room 225, KAFU Main Campus',
                'email'           => 'dept.econ@kafu.ac.ke',
                'phone'           => '+254 700 100 320',
                'sort_order'      => 3,
            ],

            // ── SCIT ─────────────────────────────────────────────────────────
            [
                'school_code'     => 'SCIT',
                'name'            => 'Department of Computer Science',
                'slug'            => 'computer-science',
                'description'     => 'The Department of Computer Science offers theoretically rigorous and practically grounded programmes in algorithms, software systems, artificial intelligence, data science, and computer networks. It is equipped with modern computing labs and is home to KAFU\'s Cyber Security Research Centre.',
                'vision'          => 'To be a centre of excellence in computing education and research in East Africa.',
                'hod_name'        => 'Dr. Lilian Ronoh',
                'hod_title'       => 'Chair, Computer Science Department',
                'hod_email'       => 'l.ronoh@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 401',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Dr.-Lilian-Ronoh-1-300x300.jpg',
                'hod_bio'         => 'Dr. Lilian Ronoh serves as Chair of the Department of Computer Science at Kaimosi Friends University\'s School of Computing and Information Technology. She is committed to academic excellence and equipping students with cutting-edge computing skills.',
                'office_location' => 'ICT Block, Room 101, KAFU Main Campus',
                'email'           => 'dept.cs@kafu.ac.ke',
                'phone'           => '+254 700 100 400',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SCIT',
                'name'            => 'Department of Information Technology',
                'slug'            => 'information-technology',
                'description'     => 'The Department of Information Technology trains students in systems administration, database management, networking, web technologies, and IT project management. Its graduates are in high demand across the banking, healthcare, telecommunications, and public sectors.',
                'hod_name'        => 'Dr. Ayub H. Shirandula',
                'hod_title'       => 'Chair, Information Technology & Informatics',
                'hod_email'       => 'a.shirandula@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 411',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2026/02/Mr._Shirandula_-COD-ITI-300x300.jpg',
                'hod_bio'         => 'Dr. Ayub H. Shirandula serves as Chair of the Department of Information Technology and Informatics at Kaimosi Friends University. He is passionate about preparing students to meet the evolving demands of the global ICT industry.',
                'office_location' => 'ICT Block, Room 115, KAFU Main Campus',
                'email'           => 'dept.it@kafu.ac.ke',
                'phone'           => '+254 700 100 410',
                'sort_order'      => 2,
            ],

            // ── SOS ──────────────────────────────────────────────────────────
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Biological Sciences',
                'slug'            => 'biological-sciences',
                'description'     => 'The Department of Biological Sciences offers programmes in biology, botany, zoology, microbiology, and biochemistry. It is home to well-equipped molecular biology and ecology laboratories, supporting research in biodiversity, food security, and infectious diseases in Western Kenya.',
                'hod_name'        => 'Dr. Loice Mureithi',
                'hod_title'       => 'Chair, Department of Biological Sciences',
                'hod_email'       => 'l.mureithi@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 501',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/2025/10/Dr.-Loice-COD-Biology-300x300.jpg',
                'hod_bio'         => 'Dr. Loice Mureithi chairs the Department of Biological Sciences at the School of Science, Kaimosi Friends University. She is committed to excellence in biological education and research.',
                'office_location' => 'Science Block A, Room 102, KAFU Main Campus',
                'email'           => 'dept.biosciences@kafu.ac.ke',
                'phone'           => '+254 700 100 500',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Physical & Chemical Sciences',
                'slug'            => 'physical-chemical-sciences',
                'description'     => 'The Department of Physical & Chemical Sciences offers programmes combining rigorous theoretical foundations with hands-on laboratory experience in physics, chemistry, and related disciplines. Graduates pursue careers in industry, research, teaching, and environmental management.',
                'hod_name'        => 'Dr. Felix Saouma',
                'hod_title'       => 'Chair, Department of Physical & Chemical Sciences',
                'hod_email'       => 'f.saouma@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 511',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/image-3-300x300.jpg',
                'hod_bio'         => 'Dr. Felix Saouma chairs the Department of Physical & Chemical Sciences at the School of Science, Kaimosi Friends University.',
                'office_location' => 'Science Block B, Room 204, KAFU Main Campus',
                'email'           => 'dept.pcs@kafu.ac.ke',
                'phone'           => '+254 700 100 510',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Mathematics & Statistics',
                'slug'            => 'mathematics-statistics',
                'description'     => 'The Department of Mathematics & Statistics is committed to excellence in pure and applied mathematics, probability, statistics, and actuarial science. Its graduates are employed in banking, insurance, data analytics, and academia, and are highly regarded for their analytical rigour.',
                'hod_name'        => 'Dr. Samuel B. Apima',
                'hod_title'       => 'Chair, Department of Mathematics Sciences',
                'hod_email'       => 's.apima@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 521',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Dr.-Apima-300x300.jpg',
                'hod_bio'         => 'Dr. Samuel B. Apima chairs the Department of Mathematics Sciences at Kaimosi Friends University School of Science. The department provides exceptional opportunities for study and research in Mathematics at undergraduate and postgraduate levels, servicing all other schools in the university.',
                'office_location' => 'Science Block A, Room 215, KAFU Main Campus',
                'email'           => 'dept.mathstat@kafu.ac.ke',
                'phone'           => '+254 700 100 520',
                'sort_order'      => 3,
            ],
            [
                'school_code'     => 'SOS',
                'name'            => 'Department of Agricultural Economics & Rural Development',
                'slug'            => 'agricultural-economics-rural-development',
                'description'     => 'The Department of Agricultural Economics & Rural Development trains students in farm management, agricultural policy, rural finance, value chain analysis, and food systems. The department runs an active research farm and partners with county governments and NGOs on food security initiatives in Western Kenya.',
                'hod_name'        => 'Dr. Faith Mumbua Mutuku',
                'hod_title'       => 'Head of Department',
                'hod_email'       => 'f.mutuku@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 531',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/IMG_8696.jpg',
                'hod_bio'         => 'Dr. Faith Mumbua Mutuku holds a PhD in Agricultural Economics from the University of Ghana. Her research centres on smallholder farmer livelihoods, climate-smart agriculture, and food market integration in East Africa. She has collaborated with the FAO, IFAD, and the Kenyan Ministry of Agriculture on food security projects.',
                'office_location' => 'Agricultural Sciences Block, Room 110, KAFU Main Campus',
                'email'           => 'dept.aerd@kafu.ac.ke',
                'phone'           => '+254 700 100 530',
                'sort_order'      => 4,
            ],

            // ── SHS ──────────────────────────────────────────────────────────
            [
                'school_code'     => 'SHS',
                'name'            => 'Department of Optometry & Vision Sciences',
                'slug'            => 'optometry-vision-sciences',
                'description'     => 'The Department of Optometry & Vision Sciences is one of only two departments in Kenya offering Optometry training to the PhD level. It provides clinical, research, and community outreach training, producing graduates equipped to address the significant burden of preventable blindness and visual impairment in Kenya and East Africa.',
                'vision'          => 'To be the premier centre for optometry education and eye care research in East Africa.',
                'hod_name'        => 'Dr. Cyprian Mabonga',
                'hod_title'       => 'Dean, School of Health Sciences',
                'hod_email'       => 'c.mabonga@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 601',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Dr.-Mabonga-300x300.jpg',
                'hod_bio'         => 'Dr. Cyprian Mabonga is the Dean of the School of Health Sciences at Kaimosi Friends University. He leads one of only two institutions in Kenya offering Optometry training to the PhD level, and is committed to developing world-class healthcare professionals who can address regional shortages in the sector.',
                'office_location' => 'Health Sciences Block, Room 101, KAFU Main Campus',
                'email'           => 'dept.optometry@kafu.ac.ke',
                'phone'           => '+254 700 100 600',
                'sort_order'      => 1,
            ],
            [
                'school_code'     => 'SHS',
                'name'            => 'Department of Nursing',
                'slug'            => 'nursing',
                'description'     => 'The Department of Nursing at Kaimosi Friends University is part of the School of Health Sciences, dedicated to training competent and globally competitive healthcare professionals. It integrates theory, clinical practice, research, and community engagement to address Kenya\'s healthcare workforce gap.',
                'vision'          => 'To be a centre of excellence in nursing education, research, and practice globally.',
                'hod_name'        => 'Dr. Anne Asiko Okanga',
                'hod_title'       => 'Chair, Nursing Department',
                'hod_email'       => 'a.okanga@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 611',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Dr.-Asiko-Nursing-300x300.jpg',
                'hod_bio'         => 'Dr. Anne Asiko Okanga chairs the Department of Nursing at Kaimosi Friends University School of Health Sciences. She leads a team committed to training competent, compassionate, and innovative health professionals through quality education, research, and community service.',
                'office_location' => 'Health Sciences Block, Room 115, KAFU Main Campus',
                'email'           => 'dept.nursing@kafu.ac.ke',
                'phone'           => '+254 700 100 610',
                'sort_order'      => 2,
            ],
            [
                'school_code'     => 'SHS',
                'name'            => 'Department of Clinical Medicine & Community Health',
                'slug'            => 'clinical-medicine-community-health',
                'description'     => 'The Department of Clinical Medicine and Community Health produces competent, ethical, and compassionate clinicians through evidence-based practice and patient-centred care. It offers postgraduate programmes in Clinical Medicine with specialisations in Reproductive Health, Mental Health, and Ophthalmology & Cataract Surgery.',
                'vision'          => 'To be a regional centre of excellence in clinical medicine education, innovation, and community health service.',
                'hod_name'        => 'Dr. Stella Papa',
                'hod_title'       => 'Chair, Clinical Medicine & Community Health',
                'hod_email'       => 's.papa@kafu.ac.ke',
                'hod_phone'       => '+254 700 100 621',
                'hod_photo_url'   => 'https://kafu.ac.ke/wp-content/uploads/Dr.-Stella-Papa-300x300.jpg',
                'hod_bio'         => 'Dr. Stella Papa chairs the Department of Clinical Medicine and Community Health at KAFU School of Health Sciences. She is dedicated to producing competent, ethical, and compassionate clinicians through evidence-based practice and patient-centred care, supported by strong partnerships with teaching hospitals and county health facilities.',
                'office_location' => 'Health Sciences Block, Room 205, KAFU Main Campus',
                'email'           => 'dept.clinicalmedicine@kafu.ac.ke',
                'phone'           => '+254 700 100 620',
                'sort_order'      => 3,
            ],
        ];

        foreach ($departments as $dept) {
            Department::create($dept);
        }
    }
}
