<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CouncilMember;
use App\Models\ManagementProfile;
use App\Models\Directorate;

class GovernanceSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedCouncil();
        $this->seedManagement();
        $this->seedDirectorates();
    }

    private function seedCouncil(): void
    {
        // Source: https://kafu.ac.ke/university-council/
        $members = [
            [
                'name'           => 'Prof. Stanley O. Khainga',
                'title'          => 'Chairman of the Council',
                'category'       => 'chairperson',
                'credentials'    => [],
                'bio'            => 'Prof. Stanley O. Khainga chairs the Kaimosi Friends University Council, providing strategic leadership and ensuring sound governance of the institution in accordance with the Universities Act, 2012 and the KAFU Charter.',
                'photo_url'      => '/imgs/staff/Prof.-Khainga.jpg',
                'position_order' => 1,
            ],
            [
                'name'           => 'Prof. Peter N. Mwita',
                'title'          => 'Secretary to the Council',
                'category'       => 'ex_officio',
                'credentials'    => ['PhD'],
                'bio'            => 'Prof. Peter N. Mwita is the Vice Chancellor of Kaimosi Friends University and serves as Secretary to the University Council. He is a Full Professor of Statistics and previously served as Deputy Vice-Chancellor (Research, Innovation & Linkages) at Machakos University.',
                'photo_url'      => '/imgs/staff/Prof.-Mwita-council.jpg',
                'position_order' => 2,
            ],
            [
                'name'           => 'Ms. Rose Chepkoech Langat',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => [],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Ms.-Langat.jpg',
                'position_order' => 3,
            ],
            [
                'name'           => 'Mr. David Mongosi Sigano',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => [],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Mr.-Mongosi.jpg',
                'position_order' => 4,
            ],
            [
                'name'           => 'Dr. Moses Osia Mwanje',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['PhD'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Dr.-Mwanje.jpg',
                'position_order' => 5,
            ],
            [
                'name'           => 'Mr. Yussuf Kala',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => [],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Mr.-Kala.jpg',
                'position_order' => 6,
            ],
            [
                'name'           => 'CPA Gilbert K. Kangogo',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['CPA (K)'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/CPA-Kangogo.jpg',
                'position_order' => 7,
            ],
            [
                'name'           => 'Dr. Thaddaeus W. Egondi',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['PhD'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Dr.-Egondi.jpg',
                'position_order' => 8,
            ],
            [
                'name'           => 'Dr. Milton Njuki',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['PhD'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Dr.-Njuki.jpg',
                'position_order' => 9,
            ],
        ];

        foreach ($members as $member) {
            CouncilMember::firstOrCreate(
                ['name' => $member['name']],
                $member
            );
        }
    }

    private function seedManagement(): void
    {
        $profiles = [
            [
                'name'           => 'Prof. Peter N. Mwita',
                'title'          => 'Vice Chancellor',
                'category'       => 'vc',
                'bio'            => 'Prof. Peter N. Mwita (born 15 July 1968) is the Vice Chancellor of Kaimosi Friends University and Secretary to the University Council. He is a Full Professor of Statistics and holds a PhD. He previously served as Deputy Vice-Chancellor (Research, Innovation & Linkages) at Machakos University, where he also served as Acting Vice Chancellor. He has served as Dean of the School of Mathematical Sciences and Chairman of the Department of Statistics and Actuarial Sciences at Jomo Kenyatta University of Agriculture and Technology (JKUAT). He played a key role in restructuring the Kenya National Bureau of Statistics (KNBS) into a competitive semi-autonomous government agency. He currently chairs the Board of Governors of Kendege Technical and Vocational College.',
                'email'          => 'vc@kafu.ac.ke',
                'office'         => 'Vice Chancellor\'s Office, Main Administration Block',
                'phone'          => '+254 777 373 633',
                'photo_url'      => '/imgs/staff/Prof.-Mwita-council.jpg',
                'position_order' => 1,
            ],
            [
                'name'           => 'Prof. Fred. A. Amimo',
                'title'          => 'Deputy Vice Chancellor — Academic, Student Affairs & Research',
                'category'       => 'dvc',
                'bio'            => 'Prof. Fred. A. Amimo serves as the Deputy Vice Chancellor responsible for Academic Affairs, Student Affairs, and Research (DVC ASA&R) at Kaimosi Friends University. He oversees all academic programmes, student welfare, curriculum development, quality assurance, and the university\'s research agenda across the five schools.',
                'email'          => 'dvc-asar@kafu.ac.ke',
                'office'         => 'DVC Academic Office, Administration Block',
                'phone'          => '+254 777 373 640',
                'photo_url'      => '/imgs/staff/Prof.-Amimo.jpg',
                'position_order' => 2,
            ],
            [
                'name'           => 'Prof. Thomas Kipkurgat',
                'title'          => 'Deputy Vice Chancellor — Administration, Finance, Planning & Development',
                'category'       => 'dvc',
                'bio'            => 'Prof. Thomas Kipkurgat serves as the Deputy Vice Chancellor responsible for Administration, Finance, Planning and Development (DVC AFP&D) at Kaimosi Friends University. He oversees the university\'s administrative operations, financial management, strategic planning, and campus infrastructure development.',
                'email'          => 'dvc-afpd@kafu.ac.ke',
                'office'         => 'DVC Administration Office, Administration Block',
                'phone'          => '+254 777 373 642',
                'photo_url'      => '/imgs/staff/Kipkurgat.jpg',
                'position_order' => 3,
            ],
            [
                'name'           => 'Dr. Samuel Munda',
                'title'          => 'Senior Assistant Registrar — Academic Affairs',
                'category'       => 'registrar',
                'bio'            => 'Dr. Samuel Munda serves as the Senior Assistant Registrar for Academic Affairs at Kaimosi Friends University. He is responsible for academic registration, examinations management, student records, and compliance with Commission for University Education (CUE) standards.',
                'email'          => 'registrar-aa@kafu.ac.ke',
                'office'         => 'Academic Registrar\'s Office, Administration Block',
                'phone'          => '+254 777 373 650',
                'photo_url'      => '/imgs/Dr.-Munda-1.jpg',
                'position_order' => 4,
            ],
            [
                'name'           => 'Dr. Patrick Agesa',
                'title'          => 'Acting Deputy Registrar',
                'category'       => 'registrar',
                'bio'            => 'Dr. Patrick Agesa serves as the Acting Deputy Registrar at Kaimosi Friends University, supporting the overall registry functions including student admissions, records management, academic governance, and institutional compliance.',
                'email'          => 'registrar@kafu.ac.ke',
                'office'         => 'Registry, Administration Block',
                'phone'          => '+254 777 373 651',
                'photo_url'      => '/imgs/staff/Dr.-Agesa.jpg',
                'position_order' => 5,
            ],
            [
                'name'           => 'CPA Emmanuel M. Momanyi',
                'title'          => 'Finance Officer',
                'category'       => 'finance',
                'bio'            => 'CPA Emmanuel M. Momanyi is the Finance Officer of Kaimosi Friends University, responsible for financial governance, budgeting, financial reporting, fee collection, procurement oversight, and compliance with the Public Finance Management Act.',
                'email'          => 'finance@kafu.ac.ke',
                'office'         => 'Finance Department, Administration Block',
                'phone'          => '+254 777 373 660',
                'photo_url'      => '/imgs/IMGPSP_001.png',
                'position_order' => 6,
            ],
            [
                'name'           => 'Dr. Fredrick M. Nyambane',
                'title'          => 'Dean of Students',
                'category'       => 'other',
                'bio'            => 'Dr. Fredrick M. Nyambane serves as the Dean of Students at Kaimosi Friends University, overseeing student welfare, counselling services, accommodation, clubs and societies, and the general wellbeing of the student body.',
                'email'          => 'dean.students@kafu.ac.ke',
                'office'         => 'Dean of Students Office, Student Centre',
                'phone'          => '+254 777 373 670',
                'photo_url'      => '/imgs/staff/Monanti.jpg',
                'position_order' => 7,
            ],
        ];

        foreach ($profiles as $profile) {
            ManagementProfile::firstOrCreate(
                ['name' => $profile['name'], 'category' => $profile['category']],
                $profile
            );
        }
    }

    private function seedDirectorates(): void
    {
        // Source: https://kafu.ac.ke/directorates-centres/
        $directorates = [
            [
                'name'              => 'Directorate of Information and Communication Technology Services',
                'slug'              => 'ict',
                'tagline'           => 'Powering Digital Transformation at KAFU',
                'description'       => 'The Directorate of Information and Communication Technology (ICTs) is the central support unit that provides all the University\'s ICT services and facilities. Our directorate is committed to supporting, improving, and transforming how ICTs are used across Kaimosi Friends University (KAFU). At KAFU, our goal is to provide the best possible experience for our students and staff, which is why we are persistently improving the way we work. Our ongoing ICTs Transformation Journey is focused on delivering significant improvements to our systems, website, connectivity, and services. This will empower our staff and students to work flexibly with all the information they need at their fingertips. The wireless network (Wi-Fi) is now available across the University campuses, offering connection speeds that are significantly faster than before. We are continually upgrading our infrastructure to increase the internet connection speed and enhance the reliability of our services.',
                'director_name'       => 'Mr. Yohana Obiye',
                'director_title'      => 'In-Charge, ICTS',
                'director_photo_url'  => '/images/directors/yohana-obiye.jpg',
                'director_email'      => 'ict@kafu.ac.ke',
                'director_phone'    => '+254 777 373 680',
                'director_bio'      => 'Mr. Yohana Obiye is the In-Charge of the Directorate of Information and Communication Technology Services (ICTS) at Kaimosi Friends University. He oversees the university\'s digital infrastructure, enterprise systems, network services, information systems, and web services, leading the ongoing ICTs Transformation Journey to improve connectivity, systems, and digital services across the institution.',
                'functions'         => [
                    'ICT Support: Installation, maintenance, and repair of all university computer systems and equipment; management of both managed and non-managed devices on the network',
                    'Network Infrastructure and Security: Design and maintenance of the campus-wide High-Speed Local Area Network (LAN) and Data Communication systems; implementation of information security and all ICT networking projects',
                    'Network Management: Creation and maintenance of network configuration and addressing policy; maximising network uptime and performance',
                    'Information Systems: Development and deployment of application software for information management; administration of the Student Portal and ERP server',
                    'Information Security: Coordination and securing of all university data; compliance with Standard Information Security Procedures',
                    'Web Services: Management of the university\'s strategic web presence, content development, upload, and storage; integration of disparate systems into a unified online platform',
                    'E-Learning and Innovation: Support and enhancement of the e-learning infrastructure; guidance on adoption of new ICT in teaching including audio-visuals and video conferencing',
                    'Critical Systems Management: Management of web and repository servers and support for departmental critical systems',
                ],
                'services'          => [
                    'ICT helpdesk and technical support',
                    'Equipment maintenance and PC upgrades for staff and students',
                    'Network connectivity, Wi-Fi access, and managed device support',
                    'Student Portal access and records management (online registration, fee statements)',
                    'ERP system hosting and access for academic and administrative functions',
                    'E-learning platform support and video conferencing tools',
                    'University website management and digital content services',
                    'Information security and data protection services',
                ],
                'quick_links'       => [
                    ['label' => 'Student Portal', 'url' => 'https://portal.kafu.ac.ke', 'external' => true],
                    ['label' => 'E-Learning Platform', 'url' => 'https://elearning.kafu.ac.ke', 'external' => true],
                    ['label' => 'ICT Support Desk', 'url' => '/contact'],
                ],
                'position_order'    => 1,
            ],
            [
                'name'              => 'Directorate of Corporate Affairs',
                'slug'              => 'corporate-affairs',
                'tagline'           => 'Telling the KAFU Story to the World',
                'description'       => 'At Kaimosi Friends University, communication is a strategic function that underpins institutional growth, visibility and reputation. The Corporate Affairs Department is entrusted with the responsibility of shaping and projecting the University\'s image through clear, consistent and credible engagement with our diverse stakeholders. Our role extends beyond information dissemination — we position the University by articulating its vision, showcasing its achievements and strengthening its identity in an increasingly competitive higher education landscape. Through strategic communication, media relations, branding, digital platforms and stakeholder engagement, we ensure that the University\'s voice remains authoritative, responsive and aligned to its core mandate of teaching, research and community service. The Corporate Affairs Section is domiciled in the Office of the Vice-Chancellor and serves as the central coordinating unit for the University\'s corporate communication and public relations functions.',
                'director_name'       => 'Mr. Silas Rugut',
                'director_title'      => 'Director, Corporate Affairs',
                'director_photo_url'  => '/images/directors/silas-rugut.jpg',
                'director_email'      => 'communications@kafu.ac.ke',
                'director_phone'      => '+254 777 373 740',
                'director_bio'        => 'Mr. Silas Rugut serves as Director of Corporate Affairs at Kaimosi Friends University, overseeing all institutional communications, media relations, branding, digital platforms and stakeholder engagement. He leads the University\'s efforts to position KAFU as a credible, trusted and recognisable institutional brand in the higher education landscape.',
                'functions'         => [
                    'Marketing and Publicity: Drives visibility through targeted campaigns that promote programmes and support student enrolment',
                    'Corporate Communication: Manages internal and external communication to ensure clear, timely and consistent messaging',
                    'Media Relations: Coordinates engagement with print, broadcast and digital media; manages press releases and media queries',
                    'Branding and Identity: Formulates and implements policies governing the University\'s brand identity and visual communication',
                    'Digital Platforms and Web Content: Manages the University\'s web presence, social media channels and digital content strategy',
                    'Publications: Produces newsletters, annual reports, prospectus and other institutional publications',
                    'Events Coverage: Provides photography and videography for official University events and functions',
                    'Crisis Communication: Provides public relations advisory and manages institutional communications during sensitive situations',
                ],
                'services'          => [
                    'Media enquiries and press releases',
                    'Brand assets and logo usage guidelines',
                    'Photography and video coverage requests',
                    'Newsletter contributions and institutional publications',
                    'Social media promotion for university events and programmes',
                    'Website content management and digital communications',
                ],
                'quick_links'       => [
                    ['label' => 'Latest News', 'url' => '/news'],
                    ['label' => 'Events Calendar', 'url' => '/events'],
                    ['label' => 'Contact Corporate Affairs', 'url' => '/contact'],
                ],
                'position_order'    => 2,
            ],
            [
                'name'              => 'Directorate of Quality Assurance and Management Systems',
                'slug'              => 'quality-assurance',
                'tagline'           => 'Upholding Standards of Academic and Institutional Excellence',
                'description'       => 'The Directorate of Quality Assurance and Management Systems (DQAMS) serves as the core institutional body ensuring excellence and integrity at Kaimosi Friends University. Formed in 2021 through a merger, DQAMS operates under two key sections: Quality Assurance (QA) for academic standards, and Quality Management Systems (QMS), guided by ISO 9001:2015 principles, for process efficiency. The primary mission of DQAMS is to ensure that all academic programmes and operational processes meet or exceed national and international quality benchmarks, fostering a campus-wide culture of continuous improvement. This mandate includes guaranteeing the admission of qualified students and the delivery of market-driven, competency-based programmes; conducting mandatory internal audits twice annually; coordinating external audits to validate ISO conformity; and investing in regular staff training on quality management standards and best practices in academic governance.',
                'director_name'       => 'Mr. Nicholas S. Khasoha',
                'director_title'      => 'In-Charge, DQAMS',
                'director_photo_url'  => '/images/directors/nicholas-khasoha.jpg',
                'director_email'      => 'quality.assurance@kafu.ac.ke',
                'director_phone'    => '+254 777 373 720',
                'director_bio'      => 'Mr. Nicholas S. Khasoha serves as In-Charge of the Directorate of Quality Assurance and Management Systems (DQAMS) at Kaimosi Friends University, overseeing both the Quality Assurance and Quality Management Systems sections. He coordinates internal and external audits, ISO 9001:2015 compliance, academic programme reviews, and institutional capacity building on quality standards.',
                'functions'         => [
                    'Academic Quality Assurance: Guaranteeing the admission of qualified students and the delivery of market-driven, competency-based academic programmes',
                    'Internal Audits: Conducting mandatory internal audits twice annually to assess compliance with quality standards',
                    'External Audit Coordination: Coordinating external audits to validate ISO 9001:2015 conformity and quality standards',
                    'Capacity Building: Recruiting and training quality auditors and conducting Lead Auditor Training',
                    'Documentation and Compliance: Developing the QA Handbook and instituting procedures for quality management',
                    'ISO Certification Maintenance: Ensuring timely Surveillance Fee payment and ongoing ISO certification compliance',
                    'Engagement and Alignment: Hosting ISO awareness training, Management Representative Conferences, and regional quality forums',
                    'Programme Reviews: Facilitating academic programme reviews and curriculum audits in line with CUE guidelines',
                ],
                'services'          => [
                    'Programme accreditation support and CUE compliance advisory',
                    'Internal quality audit coordination',
                    'ISO 9001:2015 certification maintenance',
                    'Staff training on quality management standards',
                    'Quality management documentation and handbook development',
                    'Institutional performance data and quality reports',
                ],
                'quick_links'       => [
                    ['label' => 'Academic Programmes', 'url' => '/programmes'],
                    ['label' => 'Schools & Faculties', 'url' => '/schools'],
                ],
                'position_order'    => 3,
            ],
            [
                'name'              => 'Directorate of Open, Distance and E-Learning',
                'slug'              => 'open-distance-elearning',
                'tagline'           => 'Expanding Access to Quality Higher Education',
                'description'       => 'Kaimosi Friends University (KAFU) has been at the forefront of modern education, seamlessly blending traditional on-campus excellence with a dynamic Open, Distance & e-Learning (ODeL) platform. The ODeL Directorate was established with a clear mandate to dismantle the barriers of the conventional classroom by focusing on three core pillars: accessibility, flexibility, and innovation. By widening the reach of quality higher education and adapting to the modern student\'s lifestyle, KAFU ensures that learning extends far beyond physical boundaries. We believe that your location or schedule should never dictate your potential; therefore, our programmes are designed to be immersive and participative, providing distance learners with the same academic rigour and support as those on campus. Whether you are balancing work commitments, family responsibilities, or geographical constraints, KAFU provides a seamless educational experience tailored to your personal choice and professional goals.',
                'director_name'       => 'Dr. Hillan Ronoh',
                'director_title'      => 'Director, ODeL',
                'director_photo_url'  => '/images/directors/hillan-ronoh.jpg',
                'director_email'      => 'odel@kafu.ac.ke',
                'director_phone'    => '+254 777 373 770',
                'director_bio'      => 'Dr. Hillan Ronoh serves as Director of the Directorate of Open, Distance and E-Learning at Kaimosi Friends University. He leads the University\'s efforts to make quality higher education accessible to students regardless of location or schedule, overseeing the LMS platform, distance programme delivery, learner support services, and academic staff capacity building in online teaching.',
                'functions'         => [
                    'Synchronous and Asynchronous Teaching Support: Providing tools and sessions for live interaction (chat, video conferencing, virtual classrooms) and asynchronous resources (recorded lectures, readings, assignments)',
                    'Learner Support Services: Including orientation, enrolment to the LMS and courses, tutorials, library and resource support, issuing reports, and maintaining student records',
                    'Technical Support and Help Desk: Helping students and faculty with access to the platform, navigation, software/hardware issues, and troubleshooting connectivity',
                    'Module Development and Production: Facilitating and supporting the designing, development, and uploading of course materials (digital and multimedia) for online or blended learning',
                    'Learning Management System (LMS) Administration: Managing and maintaining the LMS platform — uploading materials, managing user access, ensuring uptime, configuring interactive tools (forums, quizzes, live sessions)',
                    'Assessment and Examinations: Managing continuous assessments, assignments, quizzes, exams, grading, and feedback mechanisms',
                    'Quality Assurance and Monitoring: Collaboration with DQAMS to ensure that course materials, delivery, learner support, and tools maintain required standards',
                    'Capacity Building: Training academic staff and tutors on effective online and blended course design, facilitation, and assessment',
                ],
                'services'          => [
                    'ODeL programme information and application guidance',
                    'Distance learner registration and LMS enrolment support',
                    'E-learning platform access and technical support',
                    'Online study materials and digital resource access',
                    'Assessment, examination management and grading support',
                    'Online examination registration and invigilation support',
                    'ODeL fee structure advisory',
                ],
                'quick_links'       => [
                    ['label' => 'E-Learning Platform', 'url' => 'https://elearning.kafu.ac.ke', 'external' => true],
                    ['label' => 'ODeL Programmes', 'url' => '/programmes?mode=distance'],
                    ['label' => 'Student Portal', 'url' => 'https://portal.kafu.ac.ke', 'external' => true],
                    ['label' => 'Apply for ODeL Programme', 'url' => '/admissions'],
                ],
                'position_order'    => 4,
            ],
            [
                'name'              => 'Directorate of Performance Planning and Contracting',
                'slug'              => 'planning-performance-contracting',
                'tagline'           => 'Driving Strategic Growth and Institutional Accountability',
                'description'       => 'Performance Contracting (PC) is the cornerstone of Kaimosi Friends University\'s (KAFU) commitment to delivering high-quality public service. As a critical mechanism under the Public Sector Reforms agenda, the PC is a negotiated, legally-binding agreement between the Government of the Republic of Kenya (through the Ministry of Education) and the University Management. This system ensures that our operations are not only mission-driven but also aligned with national development goals, providing a clear framework for measuring institutional success. The Directorate of Performance Planning and Contracting is charged with institutionalising accountability and transparency, enhancing service delivery through impartiality and fairness, and guaranteeing the effective, efficient, and responsible use of public funds entrusted to the University. Through this robust system, every member of the University community is aligned with KAFU\'s strategic goals, driving the institution toward becoming a benchmark of excellence in higher education service delivery.',
                'director_name'       => 'Dr. Metrine Sulungi',
                'director_title'      => 'Director, PPC',
                'director_photo_url'  => '/images/directors/metrine-sulungi.jpg',
                'director_email'      => 'planning@kafu.ac.ke',
                'director_phone'    => '+254 777 373 780',
                'director_bio'      => 'Dr. Metrine Sulungi serves as Director of Performance Planning and Contracting at Kaimosi Friends University, overseeing the University\'s compliance with government performance contracting obligations and leading institutional strategic planning and monitoring.',
                'functions'         => [
                    'Target Cascading: Setting comprehensive performance targets and extending the contract to all departments, sections, units, levels, and cadres of employees for complete institutional integration',
                    'Monitoring and Reporting: Continuously tracking progress and submitting detailed quarterly and annual reports to designated government agencies',
                    'Accountability and Integrity: Institutionalising a culture of accountability, transparency, and promoting the core values and principles of the public service',
                    'Service Delivery Enhancement: Mandating impartiality, fairness, and responsiveness in the provision of public services',
                    'Resource Optimisation: Guaranteeing the effective, efficient, and responsible use of public funds entrusted to the University',
                    'Strategic Planning: Coordinating the development and monitoring of the University\'s strategic plan and institutional development programmes',
                    'Institutional Research and Statistics: Managing institutional data and preparing evidence-based reports for management and external agencies',
                ],
                'services'          => [
                    'Institutional statistics and data requests',
                    'Strategic plan information and progress updates',
                    'Performance contracting compliance advisory',
                    'Quarterly and annual performance reports',
                    'Development project planning and M&E support',
                ],
                'quick_links'       => [
                    ['label' => 'About KAFU', 'url' => '/about'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 5,
            ],
            [
                'name'              => 'Directorate of Research, Innovation and Outreach',
                'slug'              => 'research-innovation',
                'tagline'           => 'Generating Knowledge that Transforms Society',
                'description'       => 'Welcome to the Directorate of Research, Innovation and Outreach (DRIO) at Kaimosi Friends University (KAFU) — the hub of scholarly excellence, creativity, and community engagement. At KAFU, we view research and innovation not merely as academic pursuits, but as transformative tools for societal advancement. Through DRIO, the University fosters a dynamic research culture that inspires discovery, nurtures young researchers, and translates scientific knowledge into real-world impact. Our strategic focus is to build a strong ecosystem that supports multidisciplinary research, technology transfer, and partnerships that address national and global development challenges. The Directorate coordinates research funding, grant applications, capacity building, intellectual property management, and outreach initiatives that connect the University with government, industry, and community partners. We encourage staff and students to pursue curiosity-driven and problem-oriented research that contributes to KAFU\'s strategic plan, Kenya\'s Vision 2030, the African Union\'s Agenda 2063, and the UN Sustainable Development Goals (SDGs).',
                'director_name'       => 'Dr. Victor Shikuku',
                'director_title'      => 'Director, RIO',
                'director_photo_url'  => '/images/directors/victor-shikuku.jpg',
                'director_email'      => 'research@kafu.ac.ke',
                'director_phone'    => '+254 777 373 710',
                'director_bio'      => 'Dr. Victor Shikuku leads the Directorate of Research, Innovation and Outreach (DRIO) at Kaimosi Friends University. He champions a vibrant research culture, overseeing grant acquisition support, intellectual property management, research ethics review, and community outreach activities that connect the University with government, industry, and community partners.',
                'functions'         => [
                    'Enhance Research Excellence: Foster a vibrant research culture through capacity building, mentorship, and the establishment of multidisciplinary research teams that address emerging scientific and societal challenges',
                    'Promote Innovation and Technology Transfer: Support the development, protection, and commercialisation of innovative ideas, products, and technologies generated within the University',
                    'Mobilise Research Funding: Attract and manage internal and external research grants through partnerships with government agencies, industry, and international collaborators',
                    'Strengthen Community Outreach and Engagement: Bridge academic research with societal needs through community-based programmes, policy engagement, and extension services',
                    'Facilitate Research Dissemination and Visibility: Promote publication of research outputs in peer-reviewed journals, organise scientific conferences, and enhance the global visibility of KAFU\'s research achievements',
                    'Uphold Research Ethics and Integrity: Ensure all research and outreach activities adhere to ethical standards and regulatory frameworks through the Scientific and Ethics Review Committee',
                    'Supervision of the KAFU Research Journal and Institutional Repository',
                    'Intellectual property management and commercialisation support',
                ],
                'services'          => [
                    'Research proposal development and grant writing support',
                    'Funding opportunity alerts and external grant application support',
                    'Research ethics clearance via the Scientific and Ethics Review Committee',
                    'Research data management and storage',
                    'Conference travel and presentation grants',
                    'Research collaboration and partnership matching',
                    'Commercialisation and technology transfer advisory',
                ],
                'quick_links'       => [
                    ['label' => 'Research Overview', 'url' => '/research'],
                    ['label' => 'Research Projects', 'url' => '/research/projects'],
                    ['label' => 'Publications', 'url' => '/research/publications'],
                    ['label' => 'Research Partners', 'url' => '/research/partnerships'],
                ],
                'position_order'    => 6,
            ],
            [
                'name'              => 'Directorate of University Linkages, Alumni and Career Services',
                'slug'              => 'university-linkages-alumni-career',
                'tagline'           => 'Connecting KAFU to the World and Its Graduates to Opportunity',
                'description'       => 'The Directorate of University Linkages, Alumni and Career Services (DULACS) at Kaimosi Friends University (KAFU) was established in 2019 with the sole responsibility of overseeing matters of partnerships, collaborations, and linkages with like-minded organisations and institutions with the sole purpose of improving the University\'s image both locally and globally. DULACS is dedicated to serving as the link between the academic and the non-academic community by developing services and delivering programmes to facilitate student and staff engagement for their personal growth and for the good of society at large. We believe that it is through linkages, collaborations, and partnerships that we foster international awareness and deeper understanding of current emerging issues such as food security, unemployment, climate change, and epidemic diseases. The University, through DULACS, initiates, implements, and sustains collaborations with partners across the world to produce innovative research, deliver innovative teaching and learning, and create opportunities for students and staff to gain international experience through exchange programmes.',
                'director_name'       => 'Prof. Okumu Joseph Otsyulah',
                'director_title'      => 'Director, DULACS',
                'director_photo_url'  => '/images/directors/joseph-otsyulah.png',
                'director_email'      => 'linkages@kafu.ac.ke',
                'director_phone'    => '+254 777 373 730',
                'director_bio'      => 'Prof. Okumu Joseph Otsyulah CHRP(K) serves as Director of the Directorate of University Linkages, Alumni and Career Services (DULACS) at Kaimosi Friends University. He oversees all partnership, collaboration, alumni engagement, and career development activities, working to position KAFU as an internationally engaged institution while supporting graduates in building successful careers.',
                'functions'         => [
                    'Development and management of international and local partnership agreements (MoUs)',
                    'Coordination of student and staff exchange programmes',
                    'International student recruitment and support services',
                    'Visa and immigration guidance for international students',
                    'Alumni engagement and association management',
                    'Career development services and graduate placement support',
                    'Management of internship and industrial attachment programmes',
                    'Representation of KAFU at national and international forums',
                ],
                'services'          => [
                    'International student admission support',
                    'Student exchange programme coordination',
                    'MoU and partnership agreement management',
                    'Visa and immigration advisory',
                    'Alumni registration and networking',
                    'Career counselling and job placement support',
                    'Internship and attachment placement assistance',
                ],
                'quick_links'       => [
                    ['label' => 'International Students', 'url' => '/international'],
                    ['label' => 'Exchange Programmes', 'url' => '/international/exchange'],
                    ['label' => 'Our Partners', 'url' => '/international/partnerships'],
                    ['label' => 'Career Services', 'url' => '/contact'],
                ],
                'position_order'    => 7,
            ],
            [
                'name'              => 'Directorate of Graduate Studies',
                'slug'              => 'graduate-studies',
                'tagline'           => 'Advancing Postgraduate Excellence at KAFU',
                'description'       => 'The Directorate of Graduate Studies coordinates admission, teaching, field research, supervision and examination of students in diverse programmes leading to the award of Ph.D. and Masters degrees as well as Postgraduate Diplomas. It is headed by a director who chairs the Board of Graduate Studies (BGS). The mandate and core objective of the directorate is to facilitate both students and graduate faculty to implement effective processes in advanced level study in compliance with the University\'s graduate study policy, CUE guidelines and to attain results comparable with national, regional and international best practices. This positions KAFU as an emerging centre of excellence in Information Technology, Sciences, Arts, Education and Business Studies. The Directorate also promotes multidisciplinary approaches and continuous engagement of staff, students and industry practitioners through regular dissemination in the form of seminars, workshops, conferences and collaborative study.',
                'director_name'       => 'Prof. Benson O. Ojwang',
                'director_title'      => 'Director, GS',
                'director_photo_url'  => '/images/directors/benson-ojwang.jpg',
                'director_email'      => 'graduate.studies@kafu.ac.ke',
                'director_phone'    => '+254 777 373 700',
                'director_bio'      => 'Prof. Benson O. Ojwang serves as Director of Graduate Studies at Kaimosi Friends University, chairing the Board of Graduate Studies and overseeing all postgraduate programmes — Masters, Ph.D., and Postgraduate Diplomas — across the university\'s five schools.',
                'functions'         => [
                    'Coordination of all Masters, PhD and Postgraduate Diploma programmes university-wide',
                    'Chairing the Board of Graduate Studies (BGS) and enforcing graduate study policy',
                    'Management of postgraduate admissions in compliance with CUE guidelines',
                    'Facilitation of thesis and dissertation supervision, examination and approval',
                    'Promotion of multidisciplinary research and continuous engagement of staff, students and industry practitioners',
                    'Organisation of seminars, workshops, conferences and collaborative study events',
                    'Development and review of postgraduate regulations and academic standards',
                ],
                'services'          => [
                    'Postgraduate programme information and counselling',
                    'Graduate student registration and record management',
                    'Thesis submission and examination coordination',
                    'Supervisor allocation and progress monitoring',
                    'Graduate certificate and transcript issuance',
                    'Postgraduate scholarship and fellowship information',
                ],
                'quick_links'       => [
                    ['label' => 'Postgraduate Programmes', 'url' => '/programmes'],
                    ['label' => 'Postgraduate Admissions', 'url' => '/admissions#postgraduate'],
                    ['label' => 'Fees & Scholarships', 'url' => '/admissions/fees'],
                ],
                'position_order'    => 8,
            ],
            [
                'name'              => 'Directorate of Enterprise and Resource Mobilization',
                'slug'              => 'enterprises-resource-mobilization',
                'tagline'           => 'Generating Sustainable Revenue for University Growth',
                'description'       => 'The Directorate of Enterprise and Resource Mobilization (ERM) plays a strategic role in advancing Kaimosi Friends University\'s agenda on sustainability, innovation, practical training and income generation. Through its enterprise activities — particularly the University Farm — the Directorate continues to support teaching, research and resource mobilisation while promoting commercially viable and sustainable ventures. Our focus is to transform institutional resources into productive enterprises that contribute to the University\'s growth and long-term financial resilience. Key areas of operation include dairy production, crop farming, greenhouse farming, poultry, aquaculture, apiary development and other emerging income-generating initiatives. These enterprises provide students with practical exposure while strengthening the University\'s capacity to diversify revenue streams. We remain committed to prudent resource utilisation, innovation, strategic partnerships and continuous improvement.',
                'director_name'       => 'Dr. Damianus Okaka',
                'director_title'      => 'Director, Enterprise & Resource Mobilization',
                'director_photo_url'  => '/images/directors/damianus-okaka.jpg',
                'director_email'      => 'enterprises@kafu.ac.ke',
                'director_phone'    => '+254 777 373 790',
                'director_bio'      => 'Dr. Damianus Okaka serves as Director of Enterprise and Resource Mobilization at Kaimosi Friends University, overseeing all commercial enterprises including the University Farm, dairy production, crop farming, poultry, aquaculture, and apiary development, as well as resource mobilisation partnerships and fundraising activities.',
                'functions'         => [
                    'University Farm Management: Overseeing dairy production, crop farming, greenhouse farming, poultry, aquaculture, and apiary development',
                    'Income Generation: Developing and managing commercially viable enterprises that contribute to the University\'s financial resilience',
                    'Practical Training Support: Providing students with practical exposure to agricultural and enterprise activities aligned with their studies',
                    'Resource Mobilisation: Attracting funding from government, donors, development partners, and private sector through strategic partnerships',
                    'Enterprise Expansion: Identifying new income-generating opportunities and emerging ventures aligned with the University\'s mission',
                    'Innovation and Sustainability: Promoting prudent resource utilisation, sustainable farming practices, and continuous improvement',
                    'Reporting: Reporting on enterprise performance and resource mobilisation outcomes to University Management and Council',
                ],
                'services'          => [
                    'Sponsorship and partnership proposals',
                    'University facilities and conference hire',
                    'Commercial agricultural produce and farm products',
                    'Practical training attachments and field visits',
                    'Donation and endowment management',
                    'Commercial consultancy and advisory services',
                ],
                'quick_links'       => [
                    ['label' => 'About KAFU', 'url' => '/about'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 9,
            ],
            [
                'name'              => 'Centre of Excellence on Climate Action & Research',
                'slug'              => 'centre-climate-action-research',
                'tagline'           => 'Leading East Africa\'s Response to the Climate Crisis',
                'description'       => 'The Centre of Excellence on Climate Action and Research is a dedicated interdisciplinary unit at Kaimosi Friends University focused on generating knowledge, building capacity, and driving solutions to address climate change and environmental sustainability challenges in East Africa and beyond.',
                'director_name'     => 'Prof. Caroline Mulinya',
                'director_title'    => 'Director, Centre of Excellence on Climate Action & Research',
                'director_email'    => 'climate@kafu.ac.ke',
                'director_phone'    => '+254 777 373 795',
                'director_bio'      => null,
                'functions'         => [
                    'Conduct of interdisciplinary climate change research',
                    'Community education and awareness on climate action',
                    'Coordination of climate-related academic programmes',
                    'Partnerships with national and international climate organisations',
                    'Facilitation of climate policy advisory and advocacy',
                    'Management of climate data and research outputs',
                ],
                'services'          => [
                    'Climate research collaboration opportunities',
                    'Climate education and training programmes',
                    'Environmental consultancy and advisory',
                    'Research data and publications access',
                ],
                'quick_links'       => [
                    ['label' => 'Research Overview', 'url' => '/research'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 10,
            ],
            [
                'name'              => 'Directorate of International Relations & Partnerships',
                'slug'              => 'international-relations',
                'tagline'           => 'Connecting KAFU to the Global Academic Community',
                'description'       => 'The Directorate of International Relations and Partnerships manages KAFU\'s bilateral and multilateral academic partnerships with universities, research institutions, and development organisations worldwide. The Directorate facilitates student and staff mobility programmes, international student admissions, and joint research initiatives that advance KAFU\'s global profile.',
                'director_name'     => null,
                'director_title'    => 'Director, International Relations & Partnerships',
                'director_email'    => 'international@kafu.ac.ke',
                'director_phone'    => '+254 777 373 680',
                'director_bio'      => null,
                'functions'         => [
                    'Negotiation and management of international partnership agreements (MoUs)',
                    'Coordination of inbound and outbound student exchange programmes',
                    'International student recruitment, admission, and orientation support',
                    'Visa and immigration advisory for international students',
                    'Staff mobility and international scholarly visits',
                    'Representation of KAFU at international academic forums',
                    'Management of international scholarship and fellowship opportunities',
                ],
                'services'          => [
                    'International student admission support',
                    'Exchange programme coordination',
                    'Visa and immigration advisory',
                    'MoU and partnership enquiries',
                    'International scholarship information',
                ],
                'quick_links'       => [
                    ['label' => 'International Students', 'url' => '/international'],
                    ['label' => 'Exchange Programmes', 'url' => '/international/exchange'],
                    ['label' => 'Our Partners', 'url' => '/international/partnerships'],
                ],
                'position_order'    => 11,
            ],
            [
                'name'              => 'Directorate of Student Affairs',
                'slug'              => 'student-affairs',
                'tagline'           => 'Nurturing the Whole Student Beyond the Classroom',
                'description'       => 'The Directorate of Student Affairs is responsible for co-curricular student development, welfare, and campus life at Kaimosi Friends University. The Directorate oversees student organisations, counselling and wellness services, accommodation, sports and recreation, and student discipline — creating a safe, inclusive, and vibrant campus environment that supports holistic student growth.',
                'director_name'     => null,
                'director_title'    => 'Director, Student Affairs',
                'director_email'    => 'studentaffairs@kafu.ac.ke',
                'director_phone'    => '+254 777 373 660',
                'director_bio'      => null,
                'functions'         => [
                    'Coordination and oversight of all student organisations and clubs',
                    'Provision of counselling, mental health, and psychosocial support services',
                    'Management of student accommodation and residential welfare',
                    'Coordination of sports, recreation, and health promotion programmes',
                    'Student discipline and conflict resolution',
                    'Administration of student financial aid and bursary applications',
                    'Management of student identity cards and related services',
                    'Coordination of student induction and orientation programmes',
                ],
                'services'          => [
                    'Student counselling and mental health support',
                    'Accommodation allocation and hostel management',
                    'Sports and recreation facilities',
                    'Student club and organisation registration',
                    'Student bursary and financial aid applications',
                    'Student ID card services',
                ],
                'quick_links'       => [
                    ['label' => 'Student Services', 'url' => '/student-services'],
                    ['label' => 'Admissions', 'url' => '/admissions'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 12,
            ],
            [
                'name'              => 'Finance Department',
                'slug'              => 'finance',
                'tagline'           => 'Ensuring Sound Financial Stewardship of KAFU Resources',
                'description'       => 'The Finance Department is responsible for the financial management, accounting, budgeting, and reporting functions of Kaimosi Friends University. The Department ensures that KAFU\'s financial resources are managed prudently, transparently, and in accordance with applicable financial regulations, government guidelines, and the University\'s strategic objectives.',
                'director_name'     => null,
                'director_title'    => 'Finance Officer',
                'director_email'    => 'finance@kafu.ac.ke',
                'director_phone'    => '+254 777 373 640',
                'director_bio'      => null,
                'functions'         => [
                    'Preparation and management of the university budget',
                    'Processing of all financial transactions, payments, and payroll',
                    'Maintenance of accurate financial records and accounts',
                    'Preparation of financial statements and statutory reports',
                    'Compliance with government financial regulations and audit requirements',
                    'Management of student fee collection and accounts',
                    'Investment and asset management advisory',
                ],
                'services'          => [
                    'Student fee payment and receipting',
                    'Fee statements and balances',
                    'Staff salary and allowance processing',
                    'Supplier payment processing',
                    'Financial clearance for graduation',
                    'Fee structure information',
                ],
                'quick_links'       => [
                    ['label' => 'Fees & Funding', 'url' => '/admissions/fees'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 13,
            ],
            [
                'name'              => 'Procurement Department',
                'slug'              => 'procurement',
                'tagline'           => 'Delivering Value Through Transparent and Compliant Procurement',
                'description'       => 'The Procurement Department manages all procurement of goods, works, and services at Kaimosi Friends University in compliance with the Public Procurement and Asset Disposal Act (PPADA) 2015 and applicable university policies. The Department ensures that university acquisitions deliver value for money, promote transparency, and support KAFU\'s operational and academic needs.',
                'director_name'     => null,
                'director_title'    => 'Supply Chain Management Officer',
                'director_email'    => 'procurement@kafu.ac.ke',
                'director_phone'    => '+254 777 373 650',
                'director_bio'      => null,
                'functions'         => [
                    'Planning and coordination of university procurement activities',
                    'Management of tendering, evaluation, and contract award processes',
                    'Maintenance of the supplier and vendor register',
                    'Asset management and disposal in accordance with PPADA 2015',
                    'Compliance monitoring and procurement audit support',
                    'Publication of procurement notices and tender documents',
                    'Coordination with user departments on procurement needs',
                ],
                'services'          => [
                    'Tender and procurement notices',
                    'Vendor and supplier registration',
                    'Contract management information',
                    'Asset disposal notices',
                    'Procurement policy and procedures guidance',
                ],
                'quick_links'       => [
                    ['label' => 'About KAFU', 'url' => '/about'],
                    ['label' => 'Procurement Policy', 'url' => '/about/policies'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 14,
            ],
        ];

        foreach ($directorates as $data) {
            Directorate::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
