<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CouncilMember;
use App\Models\ManagementProfile;
use App\Models\Directorate;

class GovernanceSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedCouncil();
        $this->seedManagement();
        $this->seedDirectorates();
    }

    private function seedCouncil(): void
    {
        // Source: https://kafu.ac.ke/university-council/
        $members = [
            [
                'name'           => 'Prof. Stanley O. Khainga',
                'title'          => 'Chairman of the Council',
                'category'       => 'chairperson',
                'credentials'    => [],
                'bio'            => 'Prof. Stanley O. Khainga chairs the Kaimosi Friends University Council, providing strategic leadership and ensuring sound governance of the institution in accordance with the Universities Act, 2012 and the KAFU Charter.',
                'photo_url'      => '/imgs/staff/Prof.-Khainga.jpg',
                'position_order' => 1,
            ],
            [
                'name'           => 'Prof. Peter N. Mwita',
                'title'          => 'Secretary to the Council',
                'category'       => 'ex_officio',
                'credentials'    => ['PhD'],
                'bio'            => 'Prof. Peter N. Mwita is the Vice Chancellor of Kaimosi Friends University and serves as Secretary to the University Council. He is a Full Professor of Statistics and previously served as Deputy Vice-Chancellor (Research, Innovation & Linkages) at Machakos University.',
                'photo_url'      => '/imgs/staff/Prof.-Mwita-council.jpg',
                'position_order' => 2,
            ],
            [
                'name'           => 'Ms. Rose Chepkoech Langat',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => [],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Ms.-Langat.jpg',
                'position_order' => 3,
            ],
            [
                'name'           => 'Mr. David Mongosi Sigano',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => [],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Mr.-Mongosi.jpg',
                'position_order' => 4,
            ],
            [
                'name'           => 'Dr. Moses Osia Mwanje',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['PhD'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Dr.-Mwanje.jpg',
                'position_order' => 5,
            ],
            [
                'name'           => 'Mr. Yussuf Kala',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => [],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Mr.-Kala.jpg',
                'position_order' => 6,
            ],
            [
                'name'           => 'CPA Gilbert K. Kangogo',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['CPA (K)'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/CPA-Kangogo.jpg',
                'position_order' => 7,
            ],
            [
                'name'           => 'Dr. Thaddaeus W. Egondi',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['PhD'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Dr.-Egondi.jpg',
                'position_order' => 8,
            ],
            [
                'name'           => 'Dr. Milton Njuki',
                'title'          => 'Member, University Council',
                'category'       => 'member',
                'credentials'    => ['PhD'],
                'bio'            => null,
                'photo_url'      => '/imgs/staff/Dr.-Njuki.jpg',
                'position_order' => 9,
            ],
        ];

        foreach ($members as $member) {
            CouncilMember::firstOrCreate(
                ['name' => $member['name']],
                $member
            );
        }
    }

    private function seedManagement(): void
    {
        $profiles = [
            [
                'name'           => 'Prof. Peter N. Mwita',
                'title'          => 'Vice Chancellor',
                'category'       => 'vc',
                'bio'            => 'Prof. Peter N. Mwita (born 15 July 1968) is the Vice Chancellor of Kaimosi Friends University and Secretary to the University Council. He is a Full Professor of Statistics and holds a PhD. He previously served as Deputy Vice-Chancellor (Research, Innovation & Linkages) at Machakos University, where he also served as Acting Vice Chancellor. He has served as Dean of the School of Mathematical Sciences and Chairman of the Department of Statistics and Actuarial Sciences at Jomo Kenyatta University of Agriculture and Technology (JKUAT). He played a key role in restructuring the Kenya National Bureau of Statistics (KNBS) into a competitive semi-autonomous government agency. He currently chairs the Board of Governors of Kendege Technical and Vocational College.',
                'email'          => 'vc@kafu.ac.ke',
                'office'         => 'Vice Chancellor\'s Office, Main Administration Block',
                'phone'          => '+254 777 373 633',
                'photo_url'      => '/imgs/staff/Prof.-Mwita-council.jpg',
                'position_order' => 1,
            ],
            [
                'name'           => 'Prof. Fred. A. Amimo',
                'title'          => 'Deputy Vice Chancellor — Academic, Student Affairs & Research',
                'category'       => 'dvc',
                'bio'            => 'Prof. Fred. A. Amimo serves as the Deputy Vice Chancellor responsible for Academic Affairs, Student Affairs, and Research (DVC ASA&R) at Kaimosi Friends University. He oversees all academic programmes, student welfare, curriculum development, quality assurance, and the university\'s research agenda across the five schools.',
                'email'          => 'dvc-asar@kafu.ac.ke',
                'office'         => 'DVC Academic Office, Administration Block',
                'phone'          => '+254 777 373 640',
                'photo_url'      => '/imgs/staff/Prof.-Amimo.jpg',
                'position_order' => 2,
            ],
            [
                'name'           => 'Prof. Thomas Kipkurgat',
                'title'          => 'Deputy Vice Chancellor — Administration, Finance, Planning & Development',
                'category'       => 'dvc',
                'bio'            => 'Prof. Thomas Kipkurgat serves as the Deputy Vice Chancellor responsible for Administration, Finance, Planning and Development (DVC AFP&D) at Kaimosi Friends University. He oversees the university\'s administrative operations, financial management, strategic planning, and campus infrastructure development.',
                'email'          => 'dvc-afpd@kafu.ac.ke',
                'office'         => 'DVC Administration Office, Administration Block',
                'phone'          => '+254 777 373 642',
                'photo_url'      => '/imgs/staff/Kipkurgat.jpg',
                'position_order' => 3,
            ],
            [
                'name'           => 'Dr. Samuel Munda',
                'title'          => 'Senior Assistant Registrar — Academic Affairs',
                'category'       => 'registrar',
                'bio'            => 'Dr. Samuel Munda serves as the Senior Assistant Registrar for Academic Affairs at Kaimosi Friends University. He is responsible for academic registration, examinations management, student records, and compliance with Commission for University Education (CUE) standards.',
                'email'          => 'registrar-aa@kafu.ac.ke',
                'office'         => 'Academic Registrar\'s Office, Administration Block',
                'phone'          => '+254 777 373 650',
                'photo_url'      => '/imgs/Dr.-Munda-1.jpg',
                'position_order' => 4,
            ],
            [
                'name'           => 'Dr. Patrick Agesa',
                'title'          => 'Acting Deputy Registrar',
                'category'       => 'registrar',
                'bio'            => 'Dr. Patrick Agesa serves as the Acting Deputy Registrar at Kaimosi Friends University, supporting the overall registry functions including student admissions, records management, academic governance, and institutional compliance.',
                'email'          => 'registrar@kafu.ac.ke',
                'office'         => 'Registry, Administration Block',
                'phone'          => '+254 777 373 651',
                'photo_url'      => '/imgs/staff/Dr.-Agesa.jpg',
                'position_order' => 5,
            ],
            [
                'name'           => 'CPA Emmanuel M. Momanyi',
                'title'          => 'Finance Officer',
                'category'       => 'finance',
                'bio'            => 'CPA Emmanuel M. Momanyi is the Finance Officer of Kaimosi Friends University, responsible for financial governance, budgeting, financial reporting, fee collection, procurement oversight, and compliance with the Public Finance Management Act.',
                'email'          => 'finance@kafu.ac.ke',
                'office'         => 'Finance Department, Administration Block',
                'phone'          => '+254 777 373 660',
                'photo_url'      => '/imgs/IMGPSP_001.png',
                'position_order' => 6,
            ],
            [
                'name'           => 'Dr. Fredrick M. Nyambane',
                'title'          => 'Dean of Students',
                'category'       => 'other',
                'bio'            => 'Dr. Fredrick M. Nyambane serves as the Dean of Students at Kaimosi Friends University, overseeing student welfare, counselling services, accommodation, clubs and societies, and the general wellbeing of the student body.',
                'email'          => 'dean.students@kafu.ac.ke',
                'office'         => 'Dean of Students Office, Student Centre',
                'phone'          => '+254 777 373 670',
                'photo_url'      => '/imgs/staff/Monanti.jpg',
                'position_order' => 7,
            ],
        ];

        foreach ($profiles as $profile) {
            ManagementProfile::firstOrCreate(
                ['name' => $profile['name'], 'category' => $profile['category']],
                $profile
            );
        }
    }

    private function seedDirectorates(): void
    {
        // Source: https://kafu.ac.ke/directorates-centres/
        $directorates = [
            [
                'name'              => 'Directorate of Information and Communication Technology Services',
                'slug'              => 'ict',
                'tagline'           => 'Powering Digital Transformation at KAFU',
                'description'       => 'The Directorate of Information and Communication Technology Services is responsible for planning, implementing, and managing the university\'s technology infrastructure and digital services. From campus network connectivity to the enterprise resource planning system, the Directorate ensures that KAFU\'s digital platforms are reliable, secure, and aligned with the university\'s strategic goals.',
                'director_name'     => 'Mr. Yohana Obiye',
                'director_title'    => 'In-Charge, Directorate of ICT Services',
                'director_email'    => 'ict@kafu.ac.ke',
                'director_phone'    => '+254 777 373 680',
                'director_bio'      => 'Mr. Yohana Obiye is the In-Charge of the Directorate of Information and Communication Technology Services at Kaimosi Friends University, overseeing the university\'s digital infrastructure, enterprise systems, network services, and e-learning platforms.',
                'functions'         => [
                    'Management and maintenance of ICT infrastructure and networks',
                    'Administration of the university ERP and student information systems',
                    'Support and development of e-learning platforms',
                    'Cybersecurity policy and implementation',
                    'ICT procurement and asset management',
                    'Website and digital services administration',
                    'ICT training and user support for staff and students',
                    'Data backup, recovery, and business continuity planning',
                ],
                'services'          => [
                    'ICT helpdesk and technical support',
                    'Email and productivity tools provisioning',
                    'Network connectivity and Wi-Fi access',
                    'ERP system access and troubleshooting',
                    'E-learning platform support (Moodle)',
                    'Software licensing and computer lab management',
                    'Video conferencing and digital collaboration tools',
                ],
                'quick_links'       => [
                    ['label' => 'Student Portal', 'url' => 'https://portal.kafu.ac.ke', 'external' => true],
                    ['label' => 'E-Learning Platform', 'url' => 'https://elearning.kafu.ac.ke', 'external' => true],
                    ['label' => 'ICT Support Desk', 'url' => '/contact'],
                ],
                'position_order'    => 1,
            ],
            [
                'name'              => 'Directorate of Corporate Affairs',
                'slug'              => 'corporate-affairs',
                'tagline'           => 'Telling the KAFU Story to the World',
                'description'       => 'The Directorate of Corporate Affairs is the institutional voice of Kaimosi Friends University. It manages all internal and external communications, brand identity, media relations, publications, digital content, and event coverage, playing a central role in positioning KAFU as a credible, modern university to prospective students, partners, and the wider public.',
                'director_name'     => 'Mr. Silahs Rugut',
                'director_title'    => 'Director, Corporate Affairs',
                'director_email'    => 'communications@kafu.ac.ke',
                'director_phone'    => '+254 777 373 740',
                'director_bio'      => 'Mr. Silahs Rugut serves as Director of Corporate Affairs at Kaimosi Friends University, overseeing all institutional communications, media relations, brand identity, and publications.',
                'functions'         => [
                    'Management of institutional communications strategy',
                    'Media relations and press office management',
                    'Website content and digital communications management',
                    'University publications: newsletters, annual reports, prospectus',
                    'Brand identity management and compliance',
                    'Photography and videography for institutional events',
                    'Social media management and content creation',
                    'Crisis communications and public relations advisory',
                ],
                'services'          => [
                    'Media enquiries and press releases',
                    'Brand assets and logo usage guidelines',
                    'Photography and video coverage requests',
                    'Newsletter contributions and publications',
                    'Social media promotion for university events',
                    'Website content updates and management',
                ],
                'quick_links'       => [
                    ['label' => 'Latest News', 'url' => '/news'],
                    ['label' => 'Events Calendar', 'url' => '/events'],
                    ['label' => 'Contact Corporate Affairs', 'url' => '/contact'],
                ],
                'position_order'    => 2,
            ],
            [
                'name'              => 'Directorate of Quality Assurance and Management Systems (DQA&MS)',
                'slug'              => 'quality-assurance',
                'tagline'           => 'Upholding Standards of Academic and Institutional Excellence',
                'description'       => 'The Directorate of Quality Assurance and Management Systems (DQA&MS) ensures that Kaimosi Friends University maintains high standards in teaching, research, administration, and student services. The Directorate coordinates internal quality audits, programme reviews, and compliance monitoring, aligning with Commission for University Education (CUE) requirements and international best practices.',
                'director_name'     => 'Mr. Nicholas S. Khasoha',
                'director_title'    => 'In-Charge, Quality Assurance & Management Systems',
                'director_email'    => 'quality.assurance@kafu.ac.ke',
                'director_phone'    => '+254 777 373 720',
                'director_bio'      => 'Mr. Nicholas S. Khasoha serves as In-Charge of the Directorate of Quality Assurance and Management Systems at Kaimosi Friends University, coordinating internal quality audits, programme reviews, and CUE compliance.',
                'functions'         => [
                    'Development and implementation of the university quality management framework',
                    'Coordination of internal quality audits and peer reviews',
                    'Monitoring compliance with Commission for University Education (CUE) standards',
                    'Facilitation of academic programme reviews and curriculum audits',
                    'Administration of student and staff satisfaction surveys',
                    'Preparation of quality assurance reports for Council and Management',
                    'Coordination of institutional accreditation and external reviews',
                    'Training of quality champions across schools and departments',
                ],
                'services'          => [
                    'Programme accreditation support',
                    'Quality audit coordination',
                    'Performance management system administration',
                    'Staff training on quality standards',
                    'CUE compliance monitoring and advisory',
                    'Institutional statistics and performance data',
                ],
                'quick_links'       => [
                    ['label' => 'Academic Programmes', 'url' => '/programmes'],
                    ['label' => 'Schools & Faculties', 'url' => '/schools'],
                ],
                'position_order'    => 3,
            ],
            [
                'name'              => 'Directorate of Open Distance and E-Learning',
                'slug'              => 'open-distance-elearning',
                'tagline'           => 'Expanding Access to Quality Higher Education',
                'description'       => 'The Directorate of Open Distance and E-Learning (ODeL) coordinates the delivery of all open, distance, and online learning programmes at Kaimosi Friends University. The Directorate works in close collaboration with academic schools, the ICT Directorate, and external technology partners to ensure that distance learners receive the same quality of education as their campus-based peers, regardless of location or schedule.',
                'director_name'     => 'Dr. Hillan Ronoh',
                'director_title'    => 'Director, Open Distance and E-Learning',
                'director_email'    => 'odel@kafu.ac.ke',
                'director_phone'    => '+254 777 373 770',
                'director_bio'      => 'Dr. Hillan Ronoh serves as Director of the Directorate of Open Distance and E-Learning at Kaimosi Friends University, coordinating the university\'s distance learning strategy and e-learning platform management.',
                'functions'         => [
                    'Development and implementation of the university ODeL strategy',
                    'Coordination of distance and online programme registration and delivery',
                    'Management and maintenance of the KAFU e-learning platform (Moodle)',
                    'Training of academic staff in online course design and facilitation',
                    'Establishment and management of regional study centres',
                    'Quality assurance for online and distance learning programmes',
                    'Student support services for distance learners',
                    'Coordination of online examinations and proctoring',
                ],
                'services'          => [
                    'ODeL programme information and application guidance',
                    'Distance learner registration and course enrolment support',
                    'E-learning platform access and technical support',
                    'Online study materials and digital resource access',
                    'Regional study centre access and scheduling',
                    'Online examination registration and support',
                    'ODeL fee structure advisory',
                ],
                'quick_links'       => [
                    ['label' => 'E-Learning Platform', 'url' => 'https://elearning.kafu.ac.ke', 'external' => true],
                    ['label' => 'ODeL Programmes', 'url' => '/programmes?mode=distance'],
                    ['label' => 'Student Portal', 'url' => 'https://portal.kafu.ac.ke', 'external' => true],
                    ['label' => 'Apply for ODeL Programme', 'url' => '/admissions'],
                ],
                'position_order'    => 4,
            ],
            [
                'name'              => 'Directorate of Planning and Performance Contracting',
                'slug'              => 'planning-performance-contracting',
                'tagline'           => 'Driving Strategic Growth and Institutional Accountability',
                'description'       => 'The Directorate of Planning and Performance Contracting coordinates the university\'s strategic planning processes, performance contracting obligations, and institutional development programmes. It ensures that KAFU meets its commitments under the government\'s performance contracting framework while driving long-term development aligned with the university\'s strategic plan.',
                'director_name'     => 'Dr. Metrine Sulungai',
                'director_title'    => 'Director, Planning & Performance Contracting',
                'director_email'    => 'planning@kafu.ac.ke',
                'director_phone'    => '+254 777 373 780',
                'director_bio'      => 'Dr. Metrine Sulungai serves as Director of Planning and Performance Contracting at Kaimosi Friends University, coordinating the university\'s strategic planning processes and performance contracting obligations.',
                'functions'         => [
                    'Coordination of strategic planning and institutional development',
                    'Management of government performance contracting obligations',
                    'Preparation and monitoring of the university strategic plan',
                    'Institutional research, statistics, and data management',
                    'Coordination of annual performance reviews and reports',
                    'Monitoring and evaluation of university programmes and projects',
                    'Facilitation of development partner engagements',
                ],
                'services'          => [
                    'Institutional statistics and data requests',
                    'Strategic plan information and updates',
                    'Performance contracting compliance advisory',
                    'Development project planning support',
                ],
                'quick_links'       => [
                    ['label' => 'About KAFU', 'url' => '/about'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 5,
            ],
            [
                'name'              => 'Directorate of Research, Innovation and Outreach',
                'slug'              => 'research-innovation',
                'tagline'           => 'Generating Knowledge that Transforms Society',
                'description'       => 'The Directorate of Research, Innovation and Outreach drives KAFU\'s research agenda, fostering a culture of inquiry, discovery, and creative problem-solving. The Directorate supports researchers across all disciplines, facilitates funding acquisition, promotes the translation of research outputs into practical solutions, and coordinates community outreach activities.',
                'director_name'     => 'Dr. Victor Shikuku',
                'director_title'    => 'Director, Research, Innovation & Outreach',
                'director_email'    => 'research@kafu.ac.ke',
                'director_phone'    => '+254 777 373 710',
                'director_bio'      => 'Dr. Victor Shikuku leads the Directorate of Research, Innovation and Outreach at Kaimosi Friends University, managing the research strategy, grant acquisition support, ethics review, and community outreach activities.',
                'functions'         => [
                    'Development and implementation of the university research strategy',
                    'Management of the Research Management Information System (RMIS)',
                    'Coordination of internal research grants and seed funding',
                    'Support for external grant applications and research partnerships',
                    'Facilitation of research ethics review and approval',
                    'Promotion of research output through publications and conferences',
                    'Management of intellectual property and commercialisation',
                    'Supervision of the KAFU Research Journal',
                    'Coordination of community outreach and engagement programmes',
                ],
                'services'          => [
                    'Research proposal development support',
                    'Grant writing assistance and funding opportunity alerts',
                    'Research ethics clearance',
                    'Research data management and storage',
                    'Conference travel and presentation grants',
                    'Research collaboration matching',
                    'Commercialisation and technology transfer support',
                ],
                'quick_links'       => [
                    ['label' => 'Research Overview', 'url' => '/research'],
                    ['label' => 'Research Projects', 'url' => '/research/projects'],
                    ['label' => 'Publications', 'url' => '/research/publications'],
                    ['label' => 'Research Partners', 'url' => '/research/partnerships'],
                ],
                'position_order'    => 6,
            ],
            [
                'name'              => 'Directorate of University Linkages, Alumni and Career Services',
                'slug'              => 'university-linkages-alumni-career',
                'tagline'           => 'Connecting KAFU to the World and Its Graduates to Opportunity',
                'description'       => 'The Directorate of University Linkages, Alumni and Career Services manages KAFU\'s global and local partnerships, alumni relations, international student support, and career development services. The Directorate is committed to positioning KAFU as an internationally engaged institution and supporting graduates in building successful careers.',
                'director_name'     => 'Prof. Joseph O. Otsyulah',
                'director_title'    => 'Director, University Linkages, Alumni & Career Services',
                'director_email'    => 'linkages@kafu.ac.ke',
                'director_phone'    => '+254 777 373 730',
                'director_bio'      => null,
                'functions'         => [
                    'Development and management of international and local partnership agreements (MoUs)',
                    'Coordination of student and staff exchange programmes',
                    'International student recruitment and support services',
                    'Visa and immigration guidance for international students',
                    'Alumni engagement and association management',
                    'Career development services and graduate placement support',
                    'Management of internship and industrial attachment programmes',
                    'Representation of KAFU at national and international forums',
                ],
                'services'          => [
                    'International student admission support',
                    'Student exchange programme coordination',
                    'MoU and partnership agreement management',
                    'Visa and immigration advisory',
                    'Alumni registration and networking',
                    'Career counselling and job placement support',
                    'Internship and attachment placement assistance',
                ],
                'quick_links'       => [
                    ['label' => 'International Students', 'url' => '/international'],
                    ['label' => 'Exchange Programmes', 'url' => '/international/exchange'],
                    ['label' => 'Our Partners', 'url' => '/international/partnerships'],
                    ['label' => 'Career Services', 'url' => '/contact'],
                ],
                'position_order'    => 7,
            ],
            [
                'name'              => 'Directorate of Graduate Studies',
                'slug'              => 'graduate-studies',
                'tagline'           => 'Advancing Postgraduate Excellence at KAFU',
                'description'       => 'The Directorate of Graduate Studies coordinates all postgraduate programmes at Kaimosi Friends University, ensuring academic standards, research quality, and a conducive environment for advanced scholarship. The Directorate manages Master\'s and PhD programmes across all five schools, supporting graduate students from admission through to graduation.',
                'director_name'     => 'Prof. Benson O. Ojwang',
                'director_title'    => 'Director, Graduate Studies',
                'director_email'    => 'graduate.studies@kafu.ac.ke',
                'director_phone'    => '+254 777 373 700',
                'director_bio'      => null,
                'functions'         => [
                    'Coordination of all Masters and PhD programmes university-wide',
                    'Management of postgraduate admissions processes',
                    'Development and review of postgraduate regulations',
                    'Facilitation of thesis and dissertation examination',
                    'Postgraduate scholarship and fellowship administration',
                    'Graduate student mentorship and career development',
                    'Graduate programme quality assurance and compliance',
                ],
                'services'          => [
                    'Postgraduate programme information and counselling',
                    'Graduate student registration and record management',
                    'Thesis submission and examination coordination',
                    'Graduate research funding support',
                    'Supervisor allocation and progress monitoring',
                    'Graduate certificate and transcript issuance',
                ],
                'quick_links'       => [
                    ['label' => 'Postgraduate Programmes', 'url' => '/programmes'],
                    ['label' => 'Postgraduate Admissions', 'url' => '/admissions#postgraduate'],
                    ['label' => 'Fees & Scholarships', 'url' => '/admissions/fees'],
                ],
                'position_order'    => 8,
            ],
            [
                'name'              => 'Directorate of Enterprises and Resource Mobilization',
                'slug'              => 'enterprises-resource-mobilization',
                'tagline'           => 'Generating Sustainable Revenue for University Growth',
                'description'       => 'The Directorate of Enterprises and Resource Mobilization coordinates KAFU\'s income-generating activities, resource mobilization strategies, and commercial enterprises. It identifies and develops sustainable revenue streams that support the university\'s academic mission and infrastructure development goals.',
                'director_name'     => 'Dr. Damianus Okaka',
                'director_title'    => 'Director, Enterprises & Resource Mobilization',
                'director_email'    => 'enterprises@kafu.ac.ke',
                'director_phone'    => '+254 777 373 790',
                'director_bio'      => null,
                'functions'         => [
                    'Development and management of university commercial enterprises',
                    'Resource mobilization from government, donors, and development partners',
                    'Coordination of fundraising and endowment activities',
                    'Management of the university\'s income-generating units',
                    'Development of public-private partnership frameworks',
                    'Identification of new revenue opportunities aligned with the university mission',
                    'Reporting on enterprise performance to Management and Council',
                ],
                'services'          => [
                    'Sponsorship and partnership proposals',
                    'Conference and facilities hire',
                    'Commercial training and consultancy services',
                    'Donation and endowment management',
                ],
                'quick_links'       => [
                    ['label' => 'About KAFU', 'url' => '/about'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 9,
            ],
            [
                'name'              => 'Centre of Excellence on Climate Action & Research',
                'slug'              => 'centre-climate-action-research',
                'tagline'           => 'Leading East Africa\'s Response to the Climate Crisis',
                'description'       => 'The Centre of Excellence on Climate Action and Research is a dedicated interdisciplinary unit at Kaimosi Friends University focused on generating knowledge, building capacity, and driving solutions to address climate change and environmental sustainability challenges in East Africa and beyond.',
                'director_name'     => 'Prof. Caroline Mulinya',
                'director_title'    => 'Director, Centre of Excellence on Climate Action & Research',
                'director_email'    => 'climate@kafu.ac.ke',
                'director_phone'    => '+254 777 373 795',
                'director_bio'      => null,
                'functions'         => [
                    'Conduct of interdisciplinary climate change research',
                    'Community education and awareness on climate action',
                    'Coordination of climate-related academic programmes',
                    'Partnerships with national and international climate organisations',
                    'Facilitation of climate policy advisory and advocacy',
                    'Management of climate data and research outputs',
                ],
                'services'          => [
                    'Climate research collaboration opportunities',
                    'Climate education and training programmes',
                    'Environmental consultancy and advisory',
                    'Research data and publications access',
                ],
                'quick_links'       => [
                    ['label' => 'Research Overview', 'url' => '/research'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 10,
            ],
            [
                'name'              => 'Directorate of International Relations & Partnerships',
                'slug'              => 'international-relations',
                'tagline'           => 'Connecting KAFU to the Global Academic Community',
                'description'       => 'The Directorate of International Relations and Partnerships manages KAFU\'s bilateral and multilateral academic partnerships with universities, research institutions, and development organisations worldwide. The Directorate facilitates student and staff mobility programmes, international student admissions, and joint research initiatives that advance KAFU\'s global profile.',
                'director_name'     => null,
                'director_title'    => 'Director, International Relations & Partnerships',
                'director_email'    => 'international@kafu.ac.ke',
                'director_phone'    => '+254 777 373 680',
                'director_bio'      => null,
                'functions'         => [
                    'Negotiation and management of international partnership agreements (MoUs)',
                    'Coordination of inbound and outbound student exchange programmes',
                    'International student recruitment, admission, and orientation support',
                    'Visa and immigration advisory for international students',
                    'Staff mobility and international scholarly visits',
                    'Representation of KAFU at international academic forums',
                    'Management of international scholarship and fellowship opportunities',
                ],
                'services'          => [
                    'International student admission support',
                    'Exchange programme coordination',
                    'Visa and immigration advisory',
                    'MoU and partnership enquiries',
                    'International scholarship information',
                ],
                'quick_links'       => [
                    ['label' => 'International Students', 'url' => '/international'],
                    ['label' => 'Exchange Programmes', 'url' => '/international/exchange'],
                    ['label' => 'Our Partners', 'url' => '/international/partnerships'],
                ],
                'position_order'    => 11,
            ],
            [
                'name'              => 'Directorate of Student Affairs',
                'slug'              => 'student-affairs',
                'tagline'           => 'Nurturing the Whole Student Beyond the Classroom',
                'description'       => 'The Directorate of Student Affairs is responsible for co-curricular student development, welfare, and campus life at Kaimosi Friends University. The Directorate oversees student organisations, counselling and wellness services, accommodation, sports and recreation, and student discipline — creating a safe, inclusive, and vibrant campus environment that supports holistic student growth.',
                'director_name'     => null,
                'director_title'    => 'Director, Student Affairs',
                'director_email'    => 'studentaffairs@kafu.ac.ke',
                'director_phone'    => '+254 777 373 660',
                'director_bio'      => null,
                'functions'         => [
                    'Coordination and oversight of all student organisations and clubs',
                    'Provision of counselling, mental health, and psychosocial support services',
                    'Management of student accommodation and residential welfare',
                    'Coordination of sports, recreation, and health promotion programmes',
                    'Student discipline and conflict resolution',
                    'Administration of student financial aid and bursary applications',
                    'Management of student identity cards and related services',
                    'Coordination of student induction and orientation programmes',
                ],
                'services'          => [
                    'Student counselling and mental health support',
                    'Accommodation allocation and hostel management',
                    'Sports and recreation facilities',
                    'Student club and organisation registration',
                    'Student bursary and financial aid applications',
                    'Student ID card services',
                ],
                'quick_links'       => [
                    ['label' => 'Student Services', 'url' => '/student-services'],
                    ['label' => 'Admissions', 'url' => '/admissions'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 12,
            ],
            [
                'name'              => 'Finance Department',
                'slug'              => 'finance',
                'tagline'           => 'Ensuring Sound Financial Stewardship of KAFU Resources',
                'description'       => 'The Finance Department is responsible for the financial management, accounting, budgeting, and reporting functions of Kaimosi Friends University. The Department ensures that KAFU\'s financial resources are managed prudently, transparently, and in accordance with applicable financial regulations, government guidelines, and the University\'s strategic objectives.',
                'director_name'     => null,
                'director_title'    => 'Finance Officer',
                'director_email'    => 'finance@kafu.ac.ke',
                'director_phone'    => '+254 777 373 640',
                'director_bio'      => null,
                'functions'         => [
                    'Preparation and management of the university budget',
                    'Processing of all financial transactions, payments, and payroll',
                    'Maintenance of accurate financial records and accounts',
                    'Preparation of financial statements and statutory reports',
                    'Compliance with government financial regulations and audit requirements',
                    'Management of student fee collection and accounts',
                    'Investment and asset management advisory',
                ],
                'services'          => [
                    'Student fee payment and receipting',
                    'Fee statements and balances',
                    'Staff salary and allowance processing',
                    'Supplier payment processing',
                    'Financial clearance for graduation',
                    'Fee structure information',
                ],
                'quick_links'       => [
                    ['label' => 'Fees & Funding', 'url' => '/admissions/fees'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 13,
            ],
            [
                'name'              => 'Procurement Department',
                'slug'              => 'procurement',
                'tagline'           => 'Delivering Value Through Transparent and Compliant Procurement',
                'description'       => 'The Procurement Department manages all procurement of goods, works, and services at Kaimosi Friends University in compliance with the Public Procurement and Asset Disposal Act (PPADA) 2015 and applicable university policies. The Department ensures that university acquisitions deliver value for money, promote transparency, and support KAFU\'s operational and academic needs.',
                'director_name'     => null,
                'director_title'    => 'Supply Chain Management Officer',
                'director_email'    => 'procurement@kafu.ac.ke',
                'director_phone'    => '+254 777 373 650',
                'director_bio'      => null,
                'functions'         => [
                    'Planning and coordination of university procurement activities',
                    'Management of tendering, evaluation, and contract award processes',
                    'Maintenance of the supplier and vendor register',
                    'Asset management and disposal in accordance with PPADA 2015',
                    'Compliance monitoring and procurement audit support',
                    'Publication of procurement notices and tender documents',
                    'Coordination with user departments on procurement needs',
                ],
                'services'          => [
                    'Tender and procurement notices',
                    'Vendor and supplier registration',
                    'Contract management information',
                    'Asset disposal notices',
                    'Procurement policy and procedures guidance',
                ],
                'quick_links'       => [
                    ['label' => 'About KAFU', 'url' => '/about'],
                    ['label' => 'Procurement Policy', 'url' => '/about/policies'],
                    ['label' => 'Contact Us', 'url' => '/contact'],
                ],
                'position_order'    => 14,
            ],
        ];

        foreach ($directorates as $data) {
            Directorate::firstOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
