<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InternationalPartnership;
use App\Models\ExchangeProgramme;

class InternationalSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedPartnerships();
        $this->seedExchangeProgrammes();
    }

    private function seedPartnerships(): void
    {
        $partnerships = [
            [
                'slug' => 'earlham-college',
                'name' => 'Earlham College',
                'short_name' => 'Earlham',
                'country' => 'United States',
                'country_code' => 'USA',
                'type' => 'quaker',
                'status' => 'active',
                'description' => 'A fellow Quaker liberal arts college in Richmond, Indiana, sharing KAFU\'s values of integrity, community, and transformative education. The partnership supports student and staff exchange, joint curriculum development, and Quaker leadership programmes.',
                'website_url' => 'https://www.earlham.edu',
                'mou_date' => '2023-06-01',
                'mou_expiry' => '2027-05-31',
                'collaboration_areas' => ['student_exchange', 'staff_exchange', 'joint_curriculum', 'quaker_studies'],
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'slug' => 'woodbrooke-quaker-study-centre',
                'name' => 'Woodbrooke Quaker Study Centre',
                'short_name' => 'Woodbrooke',
                'country' => 'United Kingdom',
                'country_code' => 'GBR',
                'type' => 'quaker',
                'status' => 'active',
                'description' => 'Based in Birmingham, Woodbrooke is the Quaker study and research centre for Britain, offering leadership development and spiritual formation programmes. KAFU and Woodbrooke collaborate on Quaker peace studies, leadership training, and curriculum exchange.',
                'website_url' => 'https://www.woodbrooke.org.uk',
                'mou_date' => '2022-09-15',
                'collaboration_areas' => ['quaker_studies', 'leadership_development', 'peace_studies', 'staff_exchange'],
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'slug' => 'makerere-university',
                'name' => 'Makerere University',
                'short_name' => 'Makerere',
                'country' => 'Uganda',
                'country_code' => 'UGA',
                'type' => 'university',
                'status' => 'active',
                'description' => 'East Africa\'s oldest and most prestigious university, Makerere University in Kampala is a key regional partner. The collaboration focuses on postgraduate research, joint PhD supervision, staff exchange, and shared academic resources in health sciences and social sciences.',
                'website_url' => 'https://www.mak.ac.ug',
                'mou_date' => '2024-01-20',
                'mou_expiry' => '2028-01-19',
                'collaboration_areas' => ['research', 'student_exchange', 'staff_exchange', 'joint_degrees', 'postgraduate'],
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'slug' => 'university-of-nairobi',
                'name' => 'University of Nairobi',
                'short_name' => 'UoN',
                'country' => 'Kenya',
                'country_code' => 'KEN',
                'type' => 'university',
                'status' => 'active',
                'description' => 'Kenya\'s oldest university and a leading research institution. KAFU\'s partnership with the University of Nairobi facilitates student mobility, shared research projects in health and agriculture, and cross-registration for postgraduate programmes.',
                'website_url' => 'https://www.uonbi.ac.ke',
                'mou_date' => '2021-03-10',
                'collaboration_areas' => ['research', 'student_exchange', 'postgraduate', 'health_sciences'],
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'slug' => 'university-of-ghana',
                'name' => 'University of Ghana',
                'short_name' => 'UG Legon',
                'country' => 'Ghana',
                'country_code' => 'GHA',
                'type' => 'university',
                'status' => 'active',
                'description' => 'Ghana\'s premier university, located in Legon, Accra. The partnership with KAFU supports West-East African academic exchange, joint research on digital governance and agricultural development, and student mobility under the African Union Agenda 2063 framework.',
                'website_url' => 'https://www.ug.edu.gh',
                'mou_date' => '2023-11-05',
                'collaboration_areas' => ['research', 'student_exchange', 'digital_governance', 'agriculture'],
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'slug' => 'iita',
                'name' => 'International Institute of Tropical Agriculture',
                'short_name' => 'IITA',
                'country' => 'Nigeria',
                'country_code' => 'NGA',
                'type' => 'research_institute',
                'status' => 'active',
                'description' => 'A CGIAR Research Centre headquartered in Ibadan, Nigeria, IITA is a world leader in tropical agriculture research. KAFU\'s partnership enables collaborative research on food security, agroforestry, and soil health, with co-supervision of postgraduate students and joint grant applications.',
                'website_url' => 'https://www.iita.org',
                'mou_date' => '2024-03-18',
                'collaboration_areas' => ['research', 'postgraduate', 'food_security', 'agroforestry'],
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'slug' => 'usaid-kenya',
                'name' => 'USAID Kenya & East Africa',
                'short_name' => 'USAID Kenya',
                'country' => 'United States',
                'country_code' => 'USA',
                'type' => 'development_agency',
                'status' => 'active',
                'description' => 'The United States Agency for International Development funds several KAFU research projects in water quality, community health, and financial inclusion. The partnership provides research grants, capacity building support, and opportunities for KAFU researchers to engage with USAID\'s broader development agenda in Kenya.',
                'website_url' => 'https://www.usaid.gov/kenya',
                'mou_date' => '2023-09-01',
                'collaboration_areas' => ['research_funding', 'capacity_building', 'water_sanitation', 'health'],
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'slug' => 'friends-world-committee',
                'name' => 'Friends World Committee for Consultation',
                'short_name' => 'FWCC',
                'country' => 'International',
                'country_code' => 'INT',
                'type' => 'quaker',
                'status' => 'active',
                'description' => 'The FWCC connects Quaker communities and institutions worldwide. KAFU\'s relationship with FWCC facilitates connections with Quaker universities globally, access to Quaker scholarship funds, and participation in global Quaker higher education networks.',
                'website_url' => 'https://www.fwcc.world',
                'mou_date' => '2020-05-01',
                'collaboration_areas' => ['quaker_network', 'scholarship', 'global_engagement'],
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'slug' => 'african-development-bank',
                'name' => 'African Development Bank',
                'short_name' => 'AfDB',
                'country' => 'Ivory Coast',
                'country_code' => 'CIV',
                'type' => 'development_agency',
                'status' => 'active',
                'description' => 'The African Development Bank Group funds KAFU\'s Agroforestry and Sustainable Landscapes Research Programme. The partnership supports multi-country agricultural research and connects KAFU researchers with the AfDB\'s Pan-African network of agricultural scientists and development practitioners.',
                'website_url' => 'https://www.afdb.org',
                'collaboration_areas' => ['research_funding', 'agriculture', 'sustainable_development'],
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'slug' => 'guilford-college',
                'name' => 'Guilford College',
                'short_name' => 'Guilford',
                'country' => 'United States',
                'country_code' => 'USA',
                'type' => 'quaker',
                'status' => 'active',
                'description' => 'A Quaker liberal arts college in Greensboro, North Carolina, Guilford College partners with KAFU on Quaker leadership and peacebuilding education. The partnership includes faculty exchange, joint workshops, and shared curriculum resources for peace and conflict studies.',
                'website_url' => 'https://www.guilford.edu',
                'mou_date' => '2022-08-20',
                'collaboration_areas' => ['quaker_studies', 'peace_studies', 'staff_exchange', 'leadership_development'],
                'is_featured' => false,
                'sort_order' => 10,
            ],
        ];

        foreach ($partnerships as $data) {
            InternationalPartnership::firstOrCreate(['slug' => $data['slug']], $data);
        }
    }

    private function seedExchangeProgrammes(): void
    {
        $earlham = InternationalPartnership::where('slug', 'earlham-college')->first();
        $makerere = InternationalPartnership::where('slug', 'makerere-university')->first();
        $woodbrooke = InternationalPartnership::where('slug', 'woodbrooke-quaker-study-centre')->first();
        $guilford = InternationalPartnership::where('slug', 'guilford-college')->first();
        $iita = InternationalPartnership::where('slug', 'iita')->first();

        $programmes = [
            [
                'slug' => 'kafu-earlham-student-exchange',
                'title' => 'KAFU–Earlham College Student Exchange',
                'type' => 'student_exchange',
                'partnership_id' => $earlham?->id,
                'partner_name' => 'Earlham College',
                'partner_country' => 'United States',
                'description' => 'A semester-long student exchange programme between KAFU and Earlham College. KAFU students experience a Quaker liberal arts environment in Indiana, USA, while Earlham students come to Kaimosi to engage with KAFU\'s community development, health, and agriculture programmes. Exchange students pay tuition at their home institution and receive full credit transfer.',
                'duration_weeks' => 17,
                'duration_label' => 'One semester (4 months)',
                'application_deadline' => '2026-04-30',
                'next_intake' => 'September 2026',
                'slots_available' => 5,
                'stipend_amount' => 1500.00,
                'stipend_currency' => 'USD',
                'eligibility' => [
                    'Minimum Year 2 undergraduate student',
                    'Minimum GPA of 3.0 (or equivalent)',
                    'Letter of recommendation from academic supervisor',
                    'Proficiency in English',
                ],
                'benefits' => [
                    'Tuition waiver (home institution tuition applies)',
                    'Return economy airfare (KAFU-to-USA)',
                    'USD 1,500 travel stipend',
                    'Campus accommodation provided',
                    'Full academic credit transfer',
                    'Cultural orientation programme',
                ],
                'required_documents' => [
                    'Completed application form',
                    'Official academic transcripts',
                    'Two letters of recommendation',
                    'Personal statement (500 words)',
                    'Copy of valid passport',
                    'Medical clearance certificate',
                ],
                'status' => 'open',
                'is_featured' => true,
            ],
            [
                'slug' => 'quaker-leadership-woodbrooke',
                'title' => 'Quaker Leadership & Peace Studies — Woodbrooke',
                'type' => 'summer_school',
                'partnership_id' => $woodbrooke?->id,
                'partner_name' => 'Woodbrooke Quaker Study Centre',
                'partner_country' => 'United Kingdom',
                'description' => 'A 6-week intensive summer programme at Woodbrooke in Birmingham, UK, focused on Quaker approaches to leadership, peacebuilding, and community transformation. Open to KAFU staff and postgraduate students. Participants engage with Quaker history, spirituality, conflict resolution, and applied ethics in a residential setting.',
                'duration_weeks' => 6,
                'duration_label' => '6 weeks (July–August)',
                'application_deadline' => '2026-05-15',
                'next_intake' => 'July 2026',
                'slots_available' => 4,
                'stipend_amount' => 2000.00,
                'stipend_currency' => 'GBP',
                'eligibility' => [
                    'KAFU staff or postgraduate student',
                    'Demonstrated interest in Quaker values or peacebuilding',
                    'Approval from Head of Department',
                ],
                'benefits' => [
                    'Full programme fees covered by KAFU-Woodbrooke scholarship',
                    'GBP 2,000 living allowance',
                    'Return economy airfare',
                    'Residential accommodation at Woodbrooke',
                    'Certificate of completion (Woodbrooke accredited)',
                ],
                'required_documents' => [
                    'Application form',
                    'Statement of purpose (Quaker values & peacebuilding)',
                    'HoD endorsement letter',
                    'Curriculum vitae',
                    'Valid passport',
                ],
                'status' => 'open',
                'is_featured' => true,
            ],
            [
                'slug' => 'kafu-makerere-postgraduate-exchange',
                'title' => 'KAFU–Makerere University Postgraduate Research Exchange',
                'type' => 'research_fellowship',
                'partnership_id' => $makerere?->id,
                'partner_name' => 'Makerere University',
                'partner_country' => 'Uganda',
                'description' => 'A three-month research residency for KAFU PhD and Masters students at Makerere University in Kampala, Uganda. Fellows join active research groups in health sciences, education, or social sciences, with co-supervision by Makerere faculty. The programme strengthens East African research networks and supports cross-institutional PhD completion.',
                'duration_weeks' => 12,
                'duration_label' => 'One semester (3 months)',
                'application_deadline' => '2026-06-30',
                'next_intake' => 'September 2026',
                'slots_available' => 3,
                'stipend_amount' => 800.00,
                'stipend_currency' => 'USD',
                'eligibility' => [
                    'Registered KAFU postgraduate student (Masters or PhD)',
                    'Active research project with ethical clearance',
                    'Supervisor approval',
                    'Valid Ugandan visa eligibility',
                ],
                'benefits' => [
                    'Monthly stipend of USD 800',
                    'Return bus/shuttle transport (Kaimosi–Kampala)',
                    'Shared student accommodation on Makerere campus',
                    'Library and laboratory access at Makerere',
                    'Co-supervision by Makerere faculty',
                ],
                'required_documents' => [
                    'Postgraduate enrolment letter',
                    'Research proposal summary',
                    'Supervisor recommendation letter',
                    'Ethical clearance certificate (if applicable)',
                    'Valid passport',
                ],
                'status' => 'open',
                'is_featured' => true,
            ],
            [
                'slug' => 'iita-agricultural-research-internship',
                'title' => 'IITA Agricultural Research Internship',
                'type' => 'internship',
                'partnership_id' => $iita?->id,
                'partner_name' => 'International Institute of Tropical Agriculture',
                'partner_country' => 'Nigeria',
                'description' => 'A competitive 8-week research internship at IITA headquarters in Ibadan, Nigeria, for KAFU students in agriculture, food science, and environmental studies. Interns join active CGIAR research teams working on food systems, crop improvement, and climate-smart agriculture. A unique opportunity to work within a world-class international agricultural research environment.',
                'duration_weeks' => 8,
                'duration_label' => '8 weeks',
                'application_deadline' => '2026-03-31',
                'next_intake' => 'June 2026',
                'slots_available' => 2,
                'stipend_amount' => 600.00,
                'stipend_currency' => 'USD',
                'eligibility' => [
                    'Year 3 or 4 undergraduate, or Masters student',
                    'Enrolled in Agriculture, Food Science, Environmental Studies, or related field',
                    'Minimum GPA of 3.2',
                    'Demonstrated research experience or project',
                ],
                'benefits' => [
                    'USD 600/month stipend',
                    'Return economy airfare (Nairobi–Lagos/Ibadan)',
                    'IITA campus accommodation',
                    'Mentorship from CGIAR scientists',
                    'Research publication co-authorship opportunity',
                    'IITA internship certificate',
                ],
                'required_documents' => [
                    'Application form',
                    'Academic transcripts',
                    'Two academic reference letters',
                    'Research/study interest statement',
                    'Valid passport',
                    'Medical fitness certificate',
                ],
                'status' => 'open',
                'is_featured' => false,
            ],
            [
                'slug' => 'guilford-peacebuilding-exchange',
                'title' => 'Guilford College Peacebuilding & Leadership Exchange',
                'type' => 'student_exchange',
                'partnership_id' => $guilford?->id,
                'partner_name' => 'Guilford College',
                'partner_country' => 'United States',
                'description' => 'A semester exchange programme between KAFU and Guilford College in Greensboro, North Carolina. Students engage with Guilford\'s nationally recognised peace and conflict studies, social justice, and Quaker leadership programmes. Focus areas include restorative justice, environmental peacebuilding, and global Quaker activism.',
                'duration_weeks' => 17,
                'duration_label' => 'One semester (4 months)',
                'application_deadline' => '2026-05-01',
                'next_intake' => 'September 2026',
                'slots_available' => 3,
                'stipend_amount' => 1200.00,
                'stipend_currency' => 'USD',
                'eligibility' => [
                    'Year 2+ undergraduate student',
                    'Interest in peace, conflict, or social justice studies',
                    'Minimum GPA of 2.8',
                    'Proficiency in English',
                ],
                'benefits' => [
                    'Tuition waiver',
                    'USD 1,200 travel grant',
                    'Campus housing at Guilford',
                    'Full credit transfer',
                    'Quaker studies elective modules',
                ],
                'required_documents' => [
                    'Application form',
                    'Academic transcripts',
                    'Personal statement',
                    'One recommendation letter',
                    'Valid passport',
                ],
                'status' => 'upcoming',
                'is_featured' => false,
            ],
            [
                'slug' => 'staff-research-mobility-east-africa',
                'title' => 'East African Staff Research Mobility Grant',
                'type' => 'staff_exchange',
                'partnership_id' => null,
                'partner_name' => 'Multiple East African Universities',
                'partner_country' => 'Kenya, Uganda, Tanzania, Rwanda',
                'description' => 'An open staff mobility scheme enabling KAFU academic staff to spend 4–8 weeks as visiting researchers at partner universities across East Africa (University of Nairobi, Makerere University, University of Dar es Salaam, University of Rwanda). The scheme supports joint publication, curriculum alignment, and regional academic networking.',
                'duration_weeks' => 6,
                'duration_label' => '4 to 8 weeks (flexible)',
                'application_deadline' => null,
                'next_intake' => 'Rolling (apply any time)',
                'slots_available' => 6,
                'stipend_amount' => 500.00,
                'stipend_currency' => 'USD',
                'eligibility' => [
                    'KAFU academic staff (lecturer or above)',
                    'Active research project at KAFU',
                    'Hosting agreement from receiving institution',
                    'Dean or VC approval',
                ],
                'benefits' => [
                    'USD 500/month living allowance',
                    'Travel costs covered (up to KES 30,000)',
                    'University affiliation letter from host institution',
                    'Access to host institution library and facilities',
                    'Joint publication support',
                ],
                'required_documents' => [
                    'Staff mobility application form',
                    'Research plan (2 pages)',
                    'Letter of invitation from host institution',
                    'Dean endorsement',
                ],
                'status' => 'open',
                'is_featured' => false,
            ],
        ];

        foreach ($programmes as $data) {
            ExchangeProgramme::firstOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
