<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RepositoryItem;

class RepositorySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ── THESES & DISSERTATIONS ──────────────────────────────────────
            [
                'slug'           => 'effectiveness-community-health-workers-western-kenya-2024',
                'title'          => 'Effectiveness of Community Health Workers in Reducing Under-Five Mortality in Western Kenya: A Mixed-Methods Study',
                'type'           => 'thesis',
                'abstract'       => 'This study investigates the role of community health workers (CHWs) in reducing under-five mortality in Vihiga, Kakamega, and Kisumu counties. Using mixed methods, the research finds that CHWs trained under the Kenya Community Health Strategy significantly improve care-seeking behaviour and reduce mortality by 18% in intervention areas. The study recommends scale-up of CHW programmes and increased government support for training and supervision.',
                'authors'        => [['name' => 'Achieng, Miriam O.', 'role' => 'student']],
                'keywords'       => ['community health workers', 'child mortality', 'Western Kenya', 'public health', 'mixed methods'],
                'department'     => 'SHS',
                'research_theme' => 'Public Health',
                'year'           => 2024,
                'student_name'   => 'Miriam O. Achieng',
                'supervisor'     => 'Prof. Daniel Wafula, Dr. Susan Nekesa',
                'degree'         => 'Masters in Public Health',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/achieng-phd-chw-western-kenya-2024.pdf',
                'file_size_kb'   => 3412,
                'citation_count' => 4,
                'downloads'      => 312,
                'views'          => 1104,
                'funded_by'      => 'KAFU Research Fund',
                'status'         => 'published',
            ],
            [
                'slug'           => 'phd-digital-financial-inclusion-rural-kenya-2023',
                'title'          => 'Digital Financial Inclusion and Household Welfare Outcomes in Rural Kenya: Evidence from Mobile Money Adoption',
                'type'           => 'dissertation',
                'abstract'       => 'Mobile money services have dramatically altered financial landscapes across sub-Saharan Africa. This dissertation investigates the causal effect of mobile money adoption on household consumption, savings behaviour, and resilience to shocks among rural households in Western Kenya. Using a difference-in-differences design with household panel data, the study finds that mobile money adoption increases per-capita consumption by 6.4% and improves resilience to income shocks. Policy implications for regulators and financial inclusion programmes are discussed.',
                'authors'        => [['name' => 'Simiyu, Kelvin W.', 'role' => 'student']],
                'keywords'       => ['mobile money', 'financial inclusion', 'rural Kenya', 'household welfare', 'M-Pesa'],
                'department'     => 'SBE',
                'research_theme' => 'Digital Innovation',
                'year'           => 2023,
                'student_name'   => 'Kelvin W. Simiyu',
                'supervisor'     => 'Dr. James Odhiambo, Prof. Lydia Oluoch',
                'degree'         => 'Doctor of Philosophy (Economics)',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/simiyu-phd-mobile-money-2023.pdf',
                'file_size_kb'   => 5820,
                'citation_count' => 11,
                'downloads'      => 879,
                'views'          => 2341,
                'funded_by'      => 'African Development Bank Research Grant',
                'status'         => 'published',
            ],
            [
                'slug'           => 'msc-agroforestry-smallholder-food-security-2024',
                'title'          => 'Agroforestry Systems and Smallholder Food Security in Nandi County: A Comparative Analysis',
                'type'           => 'thesis',
                'abstract'       => 'This thesis assesses the contribution of agroforestry systems to food security among smallholder farmers in Nandi County, Kenya. Using structured interviews with 340 households and dietary diversity scores, the study finds that farms integrating fruit trees and woodlots achieve 23% higher dietary diversity scores than monoculture farms. Indigenous tree species integration is particularly associated with improved food outcomes during dry seasons.',
                'authors'        => [['name' => 'Rotich, Emmanuel K.', 'role' => 'student']],
                'keywords'       => ['agroforestry', 'food security', 'Nandi County', 'smallholder farmers', 'dietary diversity'],
                'department'     => 'SOS',
                'research_theme' => 'Agriculture & Natural Resources',
                'year'           => 2024,
                'student_name'   => 'Emmanuel K. Rotich',
                'supervisor'     => 'Dr. Faith Chebet, Prof. Samuel Maritim',
                'degree'         => 'Masters of Science (Agroforestry)',
                'license'        => 'cc_by_nc',
                'access'         => 'open',
                'file_url'       => '/storage/repository/rotich-msc-agroforestry-2024.pdf',
                'file_size_kb'   => 2890,
                'citation_count' => 2,
                'downloads'      => 190,
                'views'          => 641,
                'funded_by'      => 'IITA-Kenya',
                'status'         => 'published',
            ],

            // ── JOURNAL ARTICLES ────────────────────────────────────────────
            [
                'slug'           => 'teacher-professional-development-quaker-schools-africa-2024',
                'title'          => 'Teacher Professional Development in Quaker Schools Across East Africa: Practices, Challenges, and Outcomes',
                'type'           => 'journal_article',
                'abstract'       => 'This study examines professional development practices in Quaker-affiliated schools across Kenya, Uganda, and Tanzania. Through qualitative interviews with 62 teachers and 14 school heads, we identify three dominant models — mentoring-based, workshop-based, and peer-learning communities — and evaluate their effectiveness on teacher retention and student outcomes. We find that peer-learning communities yield the strongest gains and argue for Quaker education networks to formalise this approach.',
                'authors'        => [
                    ['name' => 'Wanyama, Fred A.', 'staff_slug' => 'dr-fred-wanyama', 'role' => 'lead'],
                    ['name' => 'Mutua, Jane N.', 'role' => 'co-author'],
                ],
                'keywords'       => ['teacher development', 'Quaker education', 'East Africa', 'professional learning communities'],
                'department'     => 'SESS',
                'research_theme' => 'Education & Quaker Studies',
                'year'           => 2024,
                'journal_name'   => 'Journal of Educational Research in Africa',
                'volume'         => '12',
                'issue'          => '3',
                'pages'          => '44–67',
                'doi'            => '10.21504/jera.2024.12.3.44',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/wanyama-quaker-teacher-development-2024.pdf',
                'file_size_kb'   => 980,
                'citation_count' => 7,
                'downloads'      => 543,
                'views'          => 1892,
                'status'         => 'published',
            ],
            [
                'slug'           => 'water-quality-household-level-kaimosi-region-2023',
                'title'          => 'Household-Level Water Quality Assessment and Health Outcomes in the Kaimosi-Hamisi Corridor, Western Kenya',
                'type'           => 'journal_article',
                'abstract'       => 'Access to safe drinking water remains a challenge in peri-urban and rural Western Kenya. This study assessed bacteriological and chemical quality of drinking water from 280 households in the Kaimosi-Hamisi corridor and linked contamination levels to diarrhoeal disease incidence. Results indicate 61% of households consume water failing WHO bacteriological standards. Household water treatment using sodium hypochlorite was found to reduce E. coli contamination by 84%. The study recommends targeted WASH interventions and community education campaigns.',
                'authors'        => [
                    ['name' => 'Otieno, Beatrice A.', 'staff_slug' => 'dr-beatrice-otieno', 'role' => 'lead'],
                    ['name' => 'Mukhwana, Eric J.', 'role' => 'co-author'],
                ],
                'keywords'       => ['water quality', 'WASH', 'Western Kenya', 'diarrhoeal disease', 'household water treatment'],
                'department'     => 'SHS',
                'research_theme' => 'Water & Environment',
                'year'           => 2023,
                'journal_name'   => 'African Journal of Environmental Health',
                'volume'         => '9',
                'issue'          => '1',
                'pages'          => '12–29',
                'doi'            => '10.1093/ajeh.2023.9.1.12',
                'publisher'      => 'Oxford Academic',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/otieno-water-quality-kaimosi-2023.pdf',
                'file_size_kb'   => 1240,
                'citation_count' => 14,
                'downloads'      => 1120,
                'views'          => 3410,
                'funded_by'      => 'USAID-Kenya WASH Programme',
                'status'         => 'published',
            ],
            [
                'slug'           => 'sme-financing-western-kenya-commercial-banks-2023',
                'title'          => 'Access to Finance for Small and Medium Enterprises in Western Kenya: The Role of Commercial Banks and SACCOs',
                'type'           => 'journal_article',
                'abstract'       => 'This paper examines financing barriers faced by SMEs in Kakamega, Bungoma, and Vihiga counties. Using survey data from 412 SME owners and multilevel regression, we find that collateral requirements, high interest rates, and financial illiteracy are the primary barriers. SACCOs outperform commercial banks in SME outreach in rural areas. The study recommends blended finance instruments and credit guarantee schemes.',
                'authors'        => [
                    ['name' => 'Namukasa, Patricia A.', 'staff_slug' => 'dr-patricia-namukasa', 'role' => 'lead'],
                ],
                'keywords'       => ['SME finance', 'SACCO', 'Western Kenya', 'banking', 'financial barriers'],
                'department'     => 'SBE',
                'research_theme' => 'Business & Economics',
                'year'           => 2023,
                'journal_name'   => 'African Journal of Finance and Management',
                'volume'         => '31',
                'issue'          => '2',
                'pages'          => '88–109',
                'doi'            => '10.1504/ajfm.2023.31.2.88',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/namukasa-sme-finance-2023.pdf',
                'file_size_kb'   => 1050,
                'citation_count' => 9,
                'downloads'      => 701,
                'views'          => 2108,
                'status'         => 'published',
            ],
            [
                'slug'           => 'crop-disease-early-detection-ml-model-2024',
                'title'          => 'Early Detection of Maize Streak Virus Using Convolutional Neural Networks and Mobile Imaging: A Field Study in Western Kenya',
                'type'           => 'journal_article',
                'abstract'       => 'Maize streak virus (MSV) causes significant yield losses among smallholder farmers in East Africa. This paper presents a convolutional neural network (CNN) model trained on 12,000 annotated leaf images to detect MSV infection at early stages using smartphone cameras. Field trials across 14 farms in Bungoma and Kakamega show 92.3% accuracy at early detection, enabling timely intervention. The model is deployed as an open-source mobile application (KafuFarm-AI) for farmer use.',
                'authors'        => [
                    ['name' => 'Omondi, Victor A.', 'staff_slug' => 'dr-victor-omondi', 'role' => 'lead'],
                    ['name' => 'Chepkemoi, Ruth', 'role' => 'co-author'],
                ],
                'keywords'       => ['machine learning', 'crop disease detection', 'maize streak virus', 'CNN', 'precision agriculture'],
                'department'     => 'SCIT',
                'research_theme' => 'Digital Innovation',
                'year'           => 2024,
                'journal_name'   => 'Computers and Electronics in Agriculture',
                'volume'         => '218',
                'issue'          => null,
                'pages'          => '108624',
                'doi'            => '10.1016/j.compag.2024.108624',
                'publisher'      => 'Elsevier',
                'license'        => 'cc_by_nc',
                'access'         => 'open',
                'file_url'       => '/storage/repository/omondi-maize-cnn-2024.pdf',
                'file_size_kb'   => 2180,
                'citation_count' => 18,
                'downloads'      => 2340,
                'views'          => 6710,
                'funded_by'      => 'IITA Agricultural Innovation Grant',
                'status'         => 'published',
            ],
            [
                'slug'           => 'nurses-burnout-rural-public-hospitals-kenya-2023',
                'title'          => 'Occupational Burnout Among Nurses in Rural Public Hospitals in Kenya: Prevalence, Risk Factors, and Mitigation Strategies',
                'type'           => 'journal_article',
                'abstract'       => 'Nurse burnout is a significant driver of staff attrition in Kenya\'s rural health facilities. This cross-sectional study surveyed 388 nurses across 16 public hospitals in Western Kenya using the Maslach Burnout Inventory. Burnout prevalence was 47.2%, with emotional exhaustion the dominant subscale. Key risk factors included high patient-to-nurse ratios, inadequate supplies, and limited career development opportunities. The study recommends structured supervision, peer support groups, and workload redistribution.',
                'authors'        => [
                    ['name' => 'Wekesa, Agnes M.', 'staff_slug' => 'dr-agnes-wekesa', 'role' => 'lead'],
                    ['name' => 'Mwangi, Purity K.', 'role' => 'co-author'],
                ],
                'keywords'       => ['nurse burnout', 'occupational health', 'rural hospitals', 'Kenya', 'Maslach Burnout Inventory'],
                'department'     => 'SHS',
                'research_theme' => 'Public Health',
                'year'           => 2023,
                'journal_name'   => 'International Journal of Nursing Studies',
                'volume'         => '142',
                'pages'          => '104494',
                'doi'            => '10.1016/j.ijnurstu.2023.104494',
                'publisher'      => 'Elsevier',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/wekesa-nurse-burnout-2023.pdf',
                'file_size_kb'   => 890,
                'citation_count' => 22,
                'downloads'      => 1890,
                'views'          => 4501,
                'status'         => 'published',
            ],

            // ── CONFERENCE PAPERS ───────────────────────────────────────────
            [
                'slug'           => 'blockchain-land-registry-western-kenya-2023',
                'title'          => 'Towards Transparent Land Registry: A Blockchain-Based Prototype for Western Kenya Land Administration',
                'type'           => 'conference_paper',
                'abstract'       => 'Land tenure disputes are a persistent socioeconomic challenge in Western Kenya. This paper presents a prototype blockchain-based land registry system designed for the Kenyan legal framework. Using Hyperledger Fabric, the system records land transactions immutably, reduces fraud potential, and enables citizen verification of land records via a mobile interface. Pilot testing with 40 community members demonstrated ease of use and improved trust in land records.',
                'authors'        => [
                    ['name' => 'Masinde, Jared O.', 'staff_slug' => 'dr-jared-masinde', 'role' => 'lead'],
                    ['name' => 'Kimani, Faith W.', 'role' => 'co-author'],
                ],
                'keywords'       => ['blockchain', 'land registry', 'Hyperledger Fabric', 'Kenya', 'digital governance'],
                'department'     => 'SCIT',
                'research_theme' => 'Digital Innovation',
                'year'           => 2023,
                'publisher'      => 'IEEE',
                'journal_name'   => 'Proceedings of the IEEE Africa Computer Science Conference (AfricaCSC 2023)',
                'pages'          => '124–131',
                'doi'            => '10.1109/AfricaCSC.2023.124',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/masinde-blockchain-land-2023.pdf',
                'file_size_kb'   => 650,
                'citation_count' => 6,
                'downloads'      => 445,
                'views'          => 1233,
                'status'         => 'published',
            ],
            [
                'slug'           => 'inclusive-education-children-disabilities-kenya-2024',
                'title'          => 'Barriers to Inclusive Education for Children with Disabilities in Western Kenya Primary Schools',
                'type'           => 'conference_paper',
                'abstract'       => 'Despite policy commitments, inclusive education remains under-resourced in Kenya. This paper draws on case studies from 12 primary schools in Kakamega County to document physical, attitudinal, and pedagogical barriers. Teacher training, infrastructure modifications, and community engagement emerge as priority intervention areas. The study contributes to debates on universal basic education and sustainable development goal 4.',
                'authors'        => [
                    ['name' => 'Andisi, Rebecca N.', 'staff_slug' => 'dr-rebecca-andisi', 'role' => 'lead'],
                ],
                'keywords'       => ['inclusive education', 'disability', 'primary schools', 'Kenya', 'SDG 4'],
                'department'     => 'SESS',
                'research_theme' => 'Education & Quaker Studies',
                'year'           => 2024,
                'publisher'      => 'African Educational Research Network',
                'journal_name'   => 'Proceedings of the 16th African Educational Research Conference',
                'pages'          => '78–89',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/andisi-inclusive-education-2024.pdf',
                'file_size_kb'   => 540,
                'citation_count' => 3,
                'downloads'      => 210,
                'views'          => 788,
                'status'         => 'published',
            ],

            // ── RESEARCH REPORTS ────────────────────────────────────────────
            [
                'slug'           => 'kafu-water-sanitation-baseline-2023',
                'title'          => 'WASH Baseline Assessment Report: Kaimosi Sub-County Water and Sanitation Coverage, 2023',
                'type'           => 'research_report',
                'abstract'       => 'This report presents baseline data on water and sanitation access across 48 villages in Kaimosi Sub-County collected between January and March 2023. The survey covered 1,240 households. Key findings: 38% access improved water sources; 51% use open defecation sites; 12% have functioning hand-washing facilities. The report establishes benchmarks for a three-year USAID-funded WASH improvement project and informs county government planning.',
                'authors'        => [
                    ['name' => 'Otieno, Beatrice A.', 'staff_slug' => 'dr-beatrice-otieno', 'role' => 'lead'],
                    ['name' => 'Wafula, John M.', 'role' => 'co-author'],
                    ['name' => 'Nasimiyu, Carol', 'role' => 'researcher'],
                ],
                'keywords'       => ['WASH', 'water access', 'sanitation', 'Kaimosi', 'baseline survey'],
                'department'     => 'SHS',
                'research_theme' => 'Water & Environment',
                'year'           => 2023,
                'publisher'      => 'Kaimosi Friends University & USAID-Kenya',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/kafu-wash-baseline-2023.pdf',
                'file_size_kb'   => 3100,
                'funded_by'      => 'USAID-Kenya',
                'citation_count' => 5,
                'downloads'      => 622,
                'views'          => 1890,
                'status'         => 'published',
            ],
            [
                'slug'           => 'academic-integrity-policy-framework-kafu-2023',
                'title'          => 'Academic Integrity Policy Framework for KAFU: Review of Institutional Practices and Recommendations',
                'type'           => 'research_report',
                'abstract'       => 'This report reviews academic integrity challenges and institutional policies at Kaimosi Friends University. Drawing on a survey of 870 students and 64 academic staff, it documents prevalence of plagiarism, collusion, and exam misconduct. The report recommends adoption of a dedicated integrity management system, mandatory academic integrity orientation, and Quaker-values-based honour code. A policy template aligned with Kenya\'s University Standards and Guidelines (2014) is provided.',
                'authors'        => [
                    ['name' => 'Wanyama, Fred A.', 'staff_slug' => 'dr-fred-wanyama', 'role' => 'lead'],
                    ['name' => 'Simiyu, Grace L.', 'role' => 'researcher'],
                ],
                'keywords'       => ['academic integrity', 'plagiarism', 'policy', 'university governance', 'Quaker values'],
                'department'     => 'SESS',
                'research_theme' => 'Education & Quaker Studies',
                'year'           => 2023,
                'publisher'      => 'Kaimosi Friends University Senate',
                'license'        => 'cc_by_nc',
                'access'         => 'open',
                'file_url'       => '/storage/repository/kafu-academic-integrity-2023.pdf',
                'file_size_kb'   => 1820,
                'citation_count' => 1,
                'downloads'      => 334,
                'views'          => 1020,
                'status'         => 'published',
            ],
            [
                'slug'           => 'sugar-industry-economic-impact-western-kenya-2022',
                'title'          => 'Economic Impact of the Sugar Industry on Western Kenya Rural Livelihoods: A Household Income Analysis',
                'type'           => 'research_report',
                'abstract'       => 'Kenya\'s sugar industry is concentrated in Western Kenya and employs hundreds of thousands of smallholder farmers. This report analyses income contributions, market access, and vulnerability of sugar-dependent households using panel data from 820 households in Mumias, Busia, and Kakamega. Diversification into other cash crops and improved factory operations are recommended to reduce income volatility among cane farmers.',
                'authors'        => [
                    ['name' => 'Namukasa, Patricia A.', 'staff_slug' => 'dr-patricia-namukasa', 'role' => 'lead'],
                    ['name' => 'Oloo, Martin', 'role' => 'researcher'],
                ],
                'keywords'       => ['sugar industry', 'rural livelihoods', 'Western Kenya', 'household income', 'Mumias Sugar'],
                'department'     => 'SBE',
                'research_theme' => 'Agriculture & Natural Resources',
                'year'           => 2022,
                'publisher'      => 'Kaimosi Friends University & African Development Bank',
                'funded_by'      => 'African Development Bank',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/namukasa-sugar-industry-2022.pdf',
                'file_size_kb'   => 2670,
                'citation_count' => 8,
                'downloads'      => 891,
                'views'          => 2401,
                'status'         => 'published',
            ],

            // ── BOOK CHAPTERS ────────────────────────────────────────────────
            [
                'slug'           => 'peace-education-conflict-transformation-east-africa-chapter-2023',
                'title'          => 'Peace Education as Conflict Transformation: Lessons from Quaker-Founded Institutions in East Africa',
                'type'           => 'book_chapter',
                'abstract'       => 'This chapter examines how Quaker-founded educational institutions in East Africa have used peace education as a tool for conflict transformation in post-conflict communities. Drawing on historical analysis and interviews with educators at KAFU, Friends School Kamusinga, and Bukuru Quaker Secondary School, we identify key pedagogical approaches and structural conditions that enable peace education to move beyond curriculum content into community practice. The chapter concludes with a framework for replicating these approaches in other fragile contexts.',
                'authors'        => [
                    ['name' => 'Wanyama, Fred A.', 'staff_slug' => 'dr-fred-wanyama', 'role' => 'lead'],
                    ['name' => 'Kimani, Peter', 'role' => 'co-author'],
                ],
                'keywords'       => ['peace education', 'Quaker education', 'conflict transformation', 'East Africa'],
                'department'     => 'SESS',
                'research_theme' => 'Education & Quaker Studies',
                'year'           => 2023,
                'publisher'      => 'Routledge',
                'journal_name'   => 'Handbook of Peace Education in Sub-Saharan Africa',
                'pages'          => '213–236',
                'isbn_issn'      => '978-1-03-224571-9',
                'license'        => 'all_rights_reserved',
                'access'         => 'restricted',
                'file_url'       => null,
                'citation_count' => 12,
                'downloads'      => 0,
                'views'          => 890,
                'status'         => 'published',
            ],
            [
                'slug'           => 'mobile-health-sub-saharan-africa-chapter-2024',
                'title'          => 'Mobile Health Interventions for Maternal and Child Health in Sub-Saharan Africa: Evidence and Implementation Pathways',
                'type'           => 'book_chapter',
                'abstract'       => 'Mobile health (mHealth) technologies offer significant potential to address maternal and child health gaps in sub-Saharan Africa. This chapter reviews evidence from 34 mHealth interventions across 12 countries, synthesising lessons on design, scale-up, and sustainability. A KAFU-led pilot in Vihiga County using SMS reminders for antenatal care visits achieved a 31% increase in facility delivery rates. Implications for policy and health system strengthening are discussed.',
                'authors'        => [
                    ['name' => 'Achieng, Miriam O.', 'role' => 'lead'],
                    ['name' => 'Otieno, Beatrice A.', 'staff_slug' => 'dr-beatrice-otieno', 'role' => 'co-author'],
                ],
                'keywords'       => ['mHealth', 'maternal health', 'child health', 'SMS', 'Sub-Saharan Africa'],
                'department'     => 'SHS',
                'research_theme' => 'Public Health',
                'year'           => 2024,
                'publisher'      => 'Springer Nature',
                'journal_name'   => 'Digital Health Systems in Developing Economies',
                'pages'          => '88–114',
                'isbn_issn'      => '978-3-031-44210-4',
                'license'        => 'cc_by_nc',
                'access'         => 'restricted',
                'file_url'       => null,
                'citation_count' => 5,
                'downloads'      => 0,
                'views'          => 612,
                'status'         => 'published',
            ],

            // ── WORKING PAPERS ────────────────────────────────────────────────
            [
                'slug'           => 'kafu-climate-smart-agriculture-western-kenya-wp-2024',
                'title'          => 'Climate-Smart Agriculture Adoption Among Smallholders in Western Kenya: Constraints, Drivers, and Policy Recommendations',
                'type'           => 'working_paper',
                'abstract'       => 'Climate variability poses existential risks to smallholder agriculture in Western Kenya. This working paper analyses adoption constraints and drivers of climate-smart agricultural (CSA) practices among 560 farm households in Vihiga and Siaya counties. Using probit regression, we find that access to extension services, farmer group membership, and land tenure security are the strongest predictors of CSA adoption. We recommend strengthening county-level extension systems and integrating CSA into national agricultural policy frameworks.',
                'authors'        => [
                    ['name' => 'Chebet, Faith', 'staff_slug' => 'dr-faith-chebet', 'role' => 'lead'],
                    ['name' => 'Ngetich, Bernard', 'role' => 'co-author'],
                ],
                'keywords'       => ['climate-smart agriculture', 'adoption', 'Western Kenya', 'smallholder', 'extension services'],
                'department'     => 'SOS',
                'research_theme' => 'Agriculture & Natural Resources',
                'year'           => 2024,
                'publisher'      => 'Kaimosi Friends University Working Paper Series',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/chebet-csa-working-paper-2024.pdf',
                'file_size_kb'   => 780,
                'citation_count' => 0,
                'downloads'      => 143,
                'views'          => 490,
                'funded_by'      => 'IITA-Kenya',
                'status'         => 'published',
            ],
            [
                'slug'           => 'edtech-secondary-schools-kenya-digital-divide-wp-2023',
                'title'          => 'EdTech Adoption in Kenyan Secondary Schools: Bridging the Digital Divide in Rural and Peri-Urban Settings',
                'type'           => 'working_paper',
                'abstract'       => 'The roll-out of digital learning devices under Kenya\'s digital literacy programme has raised important questions about pedagogical readiness and infrastructure gaps. This working paper draws on data from 22 schools in Western Kenya to assess teacher readiness, connectivity challenges, and student engagement with EdTech tools. Electricity unreliability, limited bandwidth, and inadequate teacher training are the primary barriers identified. Recommendations for targeted ICT4Education investment are presented.',
                'authors'        => [
                    ['name' => 'Omondi, Victor A.', 'staff_slug' => 'dr-victor-omondi', 'role' => 'lead'],
                ],
                'keywords'       => ['EdTech', 'digital literacy', 'secondary schools', 'Kenya', 'ICT4Education'],
                'department'     => 'SCIT',
                'research_theme' => 'Digital Innovation',
                'year'           => 2023,
                'publisher'      => 'Kaimosi Friends University Working Paper Series',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/omondi-edtech-digital-divide-2023.pdf',
                'file_size_kb'   => 620,
                'citation_count' => 2,
                'downloads'      => 289,
                'views'          => 820,
                'status'         => 'published',
            ],

            // ── MORE THESES ─────────────────────────────────────────────────
            [
                'slug'           => 'phd-devolved-healthcare-financing-kenya-counties-2022',
                'title'          => 'Devolution and Healthcare Financing in Kenya: An Analysis of County Health Budget Allocations and Service Delivery Outcomes (2013–2022)',
                'type'           => 'dissertation',
                'abstract'       => 'Kenya\'s 2010 constitutional devolution transferred health services to 47 counties. This dissertation evaluates how devolved financing has affected healthcare service delivery outcomes in six Western Kenya counties over a ten-year period. Using a panel data approach and key informant interviews, the study finds that counties with stronger revenue-raising capacity and political commitment achieve better maternal health indicators. The research recommends equitable fiscal transfers and capacity building for county health departments.',
                'authors'        => [['name' => 'Owino, George P.', 'role' => 'student']],
                'keywords'       => ['devolution', 'healthcare financing', 'county health', 'Kenya', 'service delivery'],
                'department'     => 'SHS',
                'research_theme' => 'Public Health',
                'year'           => 2022,
                'student_name'   => 'George P. Owino',
                'supervisor'     => 'Prof. Daniel Wafula',
                'degree'         => 'Doctor of Philosophy (Health Systems)',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/owino-devolution-healthcare-2022.pdf',
                'file_size_kb'   => 6100,
                'citation_count' => 15,
                'downloads'      => 1340,
                'views'          => 3780,
                'status'         => 'published',
            ],
            [
                'slug'           => 'msc-it-governance-smes-western-kenya-2024',
                'title'          => 'IT Governance Maturity in SMEs: A Framework for Technology-Driven Growth in Western Kenya',
                'type'           => 'thesis',
                'abstract'       => 'Small and medium enterprises in Western Kenya increasingly rely on digital technologies, yet governance frameworks for technology adoption remain underdeveloped. This thesis proposes a lightweight IT governance maturity model (LGMM) adapted for the Kenyan SME context, validated through expert interviews and a survey of 180 SMEs in Kisumu and Kakamega. Three maturity stages are identified, with most enterprises in the initial stage. The proposed framework provides a practical roadmap for technology-driven growth.',
                'authors'        => [['name' => 'Barasa, Michael K.', 'role' => 'student']],
                'keywords'       => ['IT governance', 'SME', 'maturity model', 'technology', 'Western Kenya'],
                'department'     => 'SCIT',
                'research_theme' => 'Digital Innovation',
                'year'           => 2024,
                'student_name'   => 'Michael K. Barasa',
                'supervisor'     => 'Dr. Jared Masinde',
                'degree'         => 'Masters of Science (Information Systems)',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/barasa-it-governance-smes-2024.pdf',
                'file_size_kb'   => 2950,
                'citation_count' => 0,
                'downloads'      => 88,
                'views'          => 310,
                'status'         => 'published',
            ],
            [
                'slug'           => 'mba-corporate-governance-microfinance-kenya-2023',
                'title'          => 'Corporate Governance Practices and Financial Performance in Kenyan Microfinance Institutions',
                'type'           => 'thesis',
                'abstract'       => 'This MBA research examines the relationship between corporate governance practices and financial performance in 18 licensed microfinance institutions (MFIs) in Kenya over the period 2017–2022. Using board composition, ownership structure, and transparency indices, the study finds that MFIs with higher board independence and gender diversity achieve superior return on equity and lower non-performing loan ratios. Recommendations for MFI boards and regulators are provided.',
                'authors'        => [['name' => 'Nekesa, Esther A.', 'role' => 'student']],
                'keywords'       => ['corporate governance', 'microfinance', 'board composition', 'financial performance', 'Kenya'],
                'department'     => 'SBE',
                'research_theme' => 'Business & Economics',
                'year'           => 2023,
                'student_name'   => 'Esther A. Nekesa',
                'supervisor'     => 'Dr. James Odhiambo',
                'degree'         => 'Master of Business Administration',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/nekesa-mba-governance-mfi-2023.pdf',
                'file_size_kb'   => 1870,
                'citation_count' => 3,
                'downloads'      => 267,
                'views'          => 891,
                'status'         => 'published',
            ],

            // ── DATASET ────────────────────────────────────────────────────
            [
                'slug'           => 'kafu-western-kenya-crop-yield-dataset-2023',
                'title'          => 'Western Kenya Smallholder Crop Yield and Agricultural Practice Dataset 2019–2023 (KAFU-AgriData)',
                'type'           => 'dataset',
                'abstract'       => 'This dataset contains anonymised crop yield, input use, weather, and socioeconomic data for 1,800 smallholder farm households across Bungoma, Kakamega, and Vihiga counties collected annually from 2019 to 2023. Variables include maize and bean yields, fertiliser and seed inputs, rainfall data, land size, and household characteristics. The dataset is suitable for agricultural economics, climate-smart agriculture, and food security research.',
                'authors'        => [
                    ['name' => 'Chebet, Faith', 'staff_slug' => 'dr-faith-chebet', 'role' => 'lead'],
                    ['name' => 'Maritim, Samuel', 'role' => 'co-author'],
                ],
                'keywords'       => ['crop yield', 'smallholder', 'Western Kenya', 'dataset', 'agriculture', 'panel data'],
                'department'     => 'SOS',
                'research_theme' => 'Agriculture & Natural Resources',
                'year'           => 2023,
                'publisher'      => 'KAFU Research Data Repository',
                'doi'            => '10.5281/zenodo.kafu.agridata.2023',
                'license'        => 'cc_by',
                'access'         => 'open',
                'file_url'       => '/storage/repository/kafu-agridata-2023.zip',
                'file_size_kb'   => 8840,
                'funded_by'      => 'IITA-Kenya',
                'citation_count' => 7,
                'downloads'      => 390,
                'views'          => 1021,
                'status'         => 'published',
            ],
        ];

        foreach ($items as $item) {
            RepositoryItem::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
