<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SampleApplicationsSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('admissions_online_applications')->exists()) {
            return;
        }

        $now = now()->toDateTimeString();

        $apps = [
            [
                'reference_number' => 'KAFU-2026-000001', 'applicant_type' => 'undergraduate', 'status' => 'submitted',
                'first_name' => 'Amina', 'last_name' => 'Wanjiku', 'other_names' => 'Grace',
                'gender' => 'Female', 'date_of_birth' => '2003-04-12', 'nationality' => 'Kenyan',
                'id_passport_number' => '39821045', 'phone' => '+254712345001', 'email' => 'amina.wanjiku@gmail.com',
                'postal_address' => 'P.O. Box 100 - Kakamega', 'county' => 'Kakamega',
                'kcse_index_number' => '30100001001', 'kcse_year' => '2022', 'mean_grade' => 'B+',
                'degree_institution' => null, 'degree_class' => null, 'degree_year' => null, 'degree_field' => null,
                'school_code' => 'SESS', 'programme_code' => 'BED', 'programme_name' => 'Bachelor of Education (Arts)',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260501001',
                'payment_amount' => 1000, 'payment_phone' => '+254712345001', 'payment_at' => '2026-05-10 09:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-10 09:30:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000002', 'applicant_type' => 'undergraduate', 'status' => 'under_review',
                'first_name' => 'Brian', 'last_name' => 'Otieno', 'other_names' => '',
                'gender' => 'Male', 'date_of_birth' => '2004-08-22', 'nationality' => 'Kenyan',
                'id_passport_number' => '40123789', 'phone' => '+254723456002', 'email' => 'brian.otieno@gmail.com',
                'postal_address' => 'P.O. Box 200 - Kisumu', 'county' => 'Kisumu',
                'kcse_index_number' => '40200002002', 'kcse_year' => '2023', 'mean_grade' => 'A-',
                'degree_institution' => null, 'degree_class' => null, 'degree_year' => null, 'degree_field' => null,
                'school_code' => 'SCIT', 'programme_code' => 'BSC.CS', 'programme_name' => 'Bachelor of Science in Computer Science',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260502002',
                'payment_amount' => 1000, 'payment_phone' => '+254723456002', 'payment_at' => '2026-05-11 11:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-11 11:15:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000003', 'applicant_type' => 'masters', 'status' => 'offered',
                'first_name' => 'Collins', 'last_name' => 'Mwangi', 'other_names' => 'Karanja',
                'gender' => 'Male', 'date_of_birth' => '1988-01-15', 'nationality' => 'Kenyan',
                'id_passport_number' => '25678901', 'phone' => '+254733567003', 'email' => 'c.mwangi@yahoo.com',
                'postal_address' => 'P.O. Box 300 - Nairobi', 'county' => 'Nairobi',
                'kcse_index_number' => '', 'kcse_year' => '', 'mean_grade' => '',
                'degree_institution' => 'University of Nairobi', 'degree_class' => 'Second Class Honours (Upper Division)',
                'degree_year' => '2012', 'degree_field' => 'Business Administration',
                'school_code' => 'SBE', 'programme_code' => 'MBA', 'programme_name' => 'Master of Business Administration',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260503003',
                'payment_amount' => 1500, 'payment_phone' => '+254733567003', 'payment_at' => '2026-05-05 08:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-05 08:00:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000004', 'applicant_type' => 'undergraduate', 'status' => 'documents_queried',
                'first_name' => 'Faith', 'last_name' => 'Chebet', 'other_names' => '',
                'gender' => 'Female', 'date_of_birth' => '2002-11-30', 'nationality' => 'Kenyan',
                'id_passport_number' => '41234567', 'phone' => '+254744678004', 'email' => 'faith.chebet@gmail.com',
                'postal_address' => 'P.O. Box 400 - Eldoret', 'county' => 'Eldoret/Uasin Gishu',
                'kcse_index_number' => '22300004004', 'kcse_year' => '2021', 'mean_grade' => 'C+',
                'degree_institution' => null, 'degree_class' => null, 'degree_year' => null, 'degree_field' => null,
                'school_code' => 'SHS', 'programme_code' => 'BSCNURS', 'programme_name' => 'Bachelor of Science in Nursing',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260504004',
                'payment_amount' => 1000, 'payment_phone' => '+254744678004', 'payment_at' => '2026-05-12 14:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-12 14:45:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000005', 'applicant_type' => 'phd', 'status' => 'under_review',
                'first_name' => 'Agnes', 'last_name' => 'Achieng', 'other_names' => 'Owino',
                'gender' => 'Female', 'date_of_birth' => '1985-06-20', 'nationality' => 'Kenyan',
                'id_passport_number' => '22890123', 'phone' => '+254755789005', 'email' => 'a.achieng@kafu.ac.ke',
                'postal_address' => 'P.O. Box 500 - Vihiga', 'county' => 'Vihiga',
                'kcse_index_number' => '', 'kcse_year' => '', 'mean_grade' => '',
                'degree_institution' => 'Kenyatta University', 'degree_class' => 'Masters of Science',
                'degree_year' => '2015', 'degree_field' => 'Environmental Science',
                'school_code' => 'SOS', 'programme_code' => 'PHD.ENV', 'programme_name' => 'Doctor of Philosophy in Environmental Science',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260505005',
                'payment_amount' => 2000, 'payment_phone' => '+254755789005', 'payment_at' => '2026-05-08 10:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-08 10:00:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000006', 'applicant_type' => 'undergraduate', 'status' => 'rejected',
                'first_name' => 'Kevin', 'last_name' => 'Kiprop', 'other_names' => '',
                'gender' => 'Male', 'date_of_birth' => '2003-02-14', 'nationality' => 'Kenyan',
                'id_passport_number' => '42345678', 'phone' => '+254766890006', 'email' => 'kevin.kiprop@gmail.com',
                'postal_address' => 'P.O. Box 600 - Nandi', 'county' => 'Nandi',
                'kcse_index_number' => '31600006006', 'kcse_year' => '2022', 'mean_grade' => 'C',
                'degree_institution' => null, 'degree_class' => null, 'degree_year' => null, 'degree_field' => null,
                'school_code' => 'SBE', 'programme_code' => 'BCOMM', 'programme_name' => 'Bachelor of Commerce',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260506006',
                'payment_amount' => 1000, 'payment_phone' => '+254766890006', 'payment_at' => '2026-05-07 16:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-07 16:00:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000007', 'applicant_type' => 'undergraduate', 'status' => 'awaiting_payment',
                'first_name' => 'Mercy', 'last_name' => 'Nyambura', 'other_names' => 'Wangari',
                'gender' => 'Female', 'date_of_birth' => '2004-09-05', 'nationality' => 'Kenyan',
                'id_passport_number' => '43456789', 'phone' => '+254777901007', 'email' => 'mercy.nyambura@gmail.com',
                'postal_address' => 'P.O. Box 700 - Nyeri', 'county' => 'Nyeri',
                'kcse_index_number' => '21700007007', 'kcse_year' => '2023', 'mean_grade' => 'B',
                'degree_institution' => null, 'degree_class' => null, 'degree_year' => null, 'degree_field' => null,
                'school_code' => 'SHS', 'programme_code' => 'BSCOPTO', 'programme_name' => 'Bachelor of Science in Optometry',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'pending', 'payment_reference' => '',
                'payment_amount' => 1000, 'payment_phone' => '+254777901007', 'payment_at' => null,
                'extra_data' => null, 'submitted_at' => null,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000008', 'applicant_type' => 'masters', 'status' => 'accepted',
                'first_name' => 'James', 'last_name' => 'Mutua', 'other_names' => '',
                'gender' => 'Male', 'date_of_birth' => '1990-03-18', 'nationality' => 'Kenyan',
                'id_passport_number' => '28901234', 'phone' => '+254788012008', 'email' => 'james.mutua@gmail.com',
                'postal_address' => 'P.O. Box 800 - Machakos', 'county' => 'Machakos',
                'kcse_index_number' => '', 'kcse_year' => '', 'mean_grade' => '',
                'degree_institution' => 'Moi University', 'degree_class' => 'Second Class Honours (Lower Division)',
                'degree_year' => '2014', 'degree_field' => 'Information Technology',
                'school_code' => 'SCIT', 'programme_code' => 'MSIT', 'programme_name' => 'Master of Science in Information Technology',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260508008',
                'payment_amount' => 1500, 'payment_phone' => '+254788012008', 'payment_at' => '2026-04-30 09:00:00',
                'extra_data' => null, 'submitted_at' => '2026-04-30 09:00:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000009', 'applicant_type' => 'undergraduate', 'status' => 'eligible',
                'first_name' => 'Tabitha', 'last_name' => 'Maina', 'other_names' => '',
                'gender' => 'Female', 'date_of_birth' => '2003-07-17', 'nationality' => 'Kenyan',
                'id_passport_number' => '44567890', 'phone' => '+254799123009', 'email' => 'tabitha.maina@gmail.com',
                'postal_address' => 'P.O. Box 900 - Kiambu', 'county' => 'Kiambu',
                'kcse_index_number' => '11900009009', 'kcse_year' => '2022', 'mean_grade' => 'B+',
                'degree_institution' => null, 'degree_class' => null, 'degree_year' => null, 'degree_field' => null,
                'school_code' => 'SESS', 'programme_code' => 'BSCED', 'programme_name' => 'Bachelor of Science (Education)',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260509009',
                'payment_amount' => 1000, 'payment_phone' => '+254799123009', 'payment_at' => '2026-05-14 10:00:00',
                'extra_data' => null, 'submitted_at' => '2026-05-14 10:30:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'reference_number' => 'KAFU-2026-000010', 'applicant_type' => 'masters', 'status' => 'deferred',
                'first_name' => 'Peter', 'last_name' => 'Waweru', 'other_names' => 'Kamau',
                'gender' => 'Male', 'date_of_birth' => '1987-12-02', 'nationality' => 'Kenyan',
                'id_passport_number' => '21234567', 'phone' => '+254700234010', 'email' => 'p.waweru@gmail.com',
                'postal_address' => 'P.O. Box 1000 - Nakuru', 'county' => 'Nakuru',
                'kcse_index_number' => '', 'kcse_year' => '', 'mean_grade' => '',
                'degree_institution' => 'Egerton University', 'degree_class' => 'Second Class Honours (Lower Division)',
                'degree_year' => '2011', 'degree_field' => 'Agricultural Economics',
                'school_code' => 'SBE', 'programme_code' => 'MSECON', 'programme_name' => 'Master of Science in Economics',
                'second_choice_code' => '', 'second_choice_name' => '',
                'payment_status' => 'paid', 'payment_reference' => 'MPE20260510010',
                'payment_amount' => 1500, 'payment_phone' => '+254700234010', 'payment_at' => '2026-04-28 09:00:00',
                'extra_data' => null, 'submitted_at' => '2026-04-28 09:00:00',
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        DB::table('admissions_online_applications')->insert($apps);
    }
}
